### PR TITLE
Support memritv.org

### PR DESCRIPTION
**Pull request by atomicdryad**

### CODE REVIEW

**Comment by yan12125** [comment]
From the news post[1], memritv.org is involved in copyright infringement accusations. [youtube-dl's policy](https://github.com/rg3/youtube-dl/#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free) is that copyright infriging contents will not be supported. Do you have evidence indicating that memritv.org has gotten permissions for their translated contents now?

[1] http://www.breakingisraelnews.com/25270/youtube-disables-memri-tv-channel/#MXOVecrqcjtcwFXi.97

**Comment by yan12125** [comment]
Closing this PR as no response for a long time.

**Comment by jaimeMF** [comment]
As pointed by @arisboch in https://github.com/rg3/youtube-dl/issues/7403#issuecomment-155564486, the YouTube channel is available again (https://www.youtube.com/user/MEMRITVVideos). I think we can reconsider adding support for it.

**Comment by yan12125** [comment]
Since #8497 landed, please move changes in ```youtube_dl/extractors/__init__.py``` to ```youtube_dl/extractors/extractors.py```. Check step 5 of the new [developer instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#adding-support-for-a-new-site) for more information.

**Pull request closed without merging**
