### PR TITLE
[rai] Fixed extractor (closes ytdl-org#22923)

### PR DESCRIPTION
**Pull request by de666**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fixes [https://github.com/ytdl-org/youtube-dl/issues/22923](ytdl-org#22923)

### CODE REVIEW

**Comment by iamleot** [comment]
Hello @de666,
thanks for looking at it!

Unfortunately AFAICS the corresponding tests for `RaiPlay` extractor will still fail.
The first of it is no longer present and should be removed the second needs to be adjusted because probably some information is no longer available and changed a bit.

I have worked a bit on it and a WIP patch that address that is available in:

 <https://bitbucket.org/iamleot/pkgsrc-localpatches/raw/c34f3c27681a61a7125e35e546dce8000222031e/net/youtube-dl/patch-youtube__dl_extractor_rai.py>

However, this will only fix `RaiPlay` extractor and a lot of other extractors needs to be updated too (and I would like to do that before sharing a possible PR).
Unfortunately I will probably not be able to fix in the next couple of hours but hopefully I can work on it this (UTC) evening or tomorrow!

**Comment by Mte90** [comment]
waiting for the fix and tests approved :-D

**Comment by thePanz** [comment]
I added a preliminary fix for that in https://github.com/ytdl-org/youtube-dl/pull/22843 (https://github.com/ytdl-org/youtube-dl/pull/22843/files#diff-71cf0b98e259190df337d3b1c33fc734R185)

**Comment by de666** [comment]
Avevo cercato una soluzione "veloce" e non mi sono preoccupato di 
testarla se non con qualche link preso al volo dal sito (e con quelli 
che ho usato funzionava).
Detto questo ho visto che la piattaforma sta cambiando e quindi molti 
contenuti "vecchi" (anche quelli su cui avevo fatto le prove) non sono 
disponibili (per ora?).
Non so se stanno migrando verso una nuova infrastruttura lato server e 
quindi stanno convertendo in qualche modo i vecchi contenuti alla nuova 
piattaforma.
Per questo motivo mi stavo chiedendo se vale la pena aspettare o meno 
che il passaggio venga completato (ammesso che siano effettivamente in 
fase di transizione).

Il 08/11/2019 09:41, Leonardo Taccari ha scritto:

**Comment by thePanz** [comment]
@de666 I agree, I also noticed that some contents disappeared, and others have a different video formats. The major changes I noticed are:
- URL for the json data
- new video formats
- availability of a higher resolution video format (1024x576@2523k)

As an example:
```
[info] Available formats for ce6de580-5253-4428-ac6f-4c3897c72536:
format code  extension  resolution note
hls-852      mp4        512x288     852k , avc1.77.30, mp4a.40.2
hls-1892     mp4        928x522    1892k , avc1.77.30, mp4a.40.2
hls-2523     mp4        1024x576   2523k , avc1.77.30, mp4a.40.2 (best)
```

**Comment by iamleot** [comment]
JFTR I have shared possible patches that should address all rai extractors and updated all corresponding tests in #23040.

If you find any problems please let me know!

**Comment by de666** [comment]
I close this one, please refer to #23040

**Pull request closed without merging**
