### PR TITLE
Updated support for ivi.ru

### PR DESCRIPTION
**Pull request by kritik**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Now extractor can work with new ivi.ru format of data. Supports cookies and gives better message if all files are DRM encrypted. Resolves issue as #23552

### CODE REVIEW

**Comment by dstftw** [comment]
1. This does not fix anything.
2. Do not touch fallback site scenario.

**Comment by kritik** [comment]
1. Which else situations I missed?
2. Which fallback did I remove?

**Comment by dstftw** [comment]
1. What doo you mean? This has no effect: DRM does videos does not work, same error is returned as before.
2. 183 site.

**Comment by kritik** [comment]
1. I would say that DRM is not part of this code if I understand youtude-dl code correctly. This plugin needs to return url with the video where to download url. I didn't this merge to make possible for people to download video if there's no DRM protection, so at least part of functionality could be used.
2. there's no such 183 site any more. At least it didn't exist in my network tab. This is why I have removed it.

**Comment by dstftw** [comment]
1. Do you read my posts at all? Again: this PR has no effect.
2. Again: 183 still works fine for all current tests. Do not touch it.

**Pull request closed without merging**
