### PR TITLE
[RT] Add new extractor

### PR DESCRIPTION
**Pull request by andrejsky**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Adds support for rt.com website (shows and articles) (issue https://github.com/rg3/youtube-dl/issues/17382)
RT uses several ways to embed videos and the extractor attempts to deal with them in this order:
- RT's own video CDN
- embeded videos from ora.tv
page contains ora.tv embedded url, which is retrieved to get full url to ora.tv, which is then passed to existing OraTVIE
- embeded videos from youtube
youtube url is passed to existing YoutubeIE

There are 3 tests that cover these cases.

### CODE REVIEW

**Comment by dstftw** [comment]
1. Read coding conventions and fix code appropriately.
2. See other extractors on how to delegate extraction to another extractors.

**Comment by jtrmal** [comment]
Would it be possible to include the dumping of subs for this?
For example, 
going to https://www.rt.com/on-air/rt-america-air/ I can see CC
but doing youtube-dl --list-subs  https://www.rt.com/on-air/rt-america-air/
```
[generic] rt-america-air: Requesting header
WARNING: Falling back on generic information extractor.
[generic] rt-america-air: Downloading webpage
[generic] rt-america-air: Extracting information
[generic] 1105: Downloading m3u8 information
1105 has no subtitles
```

**Comment by jtrmal** [comment]
If possible, I'd be happy to offer a small bounty($50) on dumping of the subs.

**Comment by remitamine** [comment]
@jtrmal there is no change to be done on the youtube-dl side, the subtitles for the URL you have posted are part of the downloaded video stream and can enabled on players like VLC, MPV...

**Comment by jtrmal** [comment]
thanks for clarification -- in that case, I'm clearly missing something
(both skills and knowledge probably)
because I just tested it out on vlc 3.06 (Subtitles/Subtitles track is
disabled) and I cannot display subtitles. Could you tell me, what I;m
missing? Am I supposed to use a different container than mp4?
Let me say I'm talking primarily about
https://www.rt.com/on-air/rt-america-air/ (I understand that I could
display the  subtitles from youtube hosted videos)
y.

**Comment by remitamine** [comment]
works fine on VLC 3.0.6, you have to enable subtitles manually(`Subtitle` Menu -> `Sub Track` -> `Closed captions 1`).

**Comment by jtrmal** [comment]
can you show me your command line please? I think I'm not doing something
right, as exactly that option is disabled.
y.

**Comment by remitamine** [comment]
`youtube-dl https://www.rt.com/on-air/rt-america-air/`
and then when you open the downloaded file with VLC and enable the subtitles(as explained in the preview comment), then the subtitles will be enabled shortly, it's not that difficult, if that did not work for you then I don't think that I can anymore, you might try to use another player, as I explained this is not a problem in youtube-dl.

**Comment by jtrmal** [comment]
Yes, you're right. I can download the stream and display the captions on
Windows. I still do have issues on mac, but that is my problem to deal with.
Thanks a lot for your patience and help.
Y.

**Pull request closed without merging**
