### PR TITLE
[senateisvp] improve extractor

### LINKED ISSUE #22754: US Commerce Senate Hearing not downloading
## Checklist

- [ x] I'm reporting a new site support request
- [ x] I've verified that I'm running youtube-dl version **2019.10.16**
- [ x] I've checked that all provided URLs are alive and playable in a browser
- [ x] I've checked that none of provided URLs violate any copyrights
- [ x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

https://www.commerce.senate.gov/2017/10/the-commercial-satellite-industry-what-s-up-and-what-s-on-the-horizon

## Description

US Senate Hearing uses Akamai Media Player with a "blob:Https...." javascript local file, not sure what to do, just lots of errors

### PR DESCRIPTION
**Pull request by LameLemon**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Bug fix
- [X] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
The previous state of the extractor got the .mp4 url for archived streams but since then they are no longer available. This was why changing the type to `xarch` [worked](https://github.com/ytdl-org/youtube-dl/issues/13399#issuecomment-309251280) for @johnhawkinson. This improvement extracts the m3u8 to get the mp4 download, which works. This fixes the issue discussed for single videos in #13399. 

This pull requests closes #22754 and uses the m3u8 url which it extracts from the webpage for all `https://www.[committee].senate.gov/` hearing links.

I have ran all the test cases for `SenateISVPIE` and `SenateGovISVPIE` which contains urls from both issues, and everything passed. If there are any changes or improvements that can be made please let me know.

### CODE REVIEW

**Comment by LameLemon** [comment]
Hello @dstftw 

It says 
```
AssertionError: SenateGovISVPIE should not match URL u'https://www.hsgac.senate.gov/hearings/canadas-fast-track-refugee-plan-unanswered-questions-and-implications-for-us-national-security' . That URL belongs to Generic.
```

I want this case to be handled in SenateGovISPIE, since with generic I get an error. To resolve this should I remove the static function from SenateISPIE? Not sure how this works, sorry for the trouble.

**Comment by LameLemon** [comment]
Changed `_search_iframe_url()` from `generic.py` and it is no longer a static method. So now the url will be handled within `SenateGoveISVPIE` and not generic. Would you like me to squash both commits?

**Comment by dstftw** [comment]
1. Don't touch the generic extractor in any form.
2. Don't add any new extractors.
3. Improve existing extractor to extract formats approriately.
4. Don't copypaste any code.

**Comment by LameLemon** [comment]
Hello @dstftw,

I took your advice and made changes to my origin commit. 

- The generic extractor is untouched 
- No new extractors were added
- The Existing extractor is improved and gets m3u8 and f4m or the archive url if the first two do not exist.
- No code was or has been copy pasted.

I have followed the same method for getting the stream as the senate.gov website themselves. The m3u8 and f4m stream is first fetched, if that returns a 404 the website then uses the arch stream. The extractor now functions in the same way. This closes #22754 and addresses the issue for single videos on #13399. 

Hope this satisfies the requirements.

**Comment by LameLemon** [comment]
I am having trouble understanding what's wrong on travis. Any help or guidance from other developers is appreciated.

**Comment by LameLemon** [comment]
Figured out the generic extractor already have some tests for SenateISVP, so I took out the ones I added into the extractor to prevent any conflict. All seems good now.

**Pull request closed without merging**
