### PR TITLE
[ifeng] Add new extractor

### PR DESCRIPTION
**Pull request by flysee**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Added a new extractor for http://v.ifeng.com, which is a popular website in China.
Thanks a lot!

### CODE REVIEW

**Comment by yan12125** [comment]
It would be better to extract ```videoinfo``` as a Python dictionary instead of to extract keys one by one.

**Comment by flysee** [comment]
Yeah,i refer to extractor/douyutv.py.
I will improve it later,thx!

**Comment by yan12125** [comment]
I might be unclear. I was referring the following codes as ```videoinfo```:
```
        var videoinfo = {
            "id":"11129877",
            "vid": "c0f1c812-5157-4baa-81e5-f7087cbd09da",
            "name": "能自我修复的玻璃，手机用上它再也不怕碎屏了！",
            "duration": "76",
            "url": "http://v.ifeng.com/video_11129877.shtml",
            "skey":"9CA5D6",
            "videoLargePoster": "http://p0.ifengimg.com/pmop/2018/0111/C52A04D2B265330273E2D3374C612D9C38AE0F57_size251_w448_h252.png",
            "playerName":"vFreePlayer",  
            "mUrl":"http://v.ifeng.com/dyn/m/video/11129877/index.shtml",
            "categoryId":"118-123",
            "mediaId":"345937",
            "adtype":"5",
            "categoryPath":"keji",
            "danmaku": "",
            "columnName":"SoFun搜趣坊",
            "CPId": "166",
            "keywords": "黑科技",
            "createdate": "2018-01-11 21:00:54",
            "preview": {"path":"http://p0.ifengimg.com/pmop/2018/01/11/91c0f75b-e41d-4bd9-bac5-045c29b1f0d8.jpg","sub_width":128,"time_span":1,"sub_height":72,"width":1280,"sub_picture_number":76,"picture_number":1,"height":720},
            "bqSrc": "",
            "aspect": "16:9",
            "gqSrc": "http://ips.ifeng.com/video19.ifeng.com/video09/2018/01/11/18356859-102-009-210214.mp4",
            "mediaName": "SoFun搜趣坊",
            "videoPlayUrl": "http://ips.ifeng.com/video19.ifeng.com/video09/2018/01/11/18356859-102-009-210214.mp4"
        };
```
This is a JavaScript object, and it can be transformed to a Python dictionary (say, ```video_info```), so the extractor can use its values easily (e.g., ```video_info.get('videoLargePoster')``` instead of a long regular expression)

**Comment by flysee** [comment]
Embarrassedly,my brain was short-circuited,lol!!!

**Pull request closed without merging**
