### PR TITLE
srgssr: download metadata and stream via HTTPS instead of HTTP

### PR DESCRIPTION
**Pull request by vszakats**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Downloading an SRF video was downloading two metadata resources via cleartext HTTP while these resources are also available via HTTPS. Upgraded the protocol for these hard-coded URLs.

### CODE REVIEW

**Comment by dstftw** [comment]
Do you even test before filing a PR?

**Comment by vszakats** [comment]
I was about to append [WIP].

**Comment by vszakats** [comment]
@dstftw Would you mind reopening?

**Comment by dstftw** [comment]
Note also that I won't accept any changes without clear evidence that it's an actual API in use. Current web version does not use these APIs any longer.

**Comment by vszakats** [comment]
Okay. Will you reopen this PR, so that I can continue with this here?

**Comment by vszakats** [comment]
I'll open another PR when ready, but please give me a few minutes chance to work on it (and to see an actual CI result) before closing that one. It won't possibly be perfect on the first commit on my first ever PR for `youtube-dl`.

**Pull request closed without merging**
