### PR TITLE
More string comparison operators for --match-filter

### PR DESCRIPTION
**Pull request by max-te**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This pull request allows to use string containment and regex match operators, introducing the operators `~=, !~=, *=` and `~*=`. Though regex support alone can handle all cases, the other additional operators may be more comfortable for users who are unfamiliar with regexes and also avoid having to escape certain characters. This PR adresses issues #23035 and #9092,

This PR also stops disallowing the use of `<=` and `>=` for strings. They are lexicographic comparison, this allows, e.g., to download videos in a playlist in alphabetic blocks A-F,G-K, etc. I don't have a specific use case for this, but it seems silly to disallow it when it requires no additional code.

### CODE REVIEW

**Review by dstftw — CHANGES_REQUESTED** [review]
1. Operators must match exactly with operators used in format selection.
2. Negation must be separate operator.
3. Everything must be covered by tests.

**Comment by max-te** [comment]
>     1. Operators must match exactly with operators used in format selection.
That is totally reasonable. I had failed to notice that format selection syntax already has a rich set of operators.
It doesn't have a regex-operator, though. What are your thoughts on that? Should we have one? If so, what should it be called? `*=` is taken for containment, would `~=` be fine?

I will take a look at how the operators for format selection are implemented and go from there.

**Comment by dstftw** [comment]
The operator alias is discussable and secondary, it may be `~`/`!~` like in awk, or `=~`/`!~` like in perl, or suggested `~=`/`!~=` variant. What is important is to design its behavior, whether it will be used only in quoted variant or not (in this case there is an ambiguity appears immediately since regex may contain arbitrary characters), whether it will allow using captured groups in following clauses and so on.

**Comment by max-te** [comment]
I was trying to make only minimal changes to the matching code in this PR. Maybe we should only do the `^=, *=, $=` operators as in format matching for this PR and have regexes as a second step. With the last commit I pushed, we have only the additional operators from format selection, and I added tests for each of them. Negation is now a separate operator.

Carrying over capture groups is interesting but not a standard feature of regexes and I don't believe it is supported by the `re` module.

A `/pattern/flags` syntax would require a bit of remodeling of `operator_rex` and the matching function in general. (I'm not sure which flags apart from `i` you'd realistically need, though.) The current quoting code handles escaped quotes, the only ambiguity comes from `&` characters, which already pose a problem for `=`, since the `match-filter` argument is split at all `&`s indiscriminantly.

**Pull request closed without merging**
