### PR TITLE
Viki login fix (Windows+Ubuntu) -> 1080p download is working again.

### PR DESCRIPTION
**Pull request by blackjack4494**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Windows 10 (pyinstaller) with python 3.6.5:
> youtube-dlv -F https://www.viki.com/videos/1042511v-doctor-stranger-episode-18 -u "USER" -p "SECRET" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.viki.com/videos/1042511v-doctor-stranger-episode-18', '-u', 'PRIVATE', '-p', 'PRIVATE', '--verbose']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[viki] Logging in
[viki] 1042511v: Downloading video JSON
[viki] 1042511v: Downloading video streams JSON
[info] Available formats for 1042511v:
format code  extension  resolution note
mpd-http     mpd        unknown
360p-https   mp4        360p
480p-https   mp4        480p
720p-https   mp4        720p
1080p-https  mp4        1080p      (best)

Ubuntu (Win10 WSL ~ make) with python 3.5.2:
> ./youtube-dl -F https://www.viki.com/videos/1042511v-doctor-stranger-episode-18 -u "USER" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-F', 'https://www.viki.com/videos/1042511v-doctor-stranger-episode-18', '-u', 'PRIVATE', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.07.28
[debug] Python version 3.7.8 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 2.8.17, ffprobe 2.8.17
[debug] Proxy map: {}
[viki] Logging in
[viki] 1042511v: Downloading video JSON
[viki] 1042511v: Downloading video streams JSON
[info] Available formats for 1042511v:
format code  extension  resolution note
mpd-http     mpd        unknown
360p-https   mp4        360p
480p-https   mp4        480p
720p-https   mp4        720p
1080p-https  mp4        1080p      (best)

What I noticed using -p and having a '!' in your password even when inside "" will do something else and the supplied password will be wrong then. But that's just a side note.

There were workaround using --add-header on command line. Those do work on Windows but apparently not on Ubuntu. 
I still don't know why there is a difference when using Windows 10 and Ubuntu. But I found the problem when using Ubuntu and could fix it. The Api for some reasons behave differently depending on OS. It can happen that even if you get a 400 or 404 on Ubuntu that it still contains a json with the wanted data. Under Windows it will simply return with 200. Don't ask me why it's 400 or 404 for Ubuntu, honestly no clue.

Some related issues/PR:
#25534, #26320, #26246, #25752, #25374, #25268, #25127, #25106

Let me know if everything works for you.

Also leave some upvote/attention for my other PR #26265 for soundcloud which no one bothered to merge/review :(

### CODE REVIEW

**Comment by llacb47** [comment]
image

no one wants your commit from two years ago...

**Comment by zackmark29** [comment]
@blackjack4494  could you also apply this to python? 
I just noticed when I download english subtitle it captured and download the first subtitle which is not sync to the video.
Here's my code for that fix so that It can find the right subtitle that synchronize with the video

`    public static async Task<string> GetSubtitle(string title, string id)
        {
            string final = string.Empty;
            string api = $"https://www.viki.com/player5_fragment/{title}.{id}??id={title}&autofocus=false";
            var result = await Task.Run(() => GetWebSource(api));
            var reg = new Regex(@"var parsedStreamSubtitles = ([\s\S]*:false}]})").Match(result).Groups[1].Value;
            JObject obj = JObject.Parse(reg);
            var r = getJson(obj, "dash", "src", "en.vtt");
            return obj.ToString();
        }
        private static string getJson(JObject obj, string main, string input, string contains)
        {
            return obj[main].Where(x => x.ToString().Contains(contains)).FirstOrDefault()?[input].ToString();
        }`

Here's the difference from the downloaded subtitle: from this link: https://www.viki.com/videos/91001v-dream-high-episode-1
from my code:

WEBVTT
1
00:00:00.824 --> 00:00:04.803
<i>Right now, fans are in attendance at the L.A. Staples Center</i>

from youtube-dl:
WEBVTT
1
00:00:07.034 --> 00:00:11.013
<i>Right now, fans are in attendance at the L.A. Staples Center</i>

**Comment by blackjack4494** [comment]
@zackmark29 that is odd. I had no problems on some other videos I tried. While inspecting this is what you will get when you use your browser
`https://api.viki.io/v4/videos/91001v/subtitles/de.vtt?stream_id=94944601&app=100000a&t=1597845542&sig=`
however this is the one generated by youtube-dl with wrong timestamps
`https://api.viki.io/v4/videos/91001v/subtitles/en.vtt?app=100005a&t=1597846838&site=www.viki.com&sig=`

there is a `stream_id` added to the query and the app is different. It's not that easy like copy&paste to add the `stream_id` when requesting subtitles since you have to generate a signature from the whole query. So simply adding it to the query without modifying the signature will give you an error with wrong signature. That all assumes the missing `stream_id` is indeed the missing piece. Or if the problem is the `app` or even both.

**Comment by zackmark29** [comment]
> @zackmark29 that is odd. I had no problems on some other videos I tried. While inspecting this is what you will get when you use your browser
> `https://api.viki.io/v4/videos/91001v/subtitles/de.vtt?stream_id=94944601&app=100000a&t=1597845542&sig=`
> however this is the one generated by youtube-dl with wrong timestamps
> `https://api.viki.io/v4/videos/91001v/subtitles/en.vtt?app=100005a&t=1597846838&site=www.viki.com&sig=`
> 
> there is a `stream_id` added to the query and the app is different. It's not that easy like copy&paste to add the `stream_id` when requesting subtitles since you have to generate a signature from the whole query. So simply adding it to the query without modifying the signature will give you an error with wrong signature. That all assumes the missing `stream_id` is indeed the missing piece. Or if the problem is the `app` or even both.
> 
> But the wrong timestamp in subtitles will be another/new issue. You could open one so that it can be referenced when opening a PR.

Thank you for the information. I think not all videos has the wrong timestamp if generated by youtube-dl. 
I'm gonna try later the API method for getting the subtitle. I'll see if I can grab also the correct subtitle for this url "https://www.viki.com/videos/91001v-dream-high-episode-1".

by the way, so it means the subtitle link is depends on the APP ID? I'll try later to use 100005

**Comment by lancesanch** [comment]
how can i download from viki?

**Comment by touchhyuk** [comment]
how can i download from viki?

**Comment by touchhyuk** [comment]
get this error
[viki] Logging in
ERROR: Unable to download JSON metadata: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by dirkf** [comment]
Superseded by b92bb0e02a09930cad3c4f6a406eb503c941af61.

**Pull request closed without merging**
