### PR TITLE
Truncate filenames that are too long

### PR DESCRIPTION
**Pull request by TheStranjer**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This fixes issues #7765 and #5908. I had a similar problem when I was trying to download a Twitter video and it tried to set the entire Tweet body as the filename. This does it in the common downloader, and if that doesn't give it _general_ applicability I'd love to hear how I can make it accomplish that.

### CODE REVIEW

**Comment by dstftw** [comment]
1. `statvfs` is not available on Windows.
2. `statvfs` is not available in python3.
3. This is incorrect since `.part` is optional.
4. This won't when filename includes arbitrary path.
5. This has no effect on anything apart from media files.

**Comment by TheStranjer** [comment]
Should I address these things and put in another PR or abandon this goal of truncating filenames that are too long (in particular, when they are generated by `youtube-dl`)?

**Comment by dstftw** [comment]
This may be problematic on some platforms but you can try. Note that this must be carefully tested on all platforms and work flawlessly in order to be accepted.

**Comment by TheStranjer** [comment]
I think I'll pass then purely on the basis that I hate booting into Windows. Enjoy the rest of your day.

**Comment by daniells** [comment]
This issue affects a large number of twitter videos as youtube-dl attempts to use the full tweet as the filename.  EXT4, NTFS, and HFS support only 255 characters per filename, but the current max-tweet is 280 characters.

**Pull request closed without merging**
