### PR TITLE
[lsm] add extractor for ltv.lsm.lv

### PR DESCRIPTION
**Pull request by skakri**
## Please follow the guide below
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _pull request_ (like that [x])
- Use _Preview_ tab to see how your _pull request_ will actually look like

---
### Before submitting a _pull request_ make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
### What is the purpose of your _pull request_?
- [ ] Bug fix
- [x] New extractor
- [ ] New feature

---
### Description of your _pull request_ and other information

This pull request adds LSM (Latvijas Sabiedriskie mediji) VOD extractor for archived videos from LTV (Latvijas Televīzija; http://ltv.lsm.lv).

### CODE REVIEW

**Comment by dstftw** [comment]
There are multiple formats available. All of them should be extracted.

**Comment by skakri** [comment]
Do you mean DASH from `manifest.mpd`? If yes – could you give some pointers on how to handle multiple formats?

**Comment by skakri** [comment]
Ping! @dstftw

**Comment by dstftw** [comment]
See any extractor with multiple formats, e.g. vessel.py.

**Pull request closed without merging**
