### PR TITLE
[rai] Fix extractor for recent raiplay.it updates

### PR DESCRIPTION
**Pull request by iamleot**
### Please follow the guide below
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
[rai] Fix extraction for recent raiplay.it updates

- Introduce _BASE_URL in RaiBaseIE class so it could be reused as base for the
  several subextractors.
- Remove first test of RaiPlayIE, it is no longer available
- Adjust RaiPlayIE to recent raiplay.it updates, make it extension agnostic
  (passing possible `.json' URLs is now supported too) and update test
  info_dict.
- Adjust RaiPlayLiveIE to recent raiplay.it updates.  Passing it as
  `url_transparent' is no longer supported (there is no longer an accessible
  ContentItem)
- Adjust RaiPlayPlaylistIE to recent raiplay.it updates and instruct it about
  ContentSet-s.

This fix issue #22923, #22906 and supersedes #23006.

### CODE REVIEW

**Comment by fturco** [comment]
I successfully applied this patch to youtube-dl on my Gentoo system to download some videos from raiplay.it. It works. Thanks!

**Comment by iamleot** [comment]
Whoops, sorry for the breakage and delay in reviewing the tests.

The tests failed because an `è' was present and I have just fixed it.

**Comment by mauro-r** [comment]
Ciao, the patch for the issue "ERROR: a144516f-47a3-4286-9432-1164c0dfee86: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); "  did not come with last update of nov 22 as believed.
Shall this be worked in next update?  
Thank you

**Comment by iamleot** [comment]
Hello mauro-r,

mauro-r writes:
> Ciao, the patch for the issue "ERROR: a144516f-47a3-4286-9432-1164c0dfee86: Failed to parse JSON  (caused by ValueError('Expecting value: line 1 column 1 (char 0)',)); "  did not come with last update of nov 22 as believed.
> Shall this be worked in next update?

I think it's just pending reviews and someone with commit
access to youtube-dl needs to apply it.

(At least after a week or so of using this patch I have not noticed
any problem.)

**Comment by mauro-r** [comment]
> Hello mauro-r,
> 
> mauro-r writes:
>  Shall this be worked in next update?
> I think it's just pending reviews and someone with commit
> access to youtube-dl needs to apply it.
> 
> (At least after a week or so of using this patch I have not noticed
> any problem.)

still no fix applied in last update :(

**Comment by sgerwk** [comment]
Works fine. Thanks!

**Comment by mauro-r** [comment]
??? it is *not* working; 28/11 update hasn't changed anything, still giving "Failed to parse JSON ….." answer.
I'm downloading RAIPLAY videos with Tampermonkey in Google Chrome efficiently working with friendly/easy GUI.  YouTube-dl is remaining steps behind….

**Comment by iamleot** [comment]
@mauro-r Yes, it was/is not applied at the moment but you can apply the patch in this PR and RaiPlay should then work.  If you notice any issue with `rai` extractor after applying this patch please let me know!

**Comment by mauro-r** [comment]
thank you, i'd like to apply the patch but can do it only by following beginners instruction, have no idea at all where to start from, but will put my effort to succeed. I have understood that it is a patch matter, unfortunately could not find a valid tutorial (step-by-step) for applying it

**Comment by Legrandin** [comment]
How to install `youtube-dl` (from master) with this patch included:

    git clone https://github.com/ytdl-org/youtube-dl
    cd youtube-dl
    git fetch origin pull/23040/head:rai-update
    git merge rai-update
    pip install --user .

**Comment by mauro-r** [comment]
thank you.
Downloaded and installed Git, then applied the command lines you reported using MINGW64 which was the command window automatically started at the end of the installation routine, 

I've then registered user/email as required by following the commands responses,  have installed both Python 3.7 and PIP as needed to go on
it was all right till the last command  (user created was mauro-r as I am in this forum)

$ pip install --mauro-r
bash: /c/Users/mauro/AppData/Local/Microsoft/WindowsApps/pip: Permission denied

how can I get permissions to execute the command by this bash ?

**Comment by mauro-r** [comment]
I'm reading that the issue of permissions 
bash: /c/Users/mauro/AppData/Local/Microsoft/WindowsApps/pip: Permission denied
should happen due to the Python app version provided by the Microsoft store, which is my case.
Can you please tell how to fix? I knew that instructions for patching from Windows could not be that short like I just had everything ready to go….

**Comment by fabio1962** [comment]
new versions continue but no RAIPLAY

**Pull request closed without merging**
