### PR TITLE
[medialaan] Fix clips downloading

### PR DESCRIPTION
**Pull request by kenavera**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Downloading of the small clips from `vtm.be` failed, due to a change in source code.
This can be seen by running the second test or by testing with for example `https://vtm.be/boxing-stars/laura-tesoro-voelt-plots-de-stress-voor-haar-eerste-kamp`
I do not know if this is the best solution, so I would appreciate comments to improve the code. 

I could not find the timestamp and created date in the new data.

### CODE REVIEW

**Comment by kenavera** [comment]
Thanks for the feedback. The code is now using the drupal settings and brought back all removed metadata fields.

**Comment by kenavera** [comment]
@dstftw Any update on if it is good or that I should fix some things. Thanks :)

**Comment by dstftw** [comment]
I've already pointed out what should be fixed.

**Comment by kenavera** [comment]
I fixed those things. And all mandatory fields are there. Only the diff above still shows it, because I changed the ordering. Should I fix that then?

**Comment by dstftw** [comment]
Not fixed or you did not push it. Bother to read all my comments.

**Comment by kenavera** [comment]
I brought back the mandatory data fields (in total there is id,url,title,thumbnail,timestamp,duration, upload_date) and I am using drupal settings. 
Don't know what I can do more.

Well, in that case I'll close this.
As I do not want to put more effort in this, when I feel like everything I do is wrong.

**Comment by dstftw** [comment]
I **did not ask** to bring anything back. I've clearly pointed out: **read coding conventions** from FAQ on mandatory fields and fix `url` and `title` extraction.

**Pull request closed without merging**
