### PR TITLE
CDA.PL extractor fix

### PR DESCRIPTION
**Pull request by dkja**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/), but may contains remade fragment cda decode idea.
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

CDA.PL changed format the URLs. It provides decode data to mp4 stream URL. 
I propose check code, couse I'm not python programmer and its fast fix ;) #24458 #25477 Rudloff/alltube#301

### CODE REVIEW

**Comment by dkja** [comment]
I forgot to add that I used js2py lib.

**Review by Akeeru — APPROVED** [review]

**Comment by kodxana** [comment]
Tested it on Pop_OS! 20.04 64bit and I can confirm it's working :)

**Comment by kodxana** [comment]
Can we get it merged?

**Comment by Akeeru** [comment]
Please add python lib **js2py** and then merge

**Comment by adamryczkowski** [comment]
Please, do. Besides the missing dependency, the code in the pull request works on Ubuntu 18.04.

**Comment by adamryczkowski** [comment]
@Akeeru Sorry for noob question: how does one add an external dependency to the youtube-dl?

**Comment by Akeeru** [comment]
> @Akeeru Sorry for noob question: how does one add an external dependency to the youtube-dl?

How to add **js2py**? you mean?

**Comment by kodxana** [comment]
On my fork I created requirements.txt file with dependencies

**Comment by Akeeru** [comment]
> On my fork I created requirements.txt file with dependencies

Try this https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py

edit **setup.py** add _js2py_ in package field in setup

**Comment by Akeeru** [comment]
> > On my fork I created requirements.txt file with dependencies
> 
> Try this https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py
> 
> edit **setup.py** add _js2py_ in package field in setup function

**Comment by kodxana** [comment]
I made it work by creating requirements.txt is that fine? @Akeeru https://travis-ci.org/github/kodxana/youtube-dl/builds/732984385

**Comment by Akeeru** [comment]
> I made it work by creating requirements.txt is that fine? @Akeeru https://travis-ci.org/github/kodxana/youtube-dl/builds/732984385

Maybe, but i don't know how much you need checked jobs for accept this modification

**Pull request closed without merging**
