### PR TITLE
[picta] Add new extractor

### PR DESCRIPTION
**Pull request by oleksis**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x ] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [ x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Add new extractor for site [Picta](https://www.picta.cu/) Cuban Audiovisual Content Platform

Example: 
`youtube-dl -v --no-check-certificate https://www.picta.cu/medias/818`

### CODE REVIEW

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by oleksis** [comment]
Fix KeyError when missing attributes in MPD #https://github.com/ytdl-org/youtube-dl/issues/20588

**Comment by oleksis** [comment]
@dstftw is possible check review this commit #https://github.com/ytdl-org/youtube-dl/pull/19094/commits/0fc37c4c896069d74a3ac0ef79db67c83f5276b8  
I need for my PictaExtractor pass checks in Travis CI
Thanks!

**Comment by dstftw** [comment]
Remove all unrelated changes from this PR.

**Comment by oleksis** [comment]
@dstftw Removed all unrelated changes from PictaExtractor ;)

**Comment by oleksis** [comment]
@dstftw @remitamine Update to API v2 Picta for PictaExtractor. You can do a review. I would appreciate your comments. Thank you!

**Comment by dstftw** [comment]
Not possible to test/check since picta.cu does not look to be reachable.

**Comment by oleksis** [comment]
@dstftw For us it is reachable from Cuba. I hope that one day it can be reached worldwide. Thanks and regards!

**Pull request closed without merging**
