### PR TITLE
Append sha1 hash of url to filename in Generic Extractor

### PR DESCRIPTION
**Pull request by mushifali**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Generic Extractor now appends sha1 hash of URL to filename to avoid filename collisions thus closing #23191.

### CODE REVIEW

**Comment by d3fault** [comment]
why is this "out-of-scope"? this pull lgtm (but then again I don't write python).

will #23191 ever be fixed? I've encountered real scenarios described in that bug report, it's not just theoretical.

**Comment by mushifali** [comment]
@d3fault I agree! It would be useful for some real scenarios that you encountered. But unfortunately, this pull was closed immediately with "out-of-scope" label.

**Comment by dstftw** [comment]
Id must be stable for identical URLs.

**Comment by d3fault** [comment]
@dstftw sha1 is stable... you put a single URL through it multiple times, you always get same result. am I missing something?

**Comment by dstftw** [comment]
>for identical URLs

**Comment by d3fault** [comment]
@dstftw sha1 is stable for identical URLs

**Comment by dstftw** [comment]
No, it's not. sha1 as well as any other hash is only stable for exactly same strings.

**Pull request closed without merging**
