### PR TITLE
[oxygen] Add new extractor

### PR DESCRIPTION
**Pull request by StevenDTX**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [X] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [X] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

New site request for Oxygen.

### CODE REVIEW

**Comment by dstftw** [comment]
No copy-pasting here.

**Comment by StevenDTX** [comment]
> 
> 
> No copy-pasting here.

Can you please provide a bit of explanation? The Bravo and Oxygen websites are identical, and with only slight modification, the Bravo extractor works for Oxygen.  

Thanks.

**Comment by dstftw** [comment]
Explanation on what? You are not allowed to copy paste code.

**Comment by wattsra** [comment]
I just tried to run this fork on a page on oxygen to no avail... Does it actually work? or did they change their site since sept?

**Pull request closed without merging**
