### PR TITLE
[vivo] use ROT47 instead of base64 to decode the stream url

### PR DESCRIPTION
**Pull request by waahhhh**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

vivo.sx doesn't encode the stream url with base64 anymore. ROT47 is used.
The test video is not available, so I updated the test, too.

### CODE REVIEW

**Comment by lucas1** [comment]
Work good, thanks

**Comment by OfficialCRUGG** [comment]
Is this ever going to get merged? I need vivo.sx downloading as quick as possible.

**Comment by Agent77326** [comment]
Can someone merge this or at least tag this as `pending-fixes`?

**Comment by byteholding** [comment]
please merge.

thanks!

**Comment by byteholding** [comment]
It has been changed again. Therefore please do not merge yet!

**Comment by waahhhh** [comment]
The js object structure has been changed. 
I'm not really proud of the current solution to expect, that the attribute "preroll" has to follow the attribute "source".
Maybe we could parse the js object by a module like https://stackoverflow.com/a/26900181.

But currently it works again.

**Comment by byteholding** [comment]
Wow amazing. thank you!

**Comment by byteholding** [comment]
Hey @waahhhh,

since a few minutes the vivo addon does not work again.
Could you please check again if you can find a solution?

**Comment by waahhhh** [comment]
Updated the regex again. Also solved the issue that the attributes of the object structure need a certain order.

**Comment by MrIcedTea** [comment]
ping!!!

**Pull request closed without merging**
