### PR TITLE
[vlive:playlist] Fix failing test

### PR DESCRIPTION
**Pull request by biwubo**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Noticed that the `VLivePlaylistIE` test was failing. Looks like the playlist used in the test no longer exists so I've replaced it with a valid one.

### CODE REVIEW

**Comment by dstftw** [comment]
You **must fix code** instead of hiding this bug behind working playlist URL.

**Comment by biwubo** [comment]
The playlist in the current test doesn't seem to exist anymore, I can't see any reference to a playlist in the HTML (including the embedded JavaScript). There is just a suggestions box on the page where the playlist would otherwise be displayed. I have attached images of both below to show the difference.

www vlive tv_video_22867_playlist_22912
www vlive tv_video_117956_playlist_117963

**Comment by dstftw** [comment]
It does not matter whether playlist exists or not. http://www.vlive.tv/video/22867/playlist/22912 opens a video in browser so the code must be fixed to be able to download from this URL.

**Comment by biwubo** [comment]
Fair enough, but I still think if we're only limited to one test it should be a valid playlist to actually test the playlist extractor, I can add logic to redirect to the regular extractor if a playlist cannot be found, though.

**Comment by dstftw** [comment]
We are not limited to one test.
Again: you can add another test for a valid playlist but you **must not** hide this bug by removing current test.

**Pull request closed without merging**
