### PR TITLE
[Minds] Add new extractor

### LINKED ISSUE #13220: Support for Minds.com
I would like to request [Minds.com](https://www.minds.com) support if you get the chance.

### PR DESCRIPTION
**Pull request by Tatsh**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

This adds support for Minds' [channel pages](https://www.minds.com/ottman), [single newsfeed pages](https://www.minds.com/newsfeed/900465343288483840), and [media pages which play a video](https://www.minds.com/media/334180407354331136). Fixes issue #13220.

This requires cookies to work even if not logged as the XSRF-TOKEN string must be used with all API calls. The `x-xsrf-token` header value used in API calls is taken from cookies. If you have your XSRF taken from the site, you can save it to a file like so:

```sh
printf '.minds.com\tTRUE\t/\tTRUE\t15624050615\tXSRF-TOKEN\t< TOKEN VALUE HERE >\n' >> ~/.ytdl-minds-cookies
```

Then use cookies:

```sh
youtube-dl --cookies ~/.ytdl-minds-cookies 'https://www.minds.com/ottman'
```

This closes #13220

### CODE REVIEW

**Comment by Tatsh** [comment]
@dstftw Please review again since the last commit.

**Comment by rudolphos** [comment]
Are there any updates to this? 

using latest version

> ERROR: Unsupported URL: https://www.minds.com/newsfeed/..

**Comment by Tatsh** [comment]
The general newsfeed is not supported in this PR but that would not be too hard to support. Only `/newsfeed/<some ID here>` newsfeed URLs are supported.

**Comment by Tatsh** [comment]
Bump

**Comment by Tatsh** [comment]
@dstftw If you want me to make changes, I'll need to re-make this PR. I asked GitHub and they cannot fix branch references.

**Pull request merged**
