### PR TITLE
Cloudflare can use videodelivery.net subdomains

### PR DESCRIPTION
**Pull request by davex25**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Was attempting to youtube-dl a video from a videodelivery.net stream, which did not work.  After a little research, discovered that it appears to be hosted by Cloudflare, and with a modification of the InfoExtractor regexes it appears to work.

### CODE REVIEW

**Comment by davex25** [comment]
Looks like a test is failing.  Will try to fix and resubmit.

**Comment by davex25** [comment]
When I ran the tests locally (nosetests --verbose test), I came back an hour later to find the tests still hadn't completed.  Is there a way to run just fast tests, or maybe just the extractor tests?

**Comment by dstftw** [comment]
Run only single test that fails.

**Comment by davex25** [comment]
I was able to figure out the quick test mode from travis output above.

`export YTDL_TEST_SET=core`
`./devscripts/run_tests.sh`

Fixed the test, can make a new PR.

**Pull request closed without merging**
