### PR TITLE
[youtube] Fix automatic captions not found

### PR DESCRIPTION
**Pull request by RogerRordo**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Related to #27315 

The structure of `ytplayer.config` has changed, and it can no longer be explicitly obtained from the webpage. So the function `_get_ytplayer_config` used for getting automatic captions is no longer valid. 

In the latest format of youtube webpage, the url of auto-captions is explicitly stored in `ytInitialPlayerResponse`, which is exactly the parameter `player_response` we pass in the edited function `_get_automatic_captions`. And the original code can handle such structures.

You can check with:
```
youtube-dl --write-auto-sub --skip-download https://www.youtube.com/watch?v=3lMUIUgRD-A
```

### CODE REVIEW

**Comment by denizveizov** [comment]
Hi, RogerRordo,

How to I edit the youtube_dl/extractor/youtube.py file, I have installed the youtube-dl with .exe file and cannot locate the youtube_dl/extractor/youtube.py?

Thanks in advance

**Comment by RogerRordo** [comment]
> Hi, RogerRordo,
> 
> How to I edit the youtube_dl/extractor/youtube.py file, I have installed the youtube-dl with .exe file and cannot locate the youtube_dl/extractor/youtube.py?
> 
> Thanks in advance

Use pip rather than executable file

**Comment by iNoSec2** [comment]
i hope they will merge this ASAP, thanks a lot for contrib!!!

**Comment by zxl777** [comment]
The bug is still there.  -  Couldn't find automatic captions

```
youtube-dl --write-auto-sub --sub-lang en --skip-download "https://www.youtube.com/watch?v=GWGbOjlJDkU"
[youtube] GWGbOjlJDkU: Downloading webpage
[youtube] GWGbOjlJDkU: Looking for automatic captions
WARNING: Couldn't find automatic captions for GWGbOjlJDkU
```
image

**Pull request closed without merging**
