### PR TITLE
[Funimation] Update url pattern to include language code

### LINKED ISSUE #28879: Funimation fails to parse JSON
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.04.26**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.funimation.com/shows/talentless-nana/healing/']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.26
[debug] Python version 3.9.4 (CPython) - Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
[debug] exe versions: ffmpeg 4.2.4, ffprobe 4.2.4, rtmpdump 2.4
[debug] Proxy map: {}
[Funimation] healing: Downloading webpage
WARNING: [Funimation] healing: Failed to parse JSON Expecting value: line 1 column 1 (char 0)
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/funimation.py", line 96, in _real_extract
    player_url = self._html_search_meta([
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1140, in _html_search_meta
    return self._html_search_regex(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/home/linuxbrew/.linuxbrew/opt/python@3.9/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Funimation extractor fails to parse JSON.

### PR DESCRIPTION
**Pull request by Mevious**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Funimation recently made an update to include the two-letter language code in all urls. This updates the url matching pattern to include these language codes. This fixes #28879 which was closed as a duplicate, but I can't find what it is a duplicate of.

### CODE REVIEW

**Comment by chrisfu** [comment]
I've just tested this PR against master in conjunction with https://github.com/ytdl-org/youtube-dl/pull/28951, and now the Funimation extractor works flawlessly first time for the first time in 2021.

Good job @Mevious.

**Comment by dstftw** [comment]
This will break URLs without the lang code.

**Comment by Mevious** [comment]
URLs without the language code currently **do not work**. They seem to be in the process of deprecating them. The pages still exist but they do not contain the information that the extractor is looking for. Here's an example:
```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'--skip-download', u'https://www.funimation.com/shows/hacksign/role-play/']
[debug] Encodings: locale cp1252, fs mbcs, out UTF-8, pref cp1252
[debug] youtube-dl version 2021.04.26
[debug] Python version 2.7.17 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg git-2020-04-17-889ad93, ffprobe git-2020-04-17-889ad93
[debug] Proxy map: {}
[Funimation] role-play: Downloading webpage
WARNING: [Funimation] role-play: Failed to parse JSON No JSON object could be decoded
ERROR: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\extractor\funimation.py", line 101, in _real_extract
    ], webpage, fatal=True)
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\extractor\common.py", line 1142, in _html_search_meta
    html, display_name, fatal=fatal, group='content', **kwargs)
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\extractor\common.py", line 1021, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "C:\Users\Nasir\source\repos\youtube-dl-1\youtube_dl\extractor\common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract al:web:url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Process finished with exit code 1
```

I don't see a good reason to try to rewrite the extractor to fix these old pages which seem to be going away. Another option is to accept both with and without the language code in the URL. If the language code is not present then use a default like `en`. Would that be more acceptable?

**Comment by dstftw** [comment]
URLs without lang code work **perfectly fine**.

**Comment by True-King** [comment]
> URLs without lang code work **perfectly fine**.

Wait is Funimation working with YTDL now? if so whats the process

**Comment by Mevious** [comment]
@True-King Dstftw checked in a fix [here](https://github.com/ytdl-org/youtube-dl/commit/04be55307a3a13f7091a9a2970a1cc20863769e3). Does it work for you?

**Comment by True-King** [comment]
> @True-King Dstftw checked in a fix [here](https://github.com/ytdl-org/youtube-dl/commit/04be55307a3a13f7091a9a2970a1cc20863769e3). Does it work for you?

Hi checked but it doesn't work for me, but question? I have the ytdl.exe do I have to add the funimation.py to the same folder?

**Comment by Mevious** [comment]
> Hi checked but it doesn't work for me, but question? I have the ytdl.exe do I have to add the funimation.py to the same folder?

If you want to use the exe, then you'll need to wait for the next release and download it. The most recent one is from April 26th, so it won't include the fix. I'm not sure how often it gets an update. https://ytdl-org.github.io/youtube-dl/download.html

Alternatively, you can download the full source code [here](https://github.com/ytdl-org/youtube-dl) and use python to run it directly.

**Comment by True-King** [comment]
> > Hi checked but it doesn't work for me, but question? I have the ytdl.exe do I have to add the funimation.py to the same folder?
> 
> 
> 
> If you want to use the exe, then you'll need to wait for the next release and download it. The most recent one is from April 26th, so it won't include the fix. I'm not sure how often it gets an update. https://ytdl-org.github.io/youtube-dl/download.html
> 
> 
> 
> Alternatively, you can download the full source code [here](https://github.com/ytdl-org/youtube-dl) today and use python to run it directly.
> 
> 

Ohh nice I am familiar with Python quite a bit so I couldn't understand why the exe wasn't working lol. Thanks again

**Comment by acp21** [comment]
> @True-King Dstftw checked in a fix [here](https://github.com/ytdl-org/youtube-dl/commit/04be55307a3a13f7091a9a2970a1cc20863769e3). Does it work for you?

@Mevious Sorry if I'm missing something really obvious, but I cloned the master branch with git and ran __main__.py and still received the same error in your above post. I double checked funimation.py, ensuring that it had the changes in that PR. is there anything else that I am missing because I really don't understand what is causing this.

**Comment by True-King** [comment]
> > @True-King Dstftw checked in a fix [here](https://github.com/ytdl-org/youtube-dl/commit/04be55307a3a13f7091a9a2970a1cc20863769e3). Does it work for you?
> 
> 
> 
> @Mevious Sorry if I'm missing something really obvious, but I cloned the master branch with git and ran __main__.py and still received the same error in your above post. I double checked funimation.py, ensuring that it had the changes in that PR. is there anything else that I am missing because I really don't understand what is causing this.

Having same issue

**Comment by Mevious** [comment]
> @Mevious Sorry if I'm missing something really obvious, but I cloned the master branch with git and ran **main**.py and still received the same error in your above post. I double checked funimation.py, ensuring that it had the changes in that PR. is there anything else that I am missing because I really don't understand what is causing this.

I was never able to get it working without the language code in the URL. If you're trying with a URL like this
`https://www.funimation.com/shows/hacksign/role-play/`,
then you may need to manually add a language code such as `en` after the `.com` like this
`https://www.funimation.com/en/shows/hacksign/role-play/`.

**Pull request closed without merging**
