### PR TITLE
[adobepass] Directvnow auth fix

### PR DESCRIPTION
**Pull request by speakerender**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Update adobepass authentication for Directv Now.  Fixes issue #20213

### CODE REVIEW

**Comment by speakerender** [comment]
For a tv-provider account, sign up at: https://www.directvnow.com/ Free Trail available for 7 days.
From FAQ:
How does the free trial work?
    
If you’re a new customer, its simple – if you purchase the PLUS, MAX, or International packages, you’ll get 7 free days to stream as much DIRECTV NOW as you can handle!

**Comment by dstftw** [comment]
Free trial requires sharing CC that obviously nobody will do. Providing credentials is your responsibility.

**Comment by speakerender** [comment]
My credentials would include access to my CC.  I will not be able to provide credentials.

**Comment by speakerender** [comment]
re-open, perhaps another reviewer had directv now credentials and can review request

**Comment by darkhelmet2016** [comment]
The service is now called AT&T TV NOW.

**Pull request closed without merging**
