### PR TITLE
[youtube] Fixed 'next_link' regular expression

### PR DESCRIPTION
**Pull request by RedpointsBots**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The current regular expression used to find the next page link of the search results does not work. As a result, no link is found and there is an unintentional limit to the first page of search results (20 results. If a search is made for with a specified limit of 50, youtube-dl will not find a link to the next page and report that only 20 results were found (even if there were more on any potential next pages).
This PR updates the regular expression in question. Rather than removing the offending part of the regex, I have simply made it optional for backwards compatibility or in case the next page link is changed back.

### CODE REVIEW

**Comment by RedpointsBots** [comment]
This is the associated issue: https://github.com/ytdl-org/youtube-dl/issues/26161

**Comment by donat-b** [comment]
This patch doesn't seem to work unfortunately

**Comment by RedpointsBots** [comment]
> This patch doesn't seem to work unfortunately

Can you give more information about what isn't working for you? This change is still fixes pagination for me.

**Comment by dstftw** [comment]
No longer actual.

**Pull request closed without merging**
