### PR TITLE
[gotostage] Add GoToStage extractor

### PR DESCRIPTION
**Pull request by poschi3**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

GoToStage is platform for recordings of Webinars. I added an extractor to download a video.

There is a [page for all videos](https://www.gotostage.com/). I used a [specific video](https://www.gotostage.com/channel/8901680603948959494/recording/60bb55548d434f21b9ce4f0e225c4895/watch) for testing.

### CODE REVIEW

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by poschi3** [comment]
@dstftw Sorry, I misunderstood some things. I fixed it and hope you are more satisfied now.

**Comment by jbman11** [comment]
Will this one be committed?

**Comment by poschi3** [comment]
@jbman11 This extractor is now merged into yt-dlp. See https://github.com/yt-dlp/yt-dlp/pull/883

**Pull request closed without merging**
