### PR TITLE
[la7] Fix extraction (problematic parsing as JSON of videoParams/videoLa7)

### LINKED ISSUE #23323: La7 italian television support does not work anymore
downloading videos from thsi source sued to work and now no more. I'm using an updated version of the software.
Italian television site with many videos: https://www.la7.it/tagada/rivedila7/

Output diagnistic:

./youtube-dl  --verbose https://www.la7.it/tagada/rivedila7/tagada-05-12-2019-297031
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.la7.it/tagada/rivedila7/tagada-05-12-2019-297031']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.11.28
[debug] Python version 2.7.15+ (CPython) - Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.6, ffprobe 3.4.6, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[la7.it] tagada-05-12-2019-297031: Downloading webpage
ERROR: tagada-05-12-2019-297031: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/extractor/common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube_dl/extractor/la7.py", line 55, in _real_extract
    video_id, transform_source=js_to_json)
  File "./youtube-dl/youtube_dl/extractor/common.py", line 903, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: tagada-05-12-2019-297031: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### PR DESCRIPTION
**Pull request by iamleot**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

Parsing `videoParams` or `videoLa7` JavaScript snippets as JSON is getting too
for `js_to_json`.  Just extract the `vid` from there and use `_search_og_*` for all
other data.

Update 2nd test with an existent video.

Closes #23323.

### CODE REVIEW

**Comment by EliaGeretto** [comment]
When running `python3 test/test_download.py TestDownload.test_LA7`, the first test case fails. Just removing the double space in "gesto  atletico" fixes it. The page was probably updated on the website.

When running `python3 test/test_download.py TestDownload.test_LA7_1`, the second test case also fails. The updated test case was probably correct, but the video has been removed already, they are being rotated out pretty quickly probably.

Apart from the test case issues, I manually tested the code and everything works as it should.

**Comment by iamleot** [comment]
Thank you very much Elia for pointing out these problems and suggested these improvements!

I have just applied all your suggestions and updated the patch.

**Comment by angystardust** [comment]
@iamleot Your patch works great! Thank you so much!
Hope it will merged soon

**Review by nixxo — APPROVED** [review]
works as expected fixing the broken json parser

**Pull request closed without merging**
