### PR TITLE
[VK] Fix downloading user playlist

### LINKED ISSUE #14327: [vk] VK playlist is limited to 30 items
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.09.24*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.09.24**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

```
 $ youtube-dl -u <my_login_here> -p <my_pass_here> -v https://vk.com/videos-120371361?section=album_2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-u', u'PRIVATE', u'-p', u'PRIVATE', u'-v', u'https://vk.com/videos-120371361?section=album_2']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2017.09.24
[debug] Python version 2.7.12 - Linux-4.10.0-35-generic-x86_64-with-LinuxMint-18.2-sonya
[debug] exe versions: ffmpeg 2.8.11-0ubuntu0.16.04.1, ffprobe 2.8.11-0ubuntu0.16.04.1
[debug] Proxy map: {}
[vk:uservideos] Downloading login page
[vk:uservideos] Logging in as <my_login_here>
[vk:uservideos] -120371361: Downloading webpage
[download] Downloading playlist: -120371361
[vk:uservideos] playlist -120371361: Collected 30 video ids (downloading 30 of them)
[download] Downloading video 1 of 30
[vk] Downloading login page
[vk] Logging in as <my_login_here>
[vk] -90239289_171316586: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://cs634301.vkuservideo.net/u2518483/videos/24ce9d13ba.720.mp4?extra=03rGKiObHEwJl-zlNryI10HMUcXzeIAxJIYV43J6jjihDVteuMO05J35fNUhiOA6xK5flIwOa4FLRN5Yppy9KZ3V-EH_BWJuipvN7x_eH_rRlhhjUzthn7FEdNOz3QYsjMYabyZbM5c'
[download] Обложка SK-171316586.mp4 has already been downloaded
[download] 100% of 1.39MiB
[download] Downloading video 2 of 30
[vk] -90239289_171316992: Downloading webpage
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on u'https://cs542509.vkuservideo.net/u2518483/videos/aa8c53dc11.480.mp4?extra=ZemS4e9cWMdzDTOAZelNCNqRQ9gr7B9TbY0AzOwG-8NYFPUln0IC96Of9kmNXFQ8SOnPvYhjHTLBzr2nKygAgAc9rPYkY2Lu59vSb0fOZBex4MDiEmgTkGYLMKyUWGXVgfxa3OZ1Mh8'
[download] Resuming download at byte 3649196
[download] Destination: Shaman King 01 A Boy Who Dances with Ghosts rus sub-171316992.mp4
[download]   6.7% of 141.79MiB at  1.39MiB/s ETA 01:34^C
ERROR: Interrupted by user
```

---

### Description of your *issue*, suggested solution and other information

VK playlist is limited to 30 items though there are much more videos there (65 in my example).
It seems like when you open vk album (playlist) in the browser it loads only 30 items. And you should scroll down to load more via AJAX. But youtube-dl does not load more, it does not know there is more. I think this should be fixed.
TY!

### PR DESCRIPTION
**Pull request by pawitp**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Scraping HTML will only get 30 last videos. Use the JSON API to get up to 1000 videos.

The test album is from my account and I don't plan to add any more videos to it, so it
should be OK to use `playlist_count` for testing.

Fixes #14327

### CODE REVIEW

**Comment by mpenkov** [comment]
It looks like some of the VK-specific tests are failing:

```
test_VK_10 (test.test_download.TestDownload): ... FAIL
test_VK_7 (test.test_download.TestDownload): ... FAIL
test_VK_9 (test.test_download.TestDownload): ... ok
test_VH1_1 (test.test_download.TestDownload): ... ok
test_VK_8 (test.test_download.TestDownload): ... FAIL
```

Could you please fix the failures?

There are many non-VK tests that are failing as well, although I'm not sure if they are related to your changes.

**Comment by pawitp** [comment]
I've rebased this onto master.

Comparing my PR (https://travis-ci.org/rg3/youtube-dl/jobs/420406860) against master (https://travis-ci.org/rg3/youtube-dl/jobs/420191672), there were no new VK-specific tests that failed.

 - test_VKUserVideos has been fixed (and expanded)
 - test_VK_8 is an existing failure due to broken (?) dailymotion extraction (it's marked as TODO in the code)
 - test_VK_10 is an existing failure due to failed view count extraction

**Comment by soxox** [comment]
@remitamine I'm curious why this pull request was closed, and if there are other plans to solve the problems that are fixed in this branch.

**Comment by remitamine** [comment]
> I'm curious why this pull request was closed

this PR is not up to date with the changes in 3c989818e7dc7706da069312bbdd040165a97517.
> and if there are other plans to solve the problems that are fixed in this branch.

if something does not work for you with 0e6ec3caf6c20bb5b27c063b2b946686e0b5159f, than you can post an example of the URLs that are not covered with this fix.

**Pull request closed without merging**
