### PR TITLE
[Youtube] Support 256kbps aac audio in youtube music

### PR DESCRIPTION
**Pull request by craftingmod**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

screenshot

If provided url is youtube music, It will try get_video_info GET request with youtube music player parameter.

With cookie auth, Youtube premium member could download 256kbps aac audio in some supported music video. (Example: [Megalovania](https://music.youtube.com/watch?v=0FCvzsVlXpQ))

bitrate

### CODE REVIEW

**Comment by dstftw** [comment]
You must provide premium account.

**Comment by craftingmod** [comment]
Sadly youtube wouldn't allow to download 256kbps aac without premium subscription. But current youtube-dl couldn't download 256kbps aac even if I have provided yt premium account cookie. It fixes that.

**Comment by michealespinola** [comment]
> You must provide premium account.

If it helps anyone, YouTube is currently offering a free month trial of Premium.  I upgraded my account about a week ago, but I believe they are still offering the trial.  No payment required until the first renewal date of 30 days.

**Comment by Shulyaka** [comment]
Hi!

If the free trial is not an option, I am willing to provide a donation to any of the core developers to cover premium subscription for a couple of months, if that would help with:
1. Downloading best quality audio from YouTube music
2. Search on YouTube music (like :ytsearch but on music.youtube.com). Note that it gives different results than searching on youtube.
3. Ensure logging in with netrc or --username works for YouTube music. Cookies are good, but they tend to expire.

**Comment by celloh123** [comment]
I can give my account info.

**Comment by FolkSong** [comment]
I tried manually making these changes to youtube.py in the master and running it. It still works but I noticed an issue - it doesn't work on playlists, only individual videos. 

For instance I can run it on the Megalovania track linked in the OP and format 141 is there. But if I run it on [this playlist](https://music.youtube.com/watch?v=0FCvzsVlXpQ&list=RDAMVM0FCvzsVlXpQ) with Megalovania at the top, there is no format 141.

**Comment by sumit0x0d** [comment]
> I tried manually making these changes to youtube.py in the latest master and running it. It still works but I noticed an issue - it doesn't work on playlists, only individual videos.
> 
> For instance I can run it on the Megalovania track linked in the OP and format 141 is there. But if I run it on [this playlist](https://music.youtube.com/watch?v=0FCvzsVlXpQ&list=RDAMVM0FCvzsVlXpQ) with Megalovania at the top, there is no format 141.
> 
> Update: Looks like the issue is with line 1781 of the original commit. If I just set 'is_music' to 1 instead of doing the regex, it works on playlists. Something's going wrong with that regex test.
> 
> Update2: This is also breaking tags for the output file such as "%(artist)s", "%(album)s" etc which work in the master. They all evaluate to "NA" after making the change.

Is this wroking now? it still dont show me 141 format option.

**Comment by Silun** [comment]
It supposedly works but the maintainers aren't adding it in.

**Comment by rautamiekka** [comment]
> > You must provide premium account.
> 
> If it helps anyone, YouTube is currently offering a free month trial of Premium. I upgraded my account about a week ago, but I believe they are still offering the trial. No payment required until the first renewal date of 30 days.

Plus, surely you can deactivate/cancel the auto-renewal right after taking up the trial, so you won't have to do it right before the auto-renewal proceeds.

**Comment by AndreasWidmer** [comment]
Is there any news on this? I would be really grateful for this option!

**Comment by sumit0x0d** [comment]
> Is there any news on this? I would be really grateful for this option!

apply this commit to release of december 2020. and do https://github.com/ytdl-org/youtube-dl/pull/26160#issuecomment-753561345.
./youtube_dl/__main__.py --cookies cookies.txt -F https://music.youtube.com/watch\?v\={video_id}
you can see format 141

**Comment by craftingmod** [comment]
Please refer #28778 for future update because my pull request branch is taken down :(

**Pull request closed without merging**
