### PR TITLE
[vk] Use inline video page to extract info.

### PR DESCRIPTION
**Pull request by kasper93**
### Before submitting a _pull request_ make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)
### What is the purpose of your _pull request_?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---
### Description of your _pull request_ and other information

By requesting "show_inline" we can extract information for more videos which would be not available in normal video page. This is common when video is available only on user timeline.

Also some mirror changes in tests so that they all pass. (can be split into two commits if needed)

### CODE REVIEW

**Comment by dstftw** [comment]
Do not mix unrelated changes in single PR.

**Comment by dstftw** [comment]
Another side effect is that this approach reports wrong error messages for some videos.
Dropping `upload_date` is not acceptable.
The correct solutions would be to request show API when login data is provided and to request both otherwise.

**Comment by kasper93** [comment]
Ok, so I fixed date and view count extraction and make use of inline page only if "need login" error is encountered. This works fine for all my test cases. What do you think?

**Comment by kasper93** [comment]
bump

**Pull request closed without merging**
