### PR TITLE
[Youtube] Support Shorts URL format

### LINKED ISSUE #30269: youtube shorts URL causes "unable to recognize tab page" error
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
PS C:\Users\minec\PycharmProjects\captionbot> youtube-dl -v https://youtube.com/shorts/4L2J27mJ3Dc
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtube.com/shorts/4L2J27mJ3Dc']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.22504-SP0
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag
 and include its complete output.
Traceback (most recent call last):
  File "c:\users\minec\.virtualenvs\captionbot-ffal0v-r\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "c:\users\minec\.virtualenvs\captionbot-ffal0v-r\lib\site-packages\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "c:\users\minec\.virtualenvs\captionbot-ffal0v-r\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "c:\users\minec\.virtualenvs\captionbot-ffal0v-r\lib\site-packages\youtube_dl\extractor\youtube.py", line 2844, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-
dl with the --verbose flag and include its complete output.

```

## Description

the "share" button on youtube shorts can generate a URL in the following format: `https://youtube.com/shorts/[videoid]?feature=share`. this causes the above error. reformatting the URL to the typical `https://youtube.com/watch?v=[videoid]` works fine.

### LINKED ISSUE #30328: Unable to download YouTube Shorts
~ $ youtube-dl -v https://youtube.com/shorts/fK1VmX9mzRw?feature=share

[debug] System config: []
[debug] User config: ['--format', 'bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best', '--merge-output-format', 'mp4', '-o', '/data/data/com.termux/files/home/storage/dcim/Camera/%(extractor_key)s-%(uploader)s-%(title)s-%(id)s.%(ext)s', '--no-mtime']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://youtube.com/shorts/fK1VmX9mzRw?feature=share']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.1 (CPython) - Linux-4.14.190-22338387-abN975USQS7FUI6-aarch64-with-libc
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/youtube_dl/extractor/youtube.py", line 2844, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### LINKED ISSUE #30525: Can't recognize youtube short url
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [ ] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://youtube.com/shorts/o9I6hYxwmzM?feature=share

## Description

WRITE DESCRIPTION HERE

### LINKED ISSUE #30550: Unable to recognise tab page
## Checklist

- [x ] I'm reporting a broken site support
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--verbose', u'https://www.youtube.com/shorts/QsqsT3659Ss']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 2.7.14 (CPython) - Linux-4.12.14-lp150.12.25-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg N-97612-g2b32068, ffprobe N-97612-g2b32068
[debug] Proxy map: {}
[youtube:tab] shorts: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 2862, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

youtube-dl fails to download a Youtube video that plays fine in Firefox

### PR DESCRIPTION
**Pull request by dirkf**
## Please follow the guide below
---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Simple extension of  `YoutubeIE._VALID_URL` to cover new Shorts format `https://youtube.com/shorts/{id}`.

Resolves #30269
Resolves #30328
Resolves #30525
Resolves #30550

### CODE REVIEW

**Comment by AtomicNess123** [comment]
Is this fixed? Not in the latest version.

**Comment by dirkf** [comment]
Not in the release version, because it pre-dates the fix. Just remove the .../shorts/ part of the YT URL to leave the YT ID, which is understood by yt-dl without the https://... 

Better, install the git master https://github.com/ytdl-org/youtube-dl/issues/31032#issuecomment-1158490846.

**Comment by AtomicNess123** [comment]
When is it next release coming out?

**Comment by Rudxain** [comment]
> remove the .../shorts/ part

I converted to a shortened YT URL (youtu.be), but that alt is so much easier! I didn't know that was possible

**Comment by hasnogaems** [comment]
> > remove the .../shorts/ part
> 
> I converted it to a shortened YT URL (youtu.be), but that alt is so much easier! I didn't know that was possible

So what command should look like? This video for example https://www.youtube.com/shorts/mGUYnN0QFIY

**Comment by Rudxain** [comment]
> getting not found error.

That's weird, `youtube-dl mGUYnN0QFIY` should've worked

**Comment by dirkf** [comment]
```shell
$ youtube-dl -v -F mGUYnN0QFIY
[debug] System config: ['--prefer-ffmpeg']
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '-F', 'mGUYnN0QFIY']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.5.2 (CPython) - Linux-4.4.0-210-generic-i686-with-Ubuntu-16.04-xenial
[debug] exe versions: avconv 4.3, avprobe 4.3, ffmpeg 4.3, ffprobe 4.3
[debug] Proxy map: {}
[youtube] mGUYnN0QFIY: Downloading webpage
[info] Available formats for mGUYnN0QFIY:
format code  extension  resolution note
249          webm       audio only tiny   49k , webm_dash container, opus @ 49k (48000Hz), 236.87KiB
250          webm       audio only tiny   66k , webm_dash container, opus @ 66k (48000Hz), 318.24KiB
251          webm       audio only tiny  121k , webm_dash container, opus @121k (48000Hz), 585.72KiB
140          m4a        audio only tiny  129k , m4a_dash container, mp4a.40.2@129k (44100Hz), 623.05KiB
160          mp4        144x256    144p   57k , mp4_dash container, avc1.4d400c@  57k, 30fps, video only, 277.76KiB
394          mp4        144x256    144p   69k , mp4_dash container, av01.0.00M.08@  69k, 30fps, video only, 333.83KiB
278          webm       144x256    144p   78k , webm_dash container, vp9@  78k, 30fps, video only, 376.42KiB
133          mp4        240x426    240p   92k , mp4_dash container, avc1.4d4015@  92k, 30fps, video only, 445.63KiB
395          mp4        240x426    240p  103k , mp4_dash container, av01.0.00M.08@ 103k, 30fps, video only, 496.63KiB
242          webm       240x426    240p  135k , webm_dash container, vp9@ 135k, 30fps, video only, 649.22KiB
134          mp4        360x640    360p  170k , mp4_dash container, avc1.4d401e@ 170k, 30fps, video only, 819.62KiB
396          mp4        360x640    360p  221k , mp4_dash container, av01.0.01M.08@ 221k, 30fps, video only, 1.04MiB
243          webm       360x640    360p  233k , webm_dash container, vp9@ 233k, 30fps, video only, 1.09MiB
135          mp4        480x854    480p  259k , mp4_dash container, avc1.4d401f@ 259k, 30fps, video only, 1.21MiB
244          webm       480x854    480p  322k , webm_dash container, vp9@ 322k, 30fps, video only, 1.51MiB
397          mp4        480x854    480p  396k , mp4_dash container, av01.0.04M.08@ 396k, 30fps, video only, 1.86MiB
136          mp4        720x1280   720p  489k , mp4_dash container, avc1.4d401f@ 489k, 30fps, video only, 2.29MiB
247          webm       720x1280   720p  530k , webm_dash container, vp9@ 530k, 30fps, video only, 2.49MiB
398          mp4        720x1280   720p  706k , mp4_dash container, av01.0.05M.08@ 706k, 30fps, video only, 3.31MiB
399          mp4        1080x1920  1080p 1250k , mp4_dash container, av01.0.08M.08@1250k, 30fps, video only, 5.86MiB
248          webm       1080x1920  1080p 1544k , webm_dash container, vp9@1544k, 30fps, video only, 7.24MiB
137          mp4        1080x1920  1080p 1801k , mp4_dash container, avc1.640028@1801k, 30fps, video only, 8.44MiB
18           mp4        360x640    360p  600k , avc1.42001E, 30fps, mp4a.40.2 (48000Hz), 2.82MiB
22           mp4        720x1280   720p  618k , avc1.64001F, 30fps, mp4a.40.2 (44100Hz) (best)
$ 
```

**Pull request merged**
