### PR TITLE
[zdf] rework format extraction to find additional videos (fixes #17747)

### LINKED ISSUE #17747: [ZDF] HD format as mp4 file (best) not found
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
youtube-dl -v -F https://www.zdf.de/filme/kudamm-56/kudamm-56-teil-1-102.html
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-v', u'-F', u'https://www.zdf.de/filme/kudamm-56/kudamm-56-teil-1-102.html']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.09.26
[debug] Python version 2.7.15 (CPython) - Linux-4.14.0-3-amd64-x86_64-with-debian-9.0
[debug] exe versions: ffmpeg 3.4.2-1, ffprobe 3.4.2-1, rtmpdump 2.4
[debug] Proxy map: {}
[ZDF] kudamm-56-teil-1-102: Downloading webpage
[ZDF] kudamm-56-teil-1-102: Downloading JSON content
[ZDF] kudamm-56-teil-1-102: Downloading JSON metadata
[ZDF] kudamm-56-teil-1-102: Downloading m3u8 information
[ZDF] kudamm-56-teil-1-102: Downloading m3u8 information
[ZDF] kudamm-56-teil-1-102: Downloading f4m manifest
[ZDF] kudamm-56-teil-1-102: Downloading f4m manifest
[info] Available formats for kudamm-56-teil-1-102:
format code                              extension  resolution note
hls-55-0                                 mp4        audio only   55k , mp4a.40.2
hls-55-1                                 mp4        audio only   55k , mp4a.40.2
http-h264_aac_mp4_http_na_na-low         mp4        unknown    [deu] low 
http-h264_aac_mp4_http_na_na-high-0      mp4        unknown    [deu] high 
http-h264_aac_mp4_http_na_na-high-1      mp4        unknown    [deu] high 
http-h264_aac_mp4_http_na_na-veryhigh-0  mp4        unknown    [deu] veryhigh 
http-h264_aac_mp4_http_na_na-veryhigh-1  mp4        unknown    [deu] veryhigh 
hls-124                                  mp4        240x136     124k , avc1.66.30, mp4a.40.2
hds-187-0                                flv        unknown     187k 
hds-187-1                                flv        unknown     187k 
hls-187                                  mp4        320x176     187k , avc1.77.30, mp4a.40.2
hls-220                                  mp4        320x176     220k , avc1.66.30, mp4a.40.2
hls-273                                  mp4        320x176     273k , avc1.66.30, mp4a.40.2
hds-435-0                                flv        unknown     435k 
hds-435-1                                flv        unknown     435k 
hls-435                                  mp4        480x272     435k , avc1.77.30, mp4a.40.2
hls-476                                  mp4        480x272     476k , avc1.66.30, mp4a.40.2
hds-605                                  flv        unknown     605k 
hls-605                                  mp4        640x360     605k , avc1.77.30, mp4a.40.2
hds-1456                                 flv        unknown    1456k 
hls-1456                                 mp4        852x480    1456k , avc1.77.30, mp4a.40.2
hds-2257                                 flv        unknown    2257k 
hls-2257                                 mp4        1024x576   2257k , avc1.77.30, mp4a.40.2
hds-3258                                 flv        unknown    3258k 
hls-3258                                 mp4        1280x720   3258k , avc1.77.30, mp4a.40.2 (best)
```

---

### Description of your *issue*, suggested solution and other information

1280x720 mp4 file (https://rodlzdf-a.akamaihd.net/none/zdf/16/03/160320_kudamm_teil1_kud/4/160320_kudamm_teil1_kud_3328k_p36v12.mp4) has not been discovered. It should be selected as "best" instead of hls-3258 ts stream (which would need ffmpeg processing).

Above is only an example for the issue with ZDF.

I'm aware of one working workaround for this issue: using the advertised HTTP link for mp4 file with the highest resolution, try to locate a file with HD resolution by replacing the trailing part of the URL.

https://github.com/mediathekview/MServer/blob/8dc8646ba66d80d747bf21394dcc7ed0a1f293dc/src/main/java/mServer/crawler/sender/MediathekZdf.java#L189-L236
```java
  private static void updateHdStatus(DatenFilm film, String urlSeite) {
    // manuell die Auflösung für HD setzen, 2 Versuche
    updateHd("1456k_p13v12.mp4", "3328k_p36v12.mp4", film, urlSeite);
    updateHd("2256k_p14v12.mp4", "3328k_p36v12.mp4", film, urlSeite);
    updateHd("2328k_p35v12.mp4", "3328k_p36v12.mp4", film, urlSeite);


    updateHd("1456k_p13v12.mp4", "3256k_p15v12.mp4", film, urlSeite);
    updateHd("2256k_p14v12.mp4", "3256k_p15v12.mp4", film, urlSeite);
    updateHd("2328k_p35v12.mp4", "3256k_p15v12.mp4", film, urlSeite);


    updateHd("1496k_p13v13.mp4", "3296k_p15v13.mp4", film, urlSeite);
    updateHd("2296k_p14v13.mp4", "3296k_p15v13.mp4", film, urlSeite);
    updateHd("2328k_p35v13.mp4", "3296k_p15v13.mp4", film, urlSeite);


    updateHd("1496k_p13v13.mp4", "3328k_p36v13.mp4", film, urlSeite);
    updateHd("2296k_p14v13.mp4", "3328k_p36v13.mp4", film, urlSeite);
    updateHd("2328k_p35v13.mp4", "3328k_p36v13.mp4", film, urlSeite);


    updateHd("1496k_p13v14.mp4", "3328k_p36v14.mp4", film, urlSeite);
    updateHd("2296k_p14v14.mp4", "3328k_p36v14.mp4", film, urlSeite);
    updateHd("2328k_p35v14.mp4", "3328k_p36v14.mp4", film, urlSeite);


    updateHd("1496k_p13v14.mp4", "3328k_p35v14.mp4", film, urlSeite);
    updateHd("2296k_p14v14.mp4", "3328k_p35v14.mp4", film, urlSeite);
    updateHd("2328k_p35v14.mp4", "3328k_p35v14.mp4", film, urlSeite);
  }


  private static void modifyUrl(DatenFilm film, String urlSeite, FilmeSuchen mSFilmeSuchen) {
    //große URL verbessern
    changeUrl("2256k_p14v11.mp4", "2328k_p35v11.mp4", film, urlSeite, mSFilmeSuchen);
    changeUrl("2256k_p14v12.mp4", "2328k_p35v12.mp4", film, urlSeite, mSFilmeSuchen);
    changeUrl("2296k_p14v13.mp4", "2328k_p35v13.mp4", film, urlSeite, mSFilmeSuchen);


    //klein nach groß
    changeUrl("1456k_p13v11.mp4", "2328k_p35v11.mp4", film, urlSeite, mSFilmeSuchen);
    changeUrl("1456k_p13v11.mp4", "2256k_p14v11.mp4", film, urlSeite, mSFilmeSuchen); //wenns nicht geht, dann vielleicht so


    changeUrl("1456k_p13v12.mp4", "2328k_p35v12.mp4", film, urlSeite, mSFilmeSuchen);
    changeUrl("1456k_p13v12.mp4", "2256k_p14v12.mp4", film, urlSeite, mSFilmeSuchen); //wenns nicht geht, dann vielleicht so


    changeUrl("1496k_p13v13.mp4", "2328k_p35v13.mp4", film, urlSeite, mSFilmeSuchen);
    changeUrl("1496k_p13v13.mp4", "2296k_p14v13.mp4", film, urlSeite, mSFilmeSuchen); //wenns nicht geht, dann vielleicht so
  }


  public static void urlTauschen(DatenFilm film, String urlSeite, FilmeSuchen mSFilmeSuchen) {
    modifyUrl(film, urlSeite, mSFilmeSuchen);
    updateHdStatus(film, urlSeite);
  }
```

### PR DESCRIPTION
**Pull request by ngdio**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fixes #17747. The improved version will try to find additional formats by sending HEAD requests in order to find out whether the files exist on their servers.

### CODE REVIEW

**Comment by ngdio** [comment]
Pushing this. Been a year but still working as supposed.

**Comment by andreygursky** [comment]
Due to checking it works slower but nice it works at all, thanks!

One issue I've just discovered. If the original audio track is also available, this patch auto selects the video with this track as 'best', which is undesired.

Tested with https://www.zdf.de/serien/24-hours/24-hours---two-sides-of-crime-1-100.html Unfortunately it will be de-published in about 2 hours.

```
$ youtube-dl -F --load-info-json '24 Hours-24-hours---two-sides-of-crime-1-100.info.json'
[info] Available formats for 24-hours---two-sides-of-crime-1-100:
format code            extension  resolution note
hls-aac-Originalton-0  mp4        audio only [deu] 
hls-aac-Originalton-1  mp4        audio only [nld] 
hls-aac-Originalton-2  mp4        audio only [deu] 
hls-aac-Originalton-3  mp4        audio only [nld] 
hls-aac-TV_Ton-0       mp4        audio only [deu] 
hls-aac-TV_Ton-1       mp4        audio only [nld] 
hls-aac-TV_Ton-2       mp4        audio only [deu] 
hls-aac-TV_Ton-3       mp4        audio only [nld] 
hls-95-0               mp4        audio only [nld]   95k , mp4a.40.2
hls-95-1               mp4        audio only [nld]   95k , mp4a.40.2
hls-96-0               mp4        audio only [deu]   96k , mp4a.40.2
hls-96-1               mp4        audio only [deu]   96k , mp4a.40.2
hls-380-0              mp4        480x272    [nld]  380k , avc1.77.30, video only
hls-380-1              mp4        480x272    [nld]  380k , avc1.77.30, video only
hls-381-0              mp4        480x272    [deu]  381k , avc1.77.30, video only
hls-381-1              mp4        480x272    [deu]  381k , avc1.77.30, video only
hls-619-0              mp4        640x360    [deu]  619k , avc1.77.30, video only
hls-619-1              mp4        640x360    [nld]  619k , avc1.77.30, video only
hls-619-2              mp4        640x360    [deu]  619k , avc1.77.30, video only
hls-619-3              mp4        640x360    [nld]  619k , avc1.77.30, video only
hls-620-0              mp4        640x360    [deu]  620k , avc1.77.30, video only
hls-620-1              mp4        640x360    [nld]  620k , avc1.77.30, video only
hls-620-2              mp4        640x360    [deu]  620k , avc1.77.30, video only
hls-620-3              mp4        640x360    [nld]  620k , avc1.77.30, video only
hls-1210-0             mp4        852x480    [nld] 1210k , avc1.77.30, video only
hls-1210-1             mp4        852x480    [nld] 1210k , avc1.77.30, video only
hls-1211-0             mp4        852x480    [deu] 1211k , avc1.77.30, video only
hls-1211-1             mp4        852x480    [deu] 1211k , avc1.77.30, video only
hls-1870               mp4        1024x576   [nld] 1870k , avc1.77.30, video only
hls-1871               mp4        1024x576   [deu] 1871k , avc1.77.30, video only
hls-2690-0             mp4        1280x720   [deu] 2690k , avc1.640028, video only
hls-2690-1             mp4        1280x720   [nld] 2690k , avc1.640028, video only
hds-381-0              flv        unknown    [deu]  381k 
hds-381-1              flv        unknown    [deu]  381k 
mp4-476-alt-0          mp4        480x272    [deu]  476k , avc1.4d401f, mp4a.40.2
mp4-476-alt-1          mp4        480x272    [nld]  476k , avc1.4d401f, mp4a.40.2
hds-620                flv        unknown    [deu]  620k 
mp4-776-alt-0          mp4        640x360    [deu]  776k , avc1.4d401f, mp4a.40.2
mp4-776-alt-1          mp4        640x360    [nld]  776k , avc1.4d401f, mp4a.40.2
mp4-776-0              mp4        640x360    [deu]  776k , avc1.4d401f, mp4a.40.2
mp4-776-1              mp4        640x360    [nld]  776k , avc1.4d401f, mp4a.40.2
hds-1211               flv        unknown    [deu] 1211k 
mp4-1496-alt-0         mp4        852x480    [deu] 1496k , avc1.4d401f, mp4a.40.2
mp4-1496-alt-1         mp4        852x480    [nld] 1496k , avc1.4d401f, mp4a.40.2
mp4-1496-0             mp4        852x480    [deu] 1496k , avc1.4d401f, mp4a.40.2
mp4-1496-1             mp4        852x480    [nld] 1496k , avc1.4d401f, mp4a.40.2
hds-1871               flv        unknown    [deu] 1871k 
mp4-2296-alt-0         mp4        1024x576   2296k , avc1.4d001f, mp4a.40.2
mp4-2296-alt-1         mp4        1024x576   2296k , avc1.4d001f, mp4a.40.2
mp4-2296-0             mp4        1024x576   2296k , avc1.4d001f, mp4a.40.2
mp4-2296-1             mp4        1024x576   2296k , avc1.4d001f, mp4a.40.2
mp4-2328-alt-0         mp4        1024x576   2328k , avc1.4d001f, mp4a.40.2
mp4-2328-alt-1         mp4        1024x576   2328k , avc1.4d001f, mp4a.40.2
mp4-2328-0             mp4        1024x576   2328k , avc1.4d001f, mp4a.40.2
mp4-2328-1             mp4        1024x576   2328k , avc1.4d001f, mp4a.40.2
hds-2690               flv        unknown    [deu] 2690k 
mp4-3328-alt-0         mp4        1280x720   3328k , avc1.640028, mp4a.40.2
mp4-3328-alt-1         mp4        1280x720   3328k , avc1.640028, mp4a.40.2
mp4-3328-0             mp4        1280x720   3328k , avc1.640028, mp4a.40.2
mp4-3328-1             mp4        1280x720   3328k , avc1.640028, mp4a.40.2 (best)
```
```
$ youtube-dl -f best --get-url --load-info-json '24 Hours-24-hours---two-sides-of-crime-1-100.info.json'
https://rodlzdf-a.akamaihd.net/de/zdf/18/10/181005_folge1_24h/6/181005_folge1_24h_a3a4_3328k_p36v14.mp4
```
a3a4 with original audio track
```
$ youtube-dl -f mp4-3328-0 --get-url --load-info-json '24 Hours-24-hours---two-sides-of-crime-1-100.info.json'
https://rodlzdf-a.akamaihd.net/de/zdf/18/10/181005_folge1_24h/6/181005_folge1_24h_a1a2_3328k_p36v14.mp4
```
a1a2 with german audio track.

**Comment by ngdio** [comment]
I've never seen videos with alternative audio tracks before, neither has the original author of this extractor apparently, so that certainly needs to be addressed. There's probably information about the tracks' language somewhere in the API data.

**Comment by kubin3818** [comment]
ngdio:zdf

**Comment by andreygursky** [comment]
It looks like there is a following general rule:
* a1a2 - German (default)
* a3a4 - original
* a5a6 - German with audio description

E.g.:
* "Mirage - Gefährliche Lügen" series https://www.zdf.de/serien/mirage-gefaehrliche-luegen/mirage-gefaehrliche-luegen-folge-1-100.html (available until 05.09.2020)
* "The Mallorca Files" series https://www.zdf.de/serien/the-mallorca-files/sag-niemals-goodbye-compaero-100.html (available until 25.10.2020)

**Pull request closed without merging**
