### PR TITLE
[rmcdecouverte] Expand to RMC Story

### PR DESCRIPTION
**Pull request by Anarky**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [X] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This pull request adds the French replay channel "RMC Story" to the "RMC Découverte" extractor.

### CODE REVIEW

**Comment by dstftw** [comment]
No code copypasting.

**Comment by Anarky** [comment]
@dstftw how should I do it? I guess I could rename `rmcstory.py` to `rmc.py` (or `rmc_story_decouverte.py`?) then add more if/else to set the correct Brightcove ID... Do you agree with that?

**Comment by dstftw** [comment]
Do not touch the filename. Extend URL regex, add mapping to brighcove id.

**Comment by Anarky** [comment]
@dstftw Here is the new version, the regex is less strict for RMC Découverte, I had to remove the "program_" string that RMC Story doesn't have.

**Comment by Anarky** [comment]
@dstftw could you please review this PR?

**Comment by kissifrot** [comment]
LGTM, tested on an updated URL (https://rmcstory.bfmtv.com/titans-des-mers_2715/navire-de-peche-en-alaska_13063/) and works

**Comment by Anarky** [comment]
Please merge my PR, RMC Découverte is also broken now without it; you can see with https://rmcdecouverte.bfmtv.com/americars_27301/datsun-280z_12069/

**Comment by kissifrot** [comment]
Hello, any news about this?

**Pull request closed without merging**
