### PR TITLE
[tunein] Fix existing extractors and add playlist (closes #20252)

### LINKED ISSUE #20252: [tunein] TuneIn does not work anymore (JSON parse error)
```
$youtube-dl http://tun.in/sekNY -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'http://tun.in/sekNY', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.01
[debug] Python version 2.7.15 (CPython) - Linux-4.20.10-1-default-x86_64-with-glibc2.2.5
[debug] exe versions: ffmpeg 4.1, ffprobe 4.1
[debug] Proxy map: {}
[tunein:shortener] sekNY: Downloading redirect page
[tunein:shortener] Following redirect: https://tunein.com/radio/Europe-1-1047-s6566/
[tunein:station] 6566: Downloading JSON metadata
ERROR: 6566: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/bobbie/bin/youtube-dl/youtube_dl/extractor/common.py", line 877, in _parse_json
    return json.loads(json_string)
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/home/bobbie/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/home/bobbie/bin/youtube-dl/youtube_dl/extractor/common.py", line 508, in extract
    ie_result = self._real_extract(url)
  File "/home/bobbie/bin/youtube-dl/youtube_dl/extractor/tunein.py", line 25, in _real_extract
    content_id, note='Downloading JSON metadata')
  File "/home/bobbie/bin/youtube-dl/youtube_dl/extractor/common.py", line 870, in _download_json
    expected_status=expected_status)
  File "/home/bobbie/bin/youtube-dl/youtube_dl/extractor/common.py", line 854, in _download_json_handle
    fatal=fatal), urlh
  File "/home/bobbie/bin/youtube-dl/youtube_dl/extractor/common.py", line 881, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
ExtractorError: 6566: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### PR DESCRIPTION
**Pull request by biwubo**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Seems tunein have changed their APIs, so the extractors needed to be updated.

I removed the `TuneInClipIE` extractor because these seem to have been deprecated for the following reasons:
- Almost all non-live content seems to served as a `Program` of `Topic`s
- Even on pages with clips, you cannot select the one you want to listen to (e.g https://tunein.com/radio/College-Sports-Now-s254142/?audioclipid=12617)

Previously the `TuneInProgramIE` extractor extracted a live stream. These live streams can be accessed through their own station page. For e.g the program page https://tunein.com/radio/Jazz-24-p2506/ extracted the station https://tunein.com/radio/WUKY-HD2-913-s67052/. As a result I have changed the extractor to extract a playlist of `Topic`s so in the case above it would raise an error but you can still use the easily accessible station link and it will extract using the `TuneInStationIE` extractor like before.

### CODE REVIEW

**Comment by bubbleguuum** [comment]
I have tested this branch on a few tunein stations and confirm that it works properly.

**Comment by biwubo** [comment]
@dstftw @remitamine Hi, is there anything I can do to help getting this PR reviewed?

**Comment by ElonSatoshi** [comment]
Is there a reason why this hasn't been merged yet?

**Comment by slacka** [comment]
@dstftw or @remitamine 
This fixes TuneIn which is currently completely broken. Can you please merge it?

**Comment by ElonSatoshi** [comment]
@dstftw or @remitamine

Happy new year!

**Pull request closed without merging**
