### PR TITLE
[MiTele.es] Fix new m3u8 server

### PR DESCRIPTION
**Pull request by DarkZeros**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

* Old mitele extractor used to forward to Ooyala extractor (videos used Ooyala backend)
* They changed that for a custom cerbero server that they own with a different extraction process
* The cerbero server gives a token that needs to be added to the m3u8 download options in order to be a valid request
* The server checks the callers IP before giving a token so the tests will fail outside Spain unfortunately

### CODE REVIEW

**Comment by DarkZeros** [comment]
Seems it is already done, my bad (and my time lost) https://github.com/ytdl-org/youtube-dl/pull/25827

**Comment by felisucoibi** [comment]
ANYWAY THANKS FOR THE EFFORT

**Comment by felisucoibi** [comment]
I think new changes here...
2020-10-23 Más Que Coches - /programas-tv/mas-que-coches/temporada-2020/Progr-1221-40_1008251575019/player/
2020-10-23 Cuarto Milenio - /programas-tv/cuarto-milenio/temporada-15/programa-623-40_1008608575015/player/

**Comment by felisucoibi** [comment]
still missing one step for registered users with the right cookie to download premium content

**Comment by DarkZeros** [comment]
I don't think that possible.... Anyway I think they merged Telecinco with Mitele, so this patch is no more needed upstream.

**Pull request closed without merging**
