### PR TITLE
[iqiyi] Fix extraction

### PR DESCRIPTION
**Pull request by wqfan**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
- Fix the extraction of iQIYI which can resolve https://github.com/ytdl-org/youtube-dl/issues/16852.
- The `tvid` and `video_id` search regexes are stolen from  
  - https://github.com/iawia002/annie/blob/67298d55aaf43d840b8d7283b0ac99736173d285/extractors/iqiyi/iqiyi.go#L118-L119
  - https://github.com/iawia002/annie/blob/67298d55aaf43d840b8d7283b0ac99736173d285/extractors/iqiyi/iqiyi.go#L135-L136

### CODE REVIEW

**Comment by zackmark29** [comment]
Why iqiyi extractor doesn't work with this link?
https://www.iq.com/play/19rrhm35it

**Comment by lzkgbld** [comment]
是否已经提交完毕，我尝试下载https://www.iqiyi.com/v_ulduwjfswo.html该页面视频会发生该错误：[iqiyi] temp_id: download video page

**Comment by wqfan** [comment]
@zackmark29 Can you be more specific about why it doesn't work for you? It seems working for me but only downloading the first 30s. Is this what you were seeing?

```
➜ python -m youtube_dl https://www.iq.com/play/19rrhm35it
[generic] 19rrhm35it: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 19rrhm35it: Downloading webpage
[generic] 19rrhm35it: Extracting information
[download] Backstreet Rookie-19rrhm35it.mp4 has already been downloaded
[download] 100% of 37.73MiB
```

**Comment by wqfan** [comment]
@lzkgbld Can you also be more specific about the error? It works for me but seems slow though:

```
➜ python -m youtube_dl https://www.iqiyi.com/v_ulduwjfswo.html

[iqiyi] temp_id: download video page
[iqiyi] 6f3942722dd805b6ef86006451bd1c40: Downloading JSON metadata
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 363
[download] Destination: 重启之极海听雷第二季第1集-电视剧全集-完整版视频在线观看-爱奇艺-6f3942722dd805b6ef86006451bd1c40.mp4
[download]   3.1% of ~531.58MiB at 157.21KiB/s ETA 55:13
```

**Comment by lzkgbld** [comment]
我尝试输入链接直接进行下载，他的报错依旧是Can't find any video; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

image


> @lzkgbld您还能更详细地说明该错误吗？它对我有用，但似乎很慢：
> 
> ```
> ➜ python -m youtube_dl https://www.iqiyi.com/v_ulduwjfswo.html
> 
> [iqiyi] temp_id: download video page
> [iqiyi] 6f3942722dd805b6ef86006451bd1c40: Downloading JSON metadata
> [hlsnative] Downloading m3u8 manifest
> [hlsnative] Total fragments: 363
> [download] Destination: 重启之极海听雷第二季第1集-电视剧全集-完整版视频在线观看-爱奇艺-6f3942722dd805b6ef86006451bd1c40.mp4
> [download]   3.1% of ~531.58MiB at 157.21KiB/s ETA 55:13
> ```

**Comment by wqfan** [comment]
@lzkgbld Seems you were testing with the released version. This PR is still open so the code is not merged into mainline yet. If you want to use this change now, you need to clone the code to your local and then run it with:

```
python -m youtube_dl <your link>
```

**Comment by zackmark29** [comment]
> @zackmark29 Can you be more specific about why it doesn't work for you? It seems working for me but only downloading the first 30s. Is this what you were seeing?
> 
> ```
> ➜ python -m youtube_dl https://www.iq.com/play/19rrhm35it
> [generic] 19rrhm35it: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 19rrhm35it: Downloading webpage
> [generic] 19rrhm35it: Extracting information
> [download] Destination: Backstreet Rookie-19rrhm35it.mp4
> [download] 100% of 37.73MiB in 00:06
> ```

Yeah it can only download the trailer. It can't detect the streams

**Comment by zackmark29** [comment]
> @zackmark29 Can you be more specific about why it doesn't work for you? It seems working for me but only downloading the first 30s. Is this what you were seeing?
> 
> ```
> ➜ python -m youtube_dl https://www.iq.com/play/19rrhm35it
> [generic] 19rrhm35it: Requesting header
> WARNING: Falling back on generic information extractor.
> [generic] 19rrhm35it: Downloading webpage
> [generic] 19rrhm35it: Extracting information
> [download] Destination: Backstreet Rookie-19rrhm35it.mp4
> [download] 100% of 37.73MiB in 00:06
> ```

iq.com is the international domain. which is not yet supported by youtube-dl.
Can you perhaps made possible to support that url? it's almost the same with iqiyi.com but only difference are the name of queries

**Comment by wqfan** [comment]
@zackmark29 I can take a look when I get time, but it's probably going to be in a different PR.

**Comment by lzkgbld** [comment]
@wqfan Thank you for taking your code and modifying it so that it can be downloaded, but the download speed is really a bit slow...

**Comment by zackmark29** [comment]
> @zackmark29 I can take a look when I get time, but it's probably going to be in a different PR.

Wow that's great! thanks for your effort. That could also be helpful to others

**Comment by zackmark29** [comment]
> @zackmark29 I can take a look when I get time, but it's probably going to be in a different PR.

could you mention me if you will create a new pr so that I can follow?

**Comment by lzkgbld** [comment]
@wqfan 请问一下，您是否试过下载VIP视频，我尝试将登陆cookie文件下载了下来，然后在下载中也带上了cookie文件，但是下载还是试看的视频。

**Comment by zackmark29** [comment]
Is there any progress for IQ.COM?

**Pull request closed without merging**
