### PR TITLE
[utils] Add support for DCSubtitle

### PR DESCRIPTION
**Pull request by TRox1972**
## Please follow the guide below
- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your _pull request_ (like that [x])
- Use _Preview_ tab to see how your _pull request_ will actually look like

---
### Before submitting a _pull request_ make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
### What is the purpose of your _pull request_?
- [ ] Bug fix
- [ ] New extractor
- [x] New feature

---
### Description of your _pull request_ and other information

This adds support for DC subtitles, an XML-format.
https://web.archive.org/web/20140924175755/http://www.dlp.com/downloads/pdf_dlp_cinema_CineCanvas_Rev_C.pdf

### CODE REVIEW

**Comment by yan12125** [comment]
Well my ```dfxp2srt``` is indeed awful. It should convert dfxp to some intermediate representation (possibly Python objects), and then convert it to SRT. Otherwise there would be lots of duplicated codes if a new format is introduced. Would you like to rewrite ```dfxp2srt``` for making multiple format support easier?

**Comment by TRox1972** [comment]
@yan12125 I can try :)  So do you suggest creating a function that converts dfxp (and others) to Python objects and another function to convert it to SRT?

**Comment by yan12125** [comment]
> creating a function that converts dfxp (and others) to Python objects and another function to convert it to SRT?

That would be nice. Those functions can be tested separately.

**Comment by remitamine** [comment]
is this type of subtitles really used in the web?

**Comment by dstftw** [comment]
Yes, it's used, for example http://www.viafree.se/program/livsstil/husraddarna/sasong-3/avsnitt-7.

**Pull request closed without merging**
