### PR TITLE
[adobepass] add verizon_hba mso and verizon saml improvements

### PR DESCRIPTION
**Pull request by SkiTheSlicer**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Turner extractors (AdultSwim, TNT, TBS, etc) use "Verizon_HBA" instead of "Verizon" as the MSO name, though the credentials are the same.

Also, I've encountered some additional login pipelines that are used by providers such as USA that have given me problems. This appears to also be flagged as issue #13848.

### CODE REVIEW

**Comment by beren12** [comment]
this is needed for disney jr now as well

**Comment by nyuszika7h** [comment]
Any reason this isn't merged yet? It fixes Verizon login for me.

**Comment by Zenexer** [comment]
@rg3 Could you consider merging this?  It's a very simple addition that fixes several popular sites for Verizon users.

**Comment by rg3** [comment]
Pinging the current maintainers: @dstftw

**Comment by Zenexer** [comment]
I merged this PR into master locally and confirmed that it does work for Turner services (e.g., TBS, Adult Swim).  Haven't tested other streaming services yet.

**Comment by beren12** [comment]
It's needed for truTV I found out last week.

**Comment by SkiTheSlicer** [comment]
I unfortunately don't have Verizon FiOS TV services anymore to test any changes. I wouldn't feel comfortable updating this PR without it. Hopefully someone else out there with credentials is able to work it out with you.

**Comment by beren12** [comment]
Could someone please help update this and get it into mainline? If needed I can provide a temp verizon login...

**Comment by beren12** [comment]
BTW The update from @ParadoxGBB is letting me download from https://disneynow.go.com with Verizon. I have not tried TBS.

**Comment by keithah** [comment]
@ParadoxGBB Can you submit a PR for your fix? Thanks!

**Comment by Zenexer** [comment]
This no longer appears to be relevant; Verizon_HBA has been replaced with Verizon everywhere I've checked.

**Pull request closed without merging**
