### PR TITLE
Remove "Get cookies.txt" extension from README.md

### LINKED ISSUE #31465: Remove link to malicious extension in README.md
[Get cookies.txt](https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid) extension it is a malicious extension which must be reported and removed from README.
It sends the following data of every request in your browser to https://ck.getcookiestxt.com/getcookie
```
{  
  "timestamp": "<TSTAMP>",  
  "e": "<UUID Identifying your Device",  
  "f": "<USERAGENT>",  
  "b": "<FULL URL>,  
  "locale": "<LOCALE_CODE - your Language Settings>",  
  "platform": "<PLATTFORM - MAC/Win/Linux...>"  
}
```

### PR DESCRIPTION
**Pull request by Sophira**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The "Get cookies.txt" extension (which used to be okay) has now turned malicious and is no longer suitable for recommending to others, so this pull request edits README.md to remove the link to it.

This PR does **not** alter any code, so I have not run any tests as they are not applicable.

Fixes #31465.

### CODE REVIEW

**Comment by dirkf** [comment]
Thanks for your help.

It would be nice to be able to offer **some** way for benighted Chrome users to extract cookies.

The Reddit thread says that there is a setting to disable the "logging".

Otherwise, what happens if ck.getcookiestxt.com is blocked at the firewall or aliased to a 127.0.0.1 or 0.0.0.0?

**Comment by nicolaasjan** [comment]
> Otherwise, what happens if ck.getcookiestxt.com is blocked at the firewall or aliased to a 127.0.0.1 or 0.0.0.0?

That's what I [suggested there](https://old.reddit.com/r/youtubedl/comments/10ar7o7/if_youve_been_using_the_get_cookiestxt_chrome/j45u5zy/) in the earlier Reddit thread about this extension. 😀️

Works until he changes the domain name...
As you can see it no longer resolves to `170.64.252.54` here. 🙂

```
dig ck.getcookiestxt.com

; <<>> DiG 9.16.1-Ubuntu <<>> ck.getcookiestxt.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52436
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;ck.getcookiestxt.com.		IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: zo mrt 05 07:20:12 CET 2023
;; MSG SIZE  rcvd: 49
```

**Comment by nicolaasjan** [comment]
> It would be nice to be able to offer **some** way for benighted Chrome users to extract cookies.

For Chrome there is is also the Windows program [ChromeCookiesView](https://www.nirsoft.net/utils/chrome_cookies_view.html), from which you can export to Netscape text format.

**Comment by dirkf** [comment]
What's his licence? Can someone just replicate the add-on from the .crx with the unwanted phone-home code removed, à la Stylish/Stylus?

**Comment by nicolaasjan** [comment]
> What's his licence?

Nowhere to be found...
Privacy policy [here](https://docs.google.com/document/d/1cZXBCoVDryifkGdfTA23UZR1-VDZCqfBlqgEZU03xiE/edit).

GitHub "repo" [here](https://github.com/getcookiestxt/GetCookies.txt).

> The extension GetCookies.txt is closed source.

https://github.com/getcookiestxt/GetCookies.txt/issues/2

Just forget about Chrome and point users to Firefox. 😀️

**Comment by nicolaasjan** [comment]
Would it be feasible to port yt-dlp's  option `--cookies-from-browser`?

**Comment by pukkandan** [comment]
> Would it be feasible to port yt-dlp's option `--cookies-from-browser`?

It was originally a ytdl PR https://github.com/ytdl-org/youtube-dl/pull/29201, though it's feature set is now a bit outdated compared to yt-dlp

**Comment by dirkf** [comment]
Any browser extension, especially a Chrome extension that can't have native binary code, contains the JS source, which can be inspected in the extension. The author here likes jQuery, so a minimised jQuery 3.6.3 is included in v1.5.

**Comment by gamer191** [comment]
> so this pull request edits README.md to remove the link to it

yt-dlp went a step further: https://github.com/yt-dlp/yt-dlp-wiki/commit/1043ec2c9e773cb27a3e8e860a65993b2d225508:
> In particular, **beware of the `Get cookies.txt` extension for Chrome!** There are credible reports of it being malware.

**Comment by pukkandan** [comment]
That's fine for the wiki, but is out of place in a readme imho

**Comment by Sophira** [comment]
This pull request is no longer as urgent as it was before, as the extension has now been removed from the Chrome Web Store as malware.

Meanwhile, a commenter on my post has suggested a replacement: [Get cookies.txt LOCALLY](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc). It's a very nice extension that's open source (unlike the original extension) and Manifest V3-compatible. I'll update my PR to link to this extension as it's the best replacement I know of so far.

**Comment by dirkf** [comment]
Looks like a good resolution.

**Comment by nicolaasjan** [comment]
It's still in the Microsoft Store...
https://microsoftedge.microsoft.com/addons/detail/get-cookiestxt/helleheikohejgehaknifdkcfcmceeip?hl=en-GB

**Comment by gamer191** [comment]
> The only solution is to STOP USING THAT EXTENSION IMMEDIATELY and Change Your Passwords.

There is advice on what to do in the reddit post. That's not the advice, and could be counter productive (I'm not an expert)

**Review by dirkf — APPROVED** [review]
LGTM

Also, the newly linked extension looks like a proper job.

**Pull request merged**
