### PR TITLE
Detect wrong video IDs for youtube and correct them

### PR DESCRIPTION
**Pull request by AStove**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Youtube video ids are the result of a base 64 encoding. 
For example DJztXj2GPfk is the result of encoding 0c 9c ed 5e 3d 86 3d f9
But due to padding video id DJztXj2GPfl will decode into this same binary value.
Due to this, youtube-dl will download both DJztXj2GPfk and DJztXj2GPfl, it will result in the same file.
So why would we need this change? This does not work for all youtube APIs, for example it doesn't work for age gated content. Does work for 6QFwo57WKwg but does not work for 6QFwo57WKwh. The 6QFwo57WKwh id gives an age gated error, while this is irrelevant, it's the id that is wrong.

### CODE REVIEW

**Comment by dstftw** [comment]
You should not make any assumptions about id. Youtube redirects to the page with correct id that must be taken instead of this.

**Comment by AStove** [comment]
The assumption is correct and it saves a bunch of time and requests.

**Comment by oxguy3** [comment]
The assumption may be correct now, but there is no guarantee that it will remain correct in the future. There is little harm in downloading a duplicate file, especially given that this seems to be an extremely unusual edge case. However, there would be harm in failing to download two separate videos because we made a bad assumption about YouTube's IDs.

Do these wrongly-padded video IDs actually appear in the wild? Is this issue affecting any users?

**Comment by AStove** [comment]
You are right.
> Do these wrongly-padded video IDs actually appear in the wild?

No.
>Is this issue affecting any users?

No.

**Pull request closed without merging**
