### PR TITLE
[AENetworks] Update extractor for the current site(s)

### LINKED ISSUE #23363: AETV.com Unable to extract video url
C:\Users\user\Downloads>youtube-dl -v https://www.aetv.com/shows/born-this-way/season-1/episode-1
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.aetv.com/shows/born-this-way/season-1/episode-1']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.11.28
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: none
[debug] Proxy map: {}
[aenetworks] born-this-way/season-1/episode-1: Downloading webpage
ERROR: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\aenetworks.py", line 176, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpwy0zjfmc\build\youtube_dl\extractor\common.py", line 1005, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract video url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

C:\Users\user\Downloads>

### PR DESCRIPTION
**Pull request by kevinoconnor7**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This gets the AENetworks extractor back into a working state. The highlights are:

  * Support for the `play` subdomain that the content is now hosted on
  * Extract ThePlatform URLs from the GraphQL endpoint they now use
  * Properly extract video information from the updates made to the non-play subdomain sites.
  * Properly extract the series name, season number, and episode numbers
  * Added more explicit error messages for when extraction fails

Fixes #23363

### CODE REVIEW

**Comment by yemaozitw** [comment]
Works for shows but not specials like:

https://play.aetv.com/specials/voices-magnified-locked-up-in-america/full-special
https://play.aetv.com/specials/biography-i-want-my-mtv-2/full-special
https://play.aetv.com/specials/the-nine-lives-of-ozzy-osbourne/full-special

These get the following errors:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', '--cookies', 'cookies.txt', '--ap-mso=Philo', '--ap-username=PRIVATE', '--ap-password=PRIVATE', '--fragment-retries', '35', '--retries', '35', '--all-subs', '--sub-format', 'dfxp', 'https://play.aetv.com/specials/voices-magnified-locked-up-in-america/full-special', '-o', 'scratch/Voices Magnified Locked Up in America 2020 720p WEB-DL H.264 AAC2.0-ymz.mp4']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] voices-magnified-locked-up-in-america: Downloading webpage
WARNING: unable to extract videoId; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[aenetworks] Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ymz/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ymz/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by yemaozitw** [comment]
Works for shows but not specials like:

https://play.aetv.com/specials/voices-magnified-locked-up-in-america/full-special
https://play.aetv.com/specials/biography-i-want-my-mtv-2/full-special
https://play.aetv.com/specials/the-nine-lives-of-ozzy-osbourne/full-special

These get the following errors:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '--hls-prefer-native', '--cookies', 'cookies.txt', '--fragment-retries', '35', '--retries', '35', '--all-subs', '--sub-format', 'dfxp', 'https://play.aetv.com/specials/voices-magnified-locked-up-in-america/full-special']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.7.3 (CPython) - Linux-4.19.0-10-amd64-x86_64-with-debian-10.6
[debug] exe versions: ffmpeg 4.1.6-1, ffprobe 4.1.6-1, rtmpdump 2.4
[debug] Proxy map: {}
[aenetworks] voices-magnified-locked-up-in-america: Downloading webpage
WARNING: unable to extract videoId; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[aenetworks] Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/home/ymz/bin/youtube-dl/youtube_dl/extractor/common.py", line 632, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/ymz/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by kevinoconnor7** [comment]
Hmm yeah specials are weird. They don't have the video ID in the normal spot and the only place I can find it on the page is within a giant JSON blob. Unfortunately it's mixed in with others. I'll need to dig into the JSON a bit and compare a few samples to see if I can find a reliable way to find the correct one.

**Comment by yemaozitw** [comment]
If specials are too difficult then might as well go forward with this PR since it fixes most of the problem.

**Comment by rredford6** [comment]
@kevinoconnor7 Does the GraphQL server provide different playlists?  There's an issue with ads getting injected: #26047

**Comment by kevinoconnor7** [comment]
@rredford6 Not that I'm aware, though I'm honestly not super familiar with the entire The Platform flow. When I wrote this PR I mostly tried to extract the data that had previously been used (i.e. getting the public The Platform URL).

**Review by merval — APPROVED** [review]
Looks good! Nice work. Was able to successfully download an episode

**Pull request closed without merging**
