### PR TITLE
[YleAreena] Add new extractor

### PR DESCRIPTION
**Pull request by Hegezcc**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This pull request adds a new extractor for Yle Areena, Finnish Broadcasting Company internet service. There has been an unmerged extractor pull request for both Yle Areena and Yle Elävä Arkisto using the old Flash player technology, but that player has been completely phased out from Yle Areena and replaced with Kaltura streaming service. As the codebases of these services differ greatly now, this project's scope is limited to be in Yle Areena.

Ping @hlintala for making the old extractor. Maybe the Yle Elävä Arkisto extractor might be resurrected from your code.

### CODE REVIEW

**Comment by Hegezcc** [comment]
Looks like Yle is using aggressive geo-blocking which prevents tests in CI from passing. This is a major problem, as I cannot provide a really big proxy service for every downloader and also believe that the extractor's main userbase is in Finland, which would make the proxy pretty pointless.

How can this pull request proceed?

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by Hegezcc** [comment]
@dstftw could you elaborate more on what is wrong in this code regarding coding conventions?

**Comment by Hegezcc** [comment]
Bump.

**Comment by Hegezcc** [comment]
Bump. Anything still required here?

**Comment by hlintala** [comment]
Maybe something like

`player_url = url_or_none(self._og_search_property(['video:secure_url', 'video:url'], webpage))`

and not like

    try:
        player_url = url_or_none(
            self._og_search_property('video:secure_url', webpage)
        )
    except RegexNotFoundError:
            player_url = None

    # If this backup fails extractor will error out
    player_url = url_or_none(
        self._og_search_property('video:url', webpage)
    )

Also trailing parenthesis after last argument and not on a new line.

**Comment by subirax** [comment]
Bump.  Thanks!

**Comment by tpimh** [comment]
What's actually left to be done to merge this? I can provide a proxy service for CI to run if required.

**Pull request closed without merging**
