### PR TITLE
Added the ability to stop downloading of further videos when the first video is not in daterange

### PR DESCRIPTION
**Pull request by Mave95**
Added feature requested in #1502 

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by ghostyyyyy** [comment]
This seems very interesting when will this be merged to master? I'm in needed of this now.

**Comment by linuxtm** [comment]
Waiting for the merge with the master branch as well. This is a core feature :)

**Comment by infostatus** [comment]
Why is this still not merged? 7 months!
Have dozens of channel subscriptions, would be nice to download only the lastest videos. But some channels have hundreds of videos, it takes forever! 
Should stop at first dateafter.

**Comment by linuxtm** [comment]
> Why is this still not merged? 7 months!
> Have dozens of channel subscriptions, would be nice to download only the lastest videos. But some channels have hundreds of videos, it takes forever!
> Should stop at first dateafter.

I think that's because there is a way around it, by using something like this:
 --dateafter now-1day (this will check for videos in the last 24h)
 --playlist-end 10 (this will stop after checking last 10 videos from the channel)

**Comment by omeringen** [comment]
> 
> 
> > Why is this still not merged? 7 months!
> > Have dozens of channel subscriptions, would be nice to download only the lastest videos. But some channels have hundreds of videos, it takes forever!
> > Should stop at first dateafter.
> 
> I think that's because there is a way around it, by using something like this:
> --dateafter now-1day (this will check for videos in the last 24h)
> --playlist-end 10 (this will stop after checking last 10 videos from the channel)

_dateafter blabla_ will check all videos one by one, so it's not a workaround.
_--playlist-end_ is not a solution for the users who don't want to manually check their big subscription list.

**Comment by omeringen** [comment]
@dstftw ,
Could you tell us about why this is not merged please ?

**Comment by omeringen** [comment]
It is still marked as "do not merge". :(

**Comment by playma** [comment]
Please merge this feature!!!!

**Comment by lwilletts** [comment]
Really need this feature in the mainline. I thought this would be the intended behaviour when first trying out the --date and variants.

**Comment by synoxat** [comment]
Why is this feature still not merged??????

**Pull request closed without merging**
