### PR TITLE
Thumbnail Embedding support for OGGVorbis, OGGOpus and FLAC files

### PR DESCRIPTION
**Pull request by tripulse**
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### Purpose of this *pull request*
- [x] New feature

---

"Thumbnail Embedding" was limited under mp4/m4a and mp3 (ID3v2/APE) formats. Ticket #22338 requests support for embedding thumbnails into OGGOpus files. And me, myself wanted this feature, but no one seemed to fulfil need so I did it.

Requires [`mutagen`][1] as a dependency to embed thumbnails. It raises a `EmbedThumbnailPPError` if not found (eg. the `AtomicParsley` code block does so). Despite, it’s bad reputation in youtube-dl community of doing inplace modification, it’s integrated in such a way that it doesn’t do that.

> Most of times [`mutagen`][1] is installed from PyPI, like this:
> ```bash
> pip install mutagen
> pip3 install mutagen
>
> # if administrative privileges aren't available
> pip install mutagen --user
> pip3 install mutagen --user
> ```
> Note that, `pip3` is used if `pip` isn't available.

[1]: https://github.com/quodlibet/mutagen

### CODE REVIEW

**Comment by tryamid** [comment]
10 days passed, still no replies nor submission. Are the maintainers slow?

**Comment by SRugina** [comment]
Hi, I'm just a user that wants to try this feature out early, but I haven't been able to get it to work. I've done `pip3 install mutagen`, then cloned this repository and ran `make install` in its directory.

However, downloading a video with this leads to `ERROR: mutagen was not found. Please install.`. I checked in python3's interpreter and 'import mutagen' leads to no errors, so I assume it is installed correctly. I wonder why this error is occuring?

**Comment by ajdedo** [comment]
I look forward to this feature. Thanks.

**Comment by tripulse** [comment]
Okay, so will you merge it?

**Comment by sqliuchang** [comment]
It works! Thank you!

**Comment by AVHon** [comment]
Uninstalled the copy of youtube-dl I had, cloned the repo, switched to a new branch, and patched this change in. Works a treat, thanks!

**Comment by L33Tech** [comment]
Can this please get merged?

**Comment by ciarancourtney** [comment]
@tripulse 's repo was taken down during dmca-gate, so maybe the maintainers can't merge until a new PR is done?

**Comment by tripulse** [comment]
> @tripulse 's repo was taken down during dmca-gate, so maybe the maintainers can't merge until a new PR is done?

Shouldn't be something of problem, changes can be reliably patched in.

**Comment by Thomasedv** [comment]
@tripulse Not that I'm knowledgeable, but since github is saying there is some merge conflict, is that something you are able to fix. While this thing is nearing up on a year old in ~1.5 months, I'd hate to see some maintainer skip over it because it requires more effort than just accepting the pull request.

**Comment by tripulse** [comment]
> @tripulse Not that I'm knowledgeable, but since github is saying there is some merge conflict, is that something you are able to fix. While this thing is nearing up on a year old in ~1.5 months, I'd hate to see some maintainer skip over it because it requires more effort than just accepting the pull request.

Tried to do that, but Github said `This page is out of date. Start over`. Does it mean I am not privileged?

**Comment by Thomasedv** [comment]
> @Thomasedv Tried to do that, but Github said `This page is out of date. Start over`. Does it mean I am not privileged?

Sadly, I don't know enough about Github/git to answer that.

**Comment by tripulse** [comment]
Perhaps I should make another PR, since this isn’t getting noticed.

**Comment by Aankhen** [comment]
That seems inadvisable.

This would be great to have, but the PR can’t be merged because of a conflict. Meanwhile, your repository is inaccessible due to the DMCA claim, both from the web and through Git, so I don’t think anyone else can pull it to fix it. (I tried.) I don’t think it’ll be possible to merge anything at all from your repository until that’s resolved.

**Comment by tripulse** [comment]
This pull request has been re-filed #28894.

**Comment by xsbee** [comment]
The owners really should archive this project.

**Comment by 89z** [comment]
Since its not been mentioned yet, I will. Even if this is implemented, Windows does not support this. Even outside the context of YouTube-DL, Windows does not support thumbnail for Opus files.

**Comment by xsbee** [comment]
> Since its not been mentioned yet, I will. Even if this is implemented, Windows does not support this. Even outside the context of YouTube-DL, Windows does not support thumbnail for Opus files.

That's a windows specific issue.

**Comment by 89z** [comment]
> That's a windows specific issue.

@xsbee yes obviously. However as YouTube-DL supports Windows, any PR that doesnt support Windows should document that fact.

**Comment by leetfin** [comment]
I want the feature even if it doesn't display properly. -Windows user

**Comment by xsbee** [comment]
I can see people leaving for yt-dlp because of the huge amount of pending pull requests.

**Pull request closed without merging**
