### PR TITLE
url_transparent and playlists? /NOT FOR MERGE

### PR DESCRIPTION
**Pull request by jtrmal**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [] Improvement
- [] New extractor
- [] New feature

---

### Description of your *pull request* and other information

Hi, I'm not sure how the url_transparent should interact with playlists w.r.t. overriding the fields. What I've found that for the playlist entries, the fields are not overriden, because, the information fields to be overriden are actually one level deeper (at least in the case of this given extractor). I'm attaching  a code that "fixes" it, i.e. documents what I had to change -- there might be other, correct/prefered, way how to do that correctly.

### CODE REVIEW

**Comment by dstftw** [comment]
Entries are not supposed to be overridden. It must only override metadata at the same level.

**Comment by jtrmal** [comment]
Thanks for the response. In that case, I'm not sure how to provide the date
for the playlist entries from the top page, though... If it's even possible.
y.

**Comment by dstftw** [comment]
You are not supposed to. Playlist metadata has nothing to do with entries' metadata.

**Comment by jtrmal** [comment]
Thank you.
y.

**Pull request closed without merging**
