### PR TITLE
[allmovie] Add new extractor

### PR DESCRIPTION
**Pull request by idlesign**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Extractor for site providing TV show recordings primarily in Russian.

### CODE REVIEW

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Do they have rights to distribute this? If not provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by idlesign** [comment]
I can't find there any copyright owning notes. But they have this call to copyright owners: http://allmovie.tv/pages/copyrights.html (they tell they provide special tools for copyright owners), just as youtube, rutube, myvi, ok.ru, vk.com, ruhd, and others extractors for which are provided. This site positions itself as video hosting, and as far as I can judge, they do allow uploading arbitrary videos (e.g. http://allmovie.tv/video/s-dnem-rozhdenija-sergei-17580.html).

**Comment by idlesign** [comment]
@rg3 Hi, what's the status of this?

**Comment by rg3** [comment]
@dstftw is the current head of maintainers, so I'm deferring the question. :-)

**Comment by dstftw** [comment]
No longer available.

**Pull request closed without merging**
