### PR TITLE
[niconico] Support encrypted official videos (fix #24093)

### LINKED ISSUE #24093: [niconico] Support encrypted official videos
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I did a pull requests (https://github.com/ytdl-org/youtube-dl/pull/23824) before, but I'll post it to the issue just in case.

niconico (Nico Nico Douga) is not known outside of Japan, but is the largest video sharing site in Japan.

### Problem

niconico began using HLS to encrypt the distribution of some official videos, such as anime, on March 5, 2019.
As a result, some official videos can no longer be downloaded with the previously used Extractor.
(Example of video that can be downloaded as before: https://www.nicovideo.jp/watch/sm32868846)
(Example of video that cannot be downloaded due to HLS encryption: https://www.nicovideo.jp/watch/so36189921)

### Correction and resolution

The pull requests I mentioned earlier include an improvement that allows you to download niconico's encrypted HLS videos.
Specifically, it has been modified to make a request to the (most recently published) Ping API (otherwise the download will fail).
In addition, the encrypted HLS video has been modified to send different parameters to the API for acquiring the viewing session than the HTTP video.

On niconico, if you do not send a "heartbeat" every 60 seconds, the download session will be closed and a 403 error will occur.
Short videos can complete the download before the session closes, but long videos do not.
You can "resume" videos that support HTTP, but you can't resume videos that are HLS only.
Therefore, it is necessary to implement a "heartbeat".

The pull requests also include a change that allows you to send a "heartbeat" once every 60 seconds during the download, and to download long videos to the end.
I understand that although some pull requests implementing "heartbeat" have been sent in the past, such as https://github.com/ytdl-org/youtube-dl/issues/14582, they have not been merged even now doing.
The code for "heartbeat" is based on https://github.com/archiif/youtube-dl/pull/1/commits/84995347fccc12f588efe59540418b9070a3c177.
I tried it on various video sites, but adding this feature will not hinder other sites from downloading.
Also, since February 2018, it has been improved to play videos without logging in, so you do not need an account to download.

### lastly

As a side change, we made changes to get high quality thumbnails and original titles.
In addition, support for "heartbeat" has made it easier to download normal niconico HTTP videos (especially long videos) as a side effect, eliminating the need to "resume".

I strongly hope that this change will be incorporated into the project.
Can you merge this (https://github.com/ytdl-org/youtube-dl/pull/23824) Pull requests?

Thank you.

(Sentence may be a bit strange because I am using translation)

### PR DESCRIPTION
**Pull request by tsukumijima**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

niconico (ニコニコ動画), which is not known outside Japan, is the largest video sharing site in Japan.

niconico has begun using HLS to encrypt the distribution of some official videos, such as anime, on March 5, 2019.
As a result, some official videos can no longer be downloaded with the previously used Extractor.
(Examples of videos that can be downloaded as before: https://www.nicovideo.jp/watch/sm32868846
(Example of video that cannot be downloaded due to HLS encryption: https://www.nicovideo.jp/watch/so36189921)

This pull request includes an improvement to allow you to download niconico's encrypted HLS videos.

In niconico, if you do not send "heartbeat" once every 60 seconds, the download session will be closed and you will get a 403 error.
This pull request also includes a change to allow "heartbeat" to be sent once every 60 seconds during the download, and to allow long videos to be downloaded to the end.

We have also made changes so that you can obtain higher quality thumbnails and original titles.
(Sentence may be a bit strange because we use translation)

### CODE REVIEW

**Comment by yan12125** [comment]
Thanks for the patch. However, as I've mentioned in https://github.com/ytdl-org/youtube-dl/issues/14582#issuecomment-554597115, I'm no longer working on youtube-dl.

**Comment by tsukumijima** [comment]
@yan12125
OK. Thank you for your reply!

**Comment by CXwudi** [comment]
would be really happy to see this merged, the heartbeat issue is really frustrating.

**Comment by tsukumijima** [comment]
@CXwudi
Thank you very much.  However, a few months after sending this request, my request has not yet been merged into youtube-dl.

**Comment by tsukumijima** [comment]
@CXwudi
Thank you very much. 
However, a few months after sending this request, my request has not yet been merged into youtube-dl.

**Comment by tsukumijima** [comment]
@CXwudi
Thank you very much. 
However, a few months after sending this request, my request has not yet been merged into youtube-dl.

**Comment by CXwudi** [comment]
> @CXwudi
> Thank you very much. However, a few months after sending this request, my request has not yet been merged into youtube-dl.

Hi tsukumijima, I have tried your solution about the heartbeat, it works pretty well, thanks for the fix again. but since they are not responding to this PR, may I create a folk of your folk for myself?

**Comment by tsukumijima** [comment]
> > @CXwudi
> > Thank you very much. However, a few months after sending this request, my request has not yet been merged into youtube-dl.
> 
> Hi tsukumijima, I have tried your solution about the heartbeat, it works pretty well, thanks for the fix again. but since they are not responding to this PR, may I create a folk of your folk for myself?

OK.
This pull request will probably never be merged again, so you're welcome to make your own pull requests.
However, in order to implement "Heart Beat", you need to make changes to the youtube-dl's Core (other than extension), so I'm sure that if you make a pull request like I did, it will be ignored.
I'm hoping that this change will be merged in some way, but it's a shame because there are so many pull requests that remain open and are ignored without a reply.
I'm Japanese and I use translation. There may be some unnatural areas.

**Comment by CXwudi** [comment]
the update of this PR is maintained here -> https://github.com/tsukumijima/yt-dl

**Pull request closed without merging**
