### PR TITLE
[Veeps] add extractor

### PR DESCRIPTION
**Pull request by dunnousername**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

See issue #25728 
This pull request adds an extractor for veeps.com. veeps.com hosts concert streams in which users can buy tickets and later replay the stream on the website. This extractor handles authentication (via the `--username` and `--password` options) and downloading of streams when the user has purchased tickets. Because this extractor requires authentication and payment, there are currently no test cases written; however, I have tested it and the extractor correctly lists viewable formats and is able to download them and create a viewable stream. For details on how the testing was done, see the attached issue.
URL format that this extractor accepts is `https://[channel].veeps.com/stream/[id]`.

Here's a log from a test:
```
$ python3 -m youtube_dl --username [user's email] --password [user's password] https://brandicarlile.veeps.com/stream/e5ccef3d7eba -F
[Veeps] obtaining initial session
[Veeps] logging in
[Veeps] e5ccef3d7eba: downloading stream page
[Veeps] e5ccef3d7eba: Downloading m3u8 information
[info] Available formats for e5ccef3d7eba:
format code  extension  resolution note
2516         mp4        1280x720   2516k , avc1.640020, mp4a.40.2
1640         mp4        960x540    1640k , avc1.640020, mp4a.40.2
994          mp4        640x360     994k , avc1.64001f, mp4a.40.2
697          mp4        480x270     697k , avc1.64001e, mp4a.40.2 (best)
```
It will download the format specified and concatenate the stream's .ts files, saving a playable .mp4 file.

### CODE REVIEW

**Comment by dstftw** [comment]
1. You must provide account credentials for review.
2. Read coding conventions.

**Comment by gotno** [comment]
@dunnousername THANK YOU for this. i was able to install by modifying an archlinux AUR packagebuild and pointing it to your repo/branch instead. worked great for the two shows on veeps i just tried! looking forward to seeing this in master.

**Comment by fnordpojk** [comment]
I can confirm this code works fine on release 2021.03.14 of youtube-dl.

If I can assist in privately providing an account to test with, @dstftw, please let me know.

Is the only thing stopping the merge that the tests do not pass, or is there anything else from the coding conventions that is missing?

**Comment by luciensadi** [comment]
Confirmed this code works fine for me as well on OS X on 2021.03.14. The only possible issue is the default selection of a lower resolution than maximum, but that can be worked around with `-F` and `-f` (for me, 4755 was the 1080p version). Looking forward to this being added to master.

**Comment by barsnick** [comment]
Hey @dunnousername, your repo disappeared with the DCMA takedowns. Would you care to put it back up?

I'd give my own shot at implementing this, but since you already has successful pre-work, I'd rather use that. :)

**Comment by dunnousername** [comment]
> 
> 
> Hey @dunnousername, your repo disappeared with the DCMA takedowns. Would you care to put it back up?
> 
> I'd give my own shot at implementing this, but since you already has successful pre-work, I'd rather use that. :)

It's still *sort of* up. When the whole thing happened, I think my veeps repo also got taken down, but I forked a different version of `youtube-dl` (without veeps). Apparently the repo I forked from still has a DMCA in effect, and so I actually can't even delete the repo at dunnousername/youtube-dl and put something else there without contacting GitHub with a counternotice. This is because the repo I forked from when all that happened wasn't from the initial DMCA. Here's what it looks like here:
image

My git diffs seem to still be in the "Files Changed" tab, though, as well as [here](https://github.com/ytdl-org/youtube-dl/tree/d46b850f96660fc22e055e737b5e22f17af1c6c9), for some reason.

**Comment by barsnick** [comment]
Ah, I recall, the DMCA takedowns left the actual objects intact. That's why [your commit](https://github.com/ytdl-org/youtube-dl/commit/d46b850f96660fc22e055e737b5e22f17af1c6c9) can still be seen, and possibly, your pull request is still active, but the tree cannot be browsed.
I have the same issue of not being able to revive my fork, and my new fork got a different name. *sigh*

Anyway, I am testing your changes now - thanks for pointing out their location! I am tripping across an
```
AttributeError: 'VeepsIE' object has no attribute '_NETRC_MACHINE'
```
backtrace. I'll look at whether I can get it to work in the first place (my Veeps link is only valid for a few more days). and then whether the code style remarks can be resolved.

**Comment by fnordpojk** [comment]
Unfortunately, Veeps have now changed their URL structure, and this extractor no longer works..

**Comment by githubmarker** [comment]
Here's another URL that also uses mux. 

It is a freely available conference stream and does not require any authentication.
https://aws.events.cube365.net/startup/showcase-q3

**Pull request closed without merging**
