### PR TITLE
[mediaklikk] Add new extractor

### LINKED ISSUE #21431: Support for MédiaKlikk (HU)
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2019.06.08**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://www.mediaklikk.hu/video/izorzok-toalmas/
- Single video: https://www.mediaklikk.hu/video/honfoglalo-2019-06-03-i-adas/
- Single video: https://www.mediaklikk.hu/video/eletkerek-2019-04-19-i-adas/
- Playlist/show page: https://www.mediaklikk.hu/musor/izorzok/

## Description

MédiaKlikk is the free VOD video platform of MTVA.
MTVA (Media Services and Support Trust Fund) is Hungary's state-owned national public-service broadcasting organization, and it's the successor of MTV (state television service) and MR (state radio service).
The programs are available without a registration, and I don't know if the site uses georestriction.

### PR DESCRIPTION
**Pull request by mrx23dot**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Added extractor for this site: https://mediaklikk.hu/video/kiberma-2020-04-30-i-adas/

fixes #21431

### CODE REVIEW

**Comment by asalamon74** [comment]
I tested it, I successfully downloaded videos from m4sport.hu.

I had to modify only one line:

```
_VALID_URL = r'https?://(?:www\.)?(?:mediaklikk|m4sport)\.hu/videok?/(?P<id>[^/]+)/?'
```

**Comment by mrx23dot** [comment]
They keep on changing the URL :/

**Comment by mrx23dot** [comment]
Added m4sport support, what do I need to do with this pull request to get processed?

**Comment by pizzasok** [comment]
I also tested it, and I successfully downloaded videos from [hirado.hu](https://hirado.hu/rendkivuli/video/2020/09/19/az-operativ-torzs-sajtotajekoztatoja-a-legfrissebb-intezkedesekrol-2020-szeptember-19/) as well.

Like asalamon74 I had to modify only one line: 

   _VALID_URL = r'https?://(?:www\.)?(?:mediaklikk|m4sport|hirado)\.hu(?:/videok|/rendkivuli/video)?/(?P<id>[^/]+)/?'

**Comment by pizzasok** [comment]
Also note that the [video that is listed](https://mediaklikk.hu/video/kiberma-2020-04-30-i-adas/) in the pull request description, and is included in mediaklikk.py as test, is no longer available. I suggest updating these to a video that is likely to be more permanently present on the site, e.g. :

[https://mediaklikk.hu/adal2020/video/2020/03/07/a-dal-donto/](https://mediaklikk.hu/adal2020/video/2020/03/07/a-dal-donto/)

**Comment by pizzasok** [comment]
Thank you for including the hirado.hu fix! I created a pull request with a few minor additional edits, please accept if you agree with them. Also please update in the description of your pull request the link from https://mediaklikk.hu/video/kiberma-2020-04-30-i-adas/ to https://mediaklikk.hu/adal2020/video/2020/03/07/a-dal-donto/

**Comment by VinhoXie** [comment]
Thank you for including the hirado.hu fix! I recently found an article offering solutions to [download video from mediaklikk](https://enjoy-online-audio-video-movie.blogspot.com/2021/05/top-3-downloaders-for-mediaklikk.html) too.

**Pull request closed without merging**
