### PR TITLE
[verystream] Add new extractor (is just a copy of Openload with little changes)

### PR DESCRIPTION
**Pull request by etmatrix**
### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [X ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
It's just a copy of Openload with some adjustment for new site.

### CODE REVIEW

**Comment by etmatrix** [comment]
for issue #20701

**Comment by ealgase** [comment]
Hey @remitamine, can you please take a look at this?

**Comment by remitamine** [comment]
obviously, duplicating the whole extractor just because the two websites differ slightly in the URLs is not acceptable.

**Comment by ealgase** [comment]
Ah, so verystream should be added to the openload extractor?

**Comment by ealgase** [comment]
I've now added support for verystream.com to the openload extractor (#20967).

**Pull request closed without merging**
