### PR TITLE
[pornhub] Fix PC page video extraction

### PR DESCRIPTION
**Pull request by ajj8**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

PornHub extractor can't find video URLs with the PC extractor and the TV page only offers up to 720p, so I moved the pre-existing code for TV pages which parses jsvars into a new function, added a new regex for PC and assign the qualities their video URL from the jsvars.

### CODE REVIEW

**Comment by ajj8** [comment]
> Fails on some videos, such as: https://www.pornhub.com/view_video.php?viewkey=ph5dbff237df1fe

Fixed in https://github.com/ytdl-org/youtube-dl/pull/23082/commits/c004bcf78d5f97ba84de2b703bfc678cf68465f6, I didn't take into account qualities higher than 1080p for free

**Comment by github-userx** [comment]
Thanks so much for doing this @ajj8 

Have You also already looked in why some model pages get an error and only can be downloaded by using this old url: pornhub.com/model/modelname/videos/upload

Apparently it’s because these use the new model page layout of pornhub.

**Comment by github-userx** [comment]
Does this not get pulled ?

**Comment by Alcatraz31337** [comment]
Any news on whether this gets pulled?

**Comment by github-userx** [comment]
Why is this not getting pulled for weeks and weeks?

**Comment by github-userx** [comment]
@ajj8 Do You have Any idea why this is not getting pulled? Just a couple days ago a new YouTube-dl version has been released as well. Again without your pull request.

**Comment by ajj8** [comment]
> @ajj8 Do You have Any idea why this is not getting pulled? Just a couple days ago a new YouTube-dl version has been released as well. Again without your pull request.

Absolutely no clue! I have another pull request which has no response for weeks either.

**Comment by ajj8** [comment]
In the meantime if you're on windows you can replace pornhub.py in
`%LOCALAPPDATA%\Programs\Python\Python38\Lib\site-packages\youtube_dl\extractor`
with https://raw.githubusercontent.com/ytdl-org/youtube-dl/c004bcf78d5f97ba84de2b703bfc678cf68465f6/youtube_dl/extractor/pornhub.py

**Comment by github-userx** [comment]
Thanks! Yeah I already just replaced the extractor file

**Comment by Kattus** [comment]
In the meantime I've merged the two commits (also perhaps that is part of a reason?) and made it into a .patch to apply before building a custom version of youtube-dl, would be nice to be able to use upstream though. But again and again youtube-dl proves to be incompetent.

**Pull request closed without merging**
