### PR TITLE
[Aparat] Fix extractor

### PR DESCRIPTION
**Pull request by HanifBirgani**
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Fix the extractor.

Fix issues: #23348 #24252 #22285

### CODE REVIEW

**Comment by amkyp** [comment]
I figuring about Aparat extractor problem, and just searching through issues, what I first found was the code below.
https://github.com/ytdl-org/youtube-dl/commit/70851a95c307880f016fcb6f37427a8eeae73cad

but after searching more, I found out that you the person who had more recently worked on Aparat.

So the problem is I can't extract any sort of video/audio, playlist, .... from Aparat, And I encounter to an error.
`[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.aparat.com/v/dtx2E', u'--verbose']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.05.03
[debug] Python version 2.7.17 (CPython) - Linux-5.3.0-51-generic-x86_64-with-Ubuntu-19.10-eoan
[debug] exe versions: ffmpeg 4.1.4-1build2, ffprobe 4.1.4-1build2, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[Aparat] dtx2E: Downloading webpage
ERROR: Unable to extract options; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/aparat.py", line 52, in _real_extract
    webpage, 'options', group='value'),
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract options; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by HanifBirgani** [comment]
Have you tried my fix for Aparat in [this branch](https://github.com/HanifBirgani/youtube-dl/tree/fix/aparat)?

**Comment by amkyp** [comment]
No, Actually I didn't know that your project wasn't a branch in your account.
I thought you have done a PR for the main project.
Was there a reason you didn't make a PR?

**Comment by amkyp** [comment]
@HanifBirgani 
I found that you have to use this template for broken site.
Could you check this till it will be available to use in master branch?
https://github.com/ytdl-org/youtube-dl/blob/b002bc433a0ba151b7c2f42ab6f1db9a27ed1ecd/.github/ISSUE_TEMPLATE/1_broken_site.md

**Comment by HanifBirgani** [comment]
> No, Actually I didn't know that the fix you've done was a branch in your account.
> I thought you have done a PR for the main project.
> Was there a reason you didn't make a PR?

You are commenting on the PR dude :)

**Comment by amkyp** [comment]
> You are commenting on the PR dude :)

Sorry, yeah I understood the thing I've done but there is still a question:
Why your change didn't merge into the master branch?

Aparat extractor is working in your fork but not in the current release of `youtube-dl`.
@dstftw

**Comment by HanifBirgani** [comment]
> Why your change didn't merge into the master branch?
I don't know, I made this PR about two months ago.

**Comment by HanifBirgani** [comment]
@dstftw Would you please review this pull request?

**Comment by amnkh** [comment]
Thanks for the patch @HanifBirgani 
I applied it manually on macOS youtube-dl installed via pip and it works like a charm.

```
(venv) > $ youtube-dl -v https://www.aparat.com/v/TB1JC
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.aparat.com/v/TB1JC']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2020.06.06
[debug] Python version 3.7.4 (CPython) - Darwin-18.7.0-x86_64-i386-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[Aparat] TB1JC: Downloading webpage
[Aparat] TB1JC: Downloading m3u8 information
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://as11.cdn.asset.aparat.com/aparat-video/9a2e2ade9cddb78dfbd2561c2674639823114720-1080p.apt/chunk.m3u8?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6ImM4ZDdhZGEzMzUzMmZiMmU0NjUzMTY5ZGIxYTA1YzlmIiwiZXhwIjoxNTkyMjQ2NjIzLCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.VzRBtf-YQ6ebM0fe2-tNdhcea7QFoIl4h4TTKIFTL3U'
[download] پدر و مادر نمی دونستن دخترشون عاشق فوتباله!  -)-TB1JC.mp4 has already been downloaded
[download] 100% of 20.20MiB
WARNING: TB1JC: malformed AAC bitstream detected. Install ffmpeg or avconv to fix this automatically.
```

image

**Comment by Dullaz** [comment]
Seems this PR will fix #26738

**Pull request closed without merging**
