### PR TITLE
Code Formatted and Re-structured

### PR DESCRIPTION
**Pull request by dhhruv**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Code Formatted and Re-structured for better visibility and to easily understand the code. 
Some of the code lines were messy so I formatted them as many of my colleagues find it difficult to understand as well.

### CODE REVIEW

**Comment by rautamiekka** [comment]
Seems like you didn't notice the project has always used (enforced, might be closer to it) single quotes even when there's a single quote inside the string. Personally I agree with you on that front, but that change probly doesn't get through.

**Comment by dirkf** [comment]
If there is meant to be a layout style (and there is) the style should be applied automatically (with some sort of pragma to override it).

I can't see any benefit to changing syntactically correct quote usage.

**Comment by dhhruv** [comment]
> If there is meant to be a layout style (and there is) the style should be applied automatically (with some sort of pragma to override it).
> 
> I can't see any benefit to changing syntactically correct quote usage.

Just tried. Will close if not found useful enough.

**Comment by dhhruv** [comment]
> Seems like you didn't notice the project has always used (enforced, might be closer to it) single quotes even when there's a single quote inside the string. Personally I agree with you on that front, but that change probly doesn't get through.

Agree.

**Pull request closed without merging**
