### PR TITLE
New regex pattern for extractor/youtube.py function name finder

### PR DESCRIPTION
**Pull request by alistairboyer**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [N/A] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

I was getting the following regex error:
  youtube_dl.utils.RegexNotFoundError

Looking at the raw JS in jscode it seems that the script is trying to find the "sL" bit: [this obviously changes each time]
...yt.akamaized.net/)||d.set("alr","yes");c&&d.set(b,(0,window.encodeURIComponent)(sL((0,window.decodeURIComponent)(c))));return d};

But it failed to match the original regex (line 1194) because of the additional '(0,window.encodeURIComponent)(' part

This new regex (added on line 1195) fixes the problem and it works for me! 

I find it really hard to force youtube-dl go via the _parse_sig_js function to test. But I have reproduced the error at least four times and confirmed the new regex solves the problem.

### CODE REVIEW

**Comment by goggle** [comment]
Can you provide an example to reproduce this error?

**Comment by alistairboyer** [comment]
A ha! I couldn't get it to reproduce because I wasn't using the "--no-cache-dir" flag.
Now I can get the same problem every time.

Try this video: oCLsa98D7iU
I obviously downloaded and deleted it straight away for research purposes.

**Comment by alistairboyer** [comment]
ALSO!!! 
I just noticed that the two regexes below my edit have had the exact same fix!!!!
             r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*(?P<sig>[a-zA-Z0-9$]+)\(',
             r'\bc\s*&&\s*d\.set\([^,]+\s*,\s*\([^)]*\)\s*\(\s*(?P<sig>[a-zA-Z0-9$]+)\('),

**Comment by goggle** [comment]
Ok thanks, I could reproduce this. I've opened an issue for this matter: #18297

**Comment by gargolito** [comment]
I couldn't find how to subit an issues so here it goes, some youtube playlist are failing _search_regex, here's the verbose output
`youtube-dl --verbose 'https://www.youtube.com/watch?v=YTmZtDQvYvg&list=PLVXq77mXV53-Np39jM456si2PeTrEm9Mj'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=YTmZtDQvYvg&list=PLVXq77mXV53-Np39jM456si2PeTrEm9Mj']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.0 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLVXq77mXV53-Np39jM456si2PeTrEm9Mj - add --no-playlist to just download video YTmZtDQvYvg
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading webpage
[download] Downloading playlist: Top Tracks - Classical Music
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #1
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #2
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #3
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #4
[youtube:playlist] playlist Top Tracks - Classical Music: Downloading 500 videos
[download] Downloading video 1 of 500
[youtube] YTmZtDQvYvg: Downloading webpage
[youtube] YTmZtDQvYvg: Downloading video info webpage
[youtube] {18} signature length 104, html5 player vfl49f_g4
[youtube] YTmZtDQvYvg: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl49f_g4/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1986, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1352, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "/Users/acamilo16/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`

**Comment by gargolito** [comment]
I couldn't find how to submit an issues so here it goes, some youtube playlist are failing with **youtube_dl.utils.RegexNotFoundError**, here's the verbose output
```
youtube-dl --verbose 'https://www.youtube.com/watch?v=YTmZtDQvYvg&list=PLVXq77mXV53-Np39jM456si2PeTrEm9Mj'
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/watch?v=YTmZtDQvYvg&list=PLVXq77mXV53-Np39jM456si2PeTrEm9Mj']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 3.7.0 (CPython) - Darwin-18.6.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.2, ffprobe 4.1.2, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:playlist] Downloading playlist PLVXq77mXV53-Np39jM456si2PeTrEm9Mj - add --no-playlist to just download video YTmZtDQvYvg
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading webpage
[download] Downloading playlist: Top Tracks - Classical Music
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #1
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #2
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #3
[youtube:playlist] PLVXq77mXV53-Np39jM456si2PeTrEm9Mj: Downloading page #4
[youtube:playlist] playlist Top Tracks - Classical Music: Downloading 500 videos
[download] Downloading video 1 of 500
[youtube] YTmZtDQvYvg: Downloading webpage
[youtube] YTmZtDQvYvg: Downloading video info webpage
[youtube] {18} signature length 104, html5 player vfl49f_g4
[youtube] YTmZtDQvYvg: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl49f_g4/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1986, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1352, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
youtube_dl.utils.ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1342, in _decrypt_signature
    video_id, player_url, s
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1250, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/youtube.py", line 1314, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Pull request closed without merging**
