### PR TITLE
[PornHub] Add support for non-verified pornstar video collections (fixes issue #16078)

### PR DESCRIPTION
**Pull request by parmjitv**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

Updated the extractor for Pornhub.com to also provide support for non-verified pornstar videos as playlists - issue #16078.

Cheers and thank you!

Parmjit V.

### CODE REVIEW

**Comment by parmjitv** [comment]
@dstftw - Good catch!  Looks like the itertools loop spins indefinitely when a paginator is not present in the page source, the latest commit should fix that.

**Comment by parmjitv** [comment]
@dstftw - Would it be possible to have a second review of this PR?  I believe the revised fix for this issue is pretty straightforward.  Much appreciated!

**Comment by parmjitv** [comment]
@dstftw - Are any collaborators available for a second review?  I believe this PR would be a very useful improvement, as there are still quite a few non-verified pornstar profiles active on the Pornhub website.  Thank you!

**Comment by parmjitv** [comment]
@remitamine @yan12125 Would it be possible to have a second review of this PR?  I believe this to be a useful fix as users are still having difficulty when trying to fetch playlists of videos - see issue #17936 for example.  Many thanks in advance!

**Comment by github-userx** [comment]
@parmjitv Any update on this? After all these months the pornhub user videos downloader from ytdl still doesn’t work..?

**Comment by github-userx** [comment]
@dstftw Any update on the pornhub user videos extractor/downloader?

**Comment by parmjitv** [comment]
@github-userx - The collaborators did not provide any further feedback for this PR.  Unfortunate, as it would have resolved a number of open issues.

**Comment by parmjitv** [comment]
@github-userx - Due to some recent changes on the PH website, this pull request requires some additional work for pagination.  It seems unlikely this PR will be reviewed further by the collaborators so I am not going to bother with updating - please feel free to pick this up yourself if you like.

Cheers,

Parmjit V.

**Comment by relgisri** [comment]
fucking merge this now...

**Pull request closed without merging**
