### PR TITLE
Fix Kakao Extractor

### PR DESCRIPTION
**Pull request by wagwan-piffting-blud**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Kakao has changed their API to return `null` for `clipChapterThumbnailList`, this change comments out the thumbnail extractor to fix the issue.

### CODE REVIEW

**Comment by zackmark29** [comment]
Why I'm getting this error?
C:\Users\MARK>youtube-dl -F https://tv.kakao.com/channel/3643855/cliplink/412069491
[Kakao] 412069491: Downloading video info
[Kakao] 412069491: Downloading video URL for profile LOW
[Kakao] 412069491: Downloading video URL for profile BASE
[Kakao] 412069491: Downloading video URL for profile MAIN
[Kakao] 412069491: Downloading video URL for profile HIGH
[Kakao] 412069491: Downloading video URL for profile HIGH4
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\__init__.py", line 474, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\__init__.py", line 464, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 2019, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpq2whuxta\build\youtube_dl\extractor\kakao.py", line 120, in _real_extract
TypeError: 'NoneType' object is not iterable

**Comment by wagwan-piffting-blud** [comment]
@zackmark29 That was the error I was getting on the old version of the file, try the new one linked in the commit. I tested with the one in the commit and it works fine.

**Comment by zackmark29** [comment]
> @zackmark29 That was the error I was getting on the old version of the file, try the new one linked in the commit. I tested with the one in the commit and it works fine.

Alright. thanks

**Comment by zackmark29** [comment]
> @zackmark29 That was the error I was getting on the old version of the file, try the new one linked in the commit. I tested with the one in the commit and it works fine.

Do you have compiled exe version?

**Comment by wagwan-piffting-blud** [comment]
> > @zackmark29 That was the error I was getting on the old version of the file, try the new one linked in the commit. I tested with the one in the commit and it works fine.
> 
> Do you have compiled exe version?

I do not, however you can run `python __main__.py https://tv.kakao.com/channel/3643855/cliplink/412069491` from your CLI and it should begin downloading then.

**Comment by zackmark29** [comment]
> > > @zackmark29 That was the error I was getting on the old version of the file, try the new one linked in the commit. I tested with the one in the commit and it works fine.
> > 
> > 
> > Do you have compiled exe version?
> 
> I do not, however you can run `python __main__.py https://tv.kakao.com/channel/3643855/cliplink/412069491` from your CLI and it should begin downloading then.

Ah alright. I'll try.

**Comment by zackmark29** [comment]
Still the same error. I already updated the kakao.py with your updated code.

**Comment by wagwan-piffting-blud** [comment]
> Still the same error. I already updated the kakao.py with your updated code.

That is strange... not sure what would be causing the error then as the affected code is commented out, and I was able to download the video fine on my end. Can you paste the error you got this time (even if it is the same as before)? I would also suggest double-checking to make sure the file is [exactly matching what is shown here (especially around line 120 where the change is)](https://github.com/ytdl-org/youtube-dl/blob/836f8042568defd8f1530c0eba007a6fc37cc13b/youtube_dl/extractor/kakao.py).

**Comment by zackmark29** [comment]
> > Still the same error. I already updated the kakao.py with your updated code.
> 
> That is strange... not sure what would be causing the error then as the affected code is commented out, and I was able to download the video fine on my end. Can you paste the error you got this time (even if it is the same as before)? I would also suggest double-checking to make sure the file is [exactly matching what is shown here (especially around line 120 where the change is)](https://github.com/ytdl-org/youtube-dl/blob/836f8042568defd8f1530c0eba007a6fc37cc13b/youtube_dl/extractor/kakao.py).

Thank you it's now working.
I forgot to comment the 'thumbnails': thumbs, from line 139

**Comment by wagwan-piffting-blud** [comment]
> > > Still the same error. I already updated the kakao.py with your updated code.
> > 
> > 
> > That is strange... not sure what would be causing the error then as the affected code is commented out, and I was able to download the video fine on my end. Can you paste the error you got this time (even if it is the same as before)? I would also suggest double-checking to make sure the file is [exactly matching what is shown here (especially around line 120 where the change is)](https://github.com/ytdl-org/youtube-dl/blob/836f8042568defd8f1530c0eba007a6fc37cc13b/youtube_dl/extractor/kakao.py).
> 
> Thank you it's now working.
> I forgot to comment the 'thumbnails': thumbs, from line 139

Okay, glad to hear it's working for you now!

**Pull request closed without merging**
