### PR TITLE
[doodstream] add new extractor

### PR DESCRIPTION
**Pull request by sxvghd**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Support for the DoodStream video hosting site.
An updated version of #26345. Normally I'd add all the changes there, but because of septembers removal, my repo is in this zombie-like state and I think it's better to just start over.

Closes #26345.

### CODE REVIEW

**Comment by dstftw** [comment]
This looks like copyrighted content. youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free). Provide [an example URL](https://github.com/rg3/youtube-dl/blob/master/README.md#is-the-description-of-the-issue-itself-sufficient) that does not violate any copyrights.

**Comment by schnusch** [comment]
I added some fixes, including the test, to their pull request (see <https://github.com/sxvghd/youtube-dl-1/pull/1>).

**Review by lukluk — APPROVED** [review]

**Comment by R1tzy** [comment]
Guys, a question, if you were going to download the doodstream link in python how would you do it. I've tried with wget, with open() turning it into 'wb', with youtube_dl it doesn't work. I don't know how else I can get it. I already checked if I could use .m3u8 capture or something similar in the request and nothing worked.

**Comment by michal-repo** [comment]
> Guys, a question, if you were going to download the doodstream link in python how would you do it. I've tried with wget, with open() turning it into 'wb', with youtube_dl it doesn't work. I don't know how else I can get it. I already checked if I could use .m3u8 capture or something similar in the request and nothing worked.

@R1tzy 

take a look at Kodi's addon script.module.resolveurl

**Pull request closed without merging**
