### PR TITLE
[ard] Reduce strictness of url regular expression

### PR DESCRIPTION
**Pull request by olifre**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The `-` is optional, and fails to match for example:
https://www.daserste.de/unterhaltung/serie/in-aller-freundschaft-die-jungen-aerzte/videos/diversity-tag-sanam-afrashteh100.html
Use `-?` to accept also URLs without `-` before the trailing part.

### CODE REVIEW

**Comment by pukkandan** [comment]
> https://www.daserste.de/unterhaltung/serie/in-aller-freundschaft-die-jungen-aerzte/videos/diversity-tag-sanam-afrashteh100.html

Maybe consider adding this as a test case

**Comment by olifre** [comment]
> Maybe consider adding this as a test case

I surely can do that, but the link will be expired in ~1 year, since the content is only kept for one year. Is this still a useful test case?

**Comment by pukkandan** [comment]
You can add it like this:
```py
{
    'url': 'https://www.daserste.de/unterhaltung/serie/in-aller-freundschaft-die-jungen-aerzte/videos/diversity-tag-sanam-afrashteh100.html',
    'only_matching': True,
}, 
```

That way only the regex is tested, not the download

**Comment by olifre** [comment]
@pukkandan Many thanks, this was not clear to me (my first `youtube-dl` PR). I added the test in the second commit :-).

**Pull request closed without merging**
