### PR TITLE
[twitch] Handle new /videos URLs (closes #24263)

### LINKED ISSUE #24263: Adapt to new Twitch URL schemes
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.03.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.twitch.tv/educated_collins/videos?filter=archives&sort=time']
[debug] Encodings: locale cp1254, fs mbcs, out cp1254, pref cp1254
[debug] youtube-dl version 2020.03.06
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg git-2020-02-20-56df829, ffprobe git-2020-02-20-56df829, phantomjs 2.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[twitch:stream] educated_collins: Downloading stream JSON
ERROR: educated_collins is offline
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6_nk0mi2\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6_nk0mi2\build\youtube_dl\extractor\common.py", line 530, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmp6_nk0mi2\build\youtube_dl\extractor\twitch.py", line 582, in _real_extract
youtube_dl.utils.ExtractorError: educated_collins is offline
```

## Description

This report is similar to this one: https://github.com/ytdl-org/youtube-dl/issues/11469

Twitch changed some URL schemes since then. For example `https://twitch.tv/educated_collins/videos/past-broadcasts` equals to this now: `https://www.twitch.tv/educated_collins/videos?filter=archives&sort=time`

Youtube-dl can recognize this URL: `https://twitch.tv/educated_collins/videos/past-broadcasts`
But it cannot recognize this URL: `https://www.twitch.tv/educated_collins/videos?filter=archives&sort=time`

Which is what someone can get from Twitch when browsing past broadcasts page.
```

### PR DESCRIPTION
**Pull request by willbeaufoy**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Twitch URLs on the path /videos have changed e.g. from
/videos/highlights to /videos?filter=highlights.

I have added support for the new URLs. The old URLs now redirect to the
base videos page, so I have removed support for them.

### CODE REVIEW

**Comment by ahmedtds** [comment]
Will this be merged?

**Comment by willbeaufoy** [comment]
> Will this be merged?

Hope so, however unfortunately I've heard nothing from the youtube-dl maintainers since I made this pull request. As far as I can see it's ready to go.

**Comment by seriousm4x** [comment]
I'm not entirely sure if your fix is causing another problem, but after i applied it, I got the following error:
```
[twitch:videos:all] wubbl0rz: Downloading channel info JSON
ERROR: twitch:videos:all returned error: Bad Request - Channel identifier "wubbl0rz" is in an invalid format
```
I think its not completely fixed.

**Comment by willbeaufoy** [comment]
> I'm not entirely sure if your fix is causing another problem, but after i applied it, I got the following error:
> 
> ```
> [twitch:videos:all] wubbl0rz: Downloading channel info JSON
> ERROR: twitch:videos:all returned error: Bad Request - Channel identifier "wubbl0rz" is in an invalid format
> ```
> 
> I think its not completely fixed.

Hhm ok. I don't remember that issue when I wrote this patch. I can look into it if it looks like there's a chance of getting this merged in, but so far it hasn't been commented on or anything by any of the maintainers, so I'm reluctant to put more work in if this is never going to be merged.

**Comment by ahmedtds** [comment]
@willbeaufoy that's an another bug started to happen recently.
relevant report: https://github.com/ytdl-org/youtube-dl/issues/25553
relevant attempt to fix: https://github.com/ytdl-org/youtube-dl/pull/25606

I also noticed this older PR which seems to be same fix attempt as this PR: https://github.com/ytdl-org/youtube-dl/pull/21812
https://github.com/ytdl-org/youtube-dl/issues/21811

**Pull request closed without merging**
