### PR TITLE
fixed error when parsing fm4 url

### PR DESCRIPTION
**Pull request by jonolt**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

removed if clause for special fm4 show_id handling, as url has been changed to a new format where the station is natively correct.

updated only test url of ORFRadio Extractors. While other extractors are not updated because they worked with a simple test in the console with random current links and the links would get invalid again quickly anyway in a short time.

### CODE REVIEW

**Comment by dstftw** [comment]
You have no guarantees that it will always start with 4.

**Comment by jonolt** [comment]
you are right, i can't guarantee it, but
- all shows I used to download did never start with 4. but now do
- i checked different shows at multiple days which all start with 4
- i have recognized the update of the site by some minor changes on the interface, as well as a changed forwarding of expired links
- i can't use a if statement to check (see code block), because i don't know for sure that there is (will be) no show name that starts with "4". Which will yield the `show_id='4XY'` while the correct value is (may be) `show_id='44XY'`.
```pyhton
# cant do something like this:
if station == 'fm4':
    if not show_id.startswith("4"):
        show_id = '4%s' % show_id
```

**Comment by dstftw** [comment]
URLs without 4 prefix should not be matched in the first place,

**Comment by jonolt** [comment]
Then everything fits, or **did I misunderstand something?**

The current version inserts a "4" before station_id. 
```
OLD URL: https://fm4.orf.at/player/20191113/HOP

show_id = "HOP"
if station == 'fm4':
    show_id = '4%s' % show_id
show_id = "4HOP"
```
My commit removes this, because it is no longer necessary, since the URL-scheme of the website itself has changed and the "4" is already in the URL.

```
OLD URL: https://fm4.orf.at/player/20191113/HOP
NEW URL: https://fm4.orf.at/player/20200101/4HOP

show_id = "4HOP"
# no manipulation needed any more
```

**Comment by dstftw** [comment]
No, it's not. Again: if you claim id to always start with 4 then extractor should not match URLs with ids not starting with 4.

**Comment by jonolt** [comment]
> URLs without 4 prefix should not be matched in the first place.

I think I got it now :sweat_smile:. Updated the _VALID_URL regex string.

**Pull request merged**
