### PR TITLE
Add official docker container

### PR DESCRIPTION
**Pull request by mikenye**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [X] New feature

---

### Description of your *pull request* and other information

Add an official docker image. This has been discussed in several existing pull requests, most notably #11632. The comments before closure of the previous pull request indicate that the Dockerfile should live in this repository. Accordingly, I have added this, plus documentation on how best to utilise the the container.

Furthermore, there is a simple shell script that can be used to build, tag and push the docker image up to hub.docker.com. Alternatively, hub.docker's automated build process can be configured to automatically re-build the "latest" tagged container when this repository is updated. However, the script allows past versions of youtube-dl to be pushed to hub.docker with the youtube-dl version as the tag (which is likely worth doing). There is probably a way to automate this, however without access as a contributor I can't do much more than this.

The docker container attempts to ahere to good practices:

- youtube-dl is not run as root. The user can specify the UID/GID that youtube-dl is run as, or if omitted it will run as 1000:1000.

- It  allows the user to supply a youtube-dl.conf file, a .netrc file, work with cookies and a download-archive.

- User can set up an alias for youtube-dl that instantiates the container and see no functional difference in operation.

During the build process, the docker container builds youtube-dl from scratch - pre-built binaries are not used. If the build script is used, the following is performed:

1. Image is built with the :latest tag
2. Upon successful build, the version of youtube-dl is obtained from the freshly built image. This version is used to create a version of the image that is tagged with youtube-dl's version instead of the :latest tag.
3. Upon success of the above two items, the script will attempt to push both the :latest and :version tagged images to hub.docker (which fails if the user has no access, but the built images will still reside on the local system)

Container is based on Alpine Linux version 3.9 and uses a multi-build process to keep the final image size as low as possible (142MB).

I've been using youtube-dl for years and am delighted that I might be able to contribute to this project.

Thanks for your time and consideration.

### CODE REVIEW

**Comment by mikenye** [comment]
Just closed as out of scope with no explanation as why this is out of scope? Dude I put a lot of effort into this.

**Comment by dstftw** [comment]
I don't plan maintaining this as already pointed out multiple times. You should use search or at least ask before implementing anything.

**Comment by mikenye** [comment]
Apologies, I saw this response: https://github.com/ytdl-org/youtube-dl/pull/11632#issuecomment-273037381

...and figured there was interest.

**Comment by paviad** [comment]
Check out my repo at https://github.com/paviad/youtube-dl-docker 
It will build youtube-dl from source inside docker, and set up batch files to run it into a local directory (required windows 10 and docker for windows)

**Pull request closed without merging**
