### PR TITLE
[teachable] Fix URL validation V2

### PR DESCRIPTION
**Pull request by ilpersi**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

As #26752 has been rejected, I am proposing a new improved version to fix teachable course download.

### CODE REVIEW

**Comment by dstftw** [comment]
Add tests.

**Comment by ilpersi** [comment]
@dstftw The teachable course URL where I had this happen is related to a paid course (that I paid and own and wanted to watch offline) so I am not currently able to provide a testable URL. How should I behave here?

**Comment by dstftw** [comment]
You can either find some free course with the same pattern or you can provide credentials privately or at least provide `--dump-pages`.

**Comment by ilpersi** [comment]
@dstftw attached you can find a `--dump-pages` sample from one of the teachable pages. Let me know if you need to have the full console log of the whole course.

[page_dump.zip](https://github.com/ytdl-org/youtube-dl/files/5655187/page_dump.zip)

**Pull request closed without merging**
