### PR TITLE
Added option to force recode a video if it's already in the target format

### PR DESCRIPTION
**Pull request by mdawar**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Added a new option `--force-recode-video` as suggested by @dstftw in pull request #18728 to force processing a video file even if it's already in the target format, this is useful if we're passing `--postprocessor-args` for example to cut the file, in the current version the conversion is skipped with the message:
```
[ffmpeg] Not converting video file FILE_PATH - already is in target format FILE_FORMAT
```

With this option we can force the recoding of the video:
```
youtube-dl URL --recode-video mp4 --format mp4 --postprocessor-args "-ss 10 -to 120 -c copy" --force-recode-video
```

### CODE REVIEW

**Comment by mdawar** [comment]
@dstftw since we cannot read and write at the same time I have added a suffix `.recoded` for the output path, for example a `video.mp4` file will be recoded as `video.recoded.mp4`, if this is not the right way to do it I can change this behavior for example rename the old file before recoding.

**Comment by ealgase** [comment]
Using `.temp.mp4` would probably make sense for consistency.

**Comment by mdawar** [comment]
@ealgase does it make sense if a `video.mp4` is converted to `video.temp.mp4` and then `video.mp4` will be deleted if `--keep-video` was not passed and the `.temp` file returned ?

I think renaming the file that will be deleted before recoding is much better, we'll wait for @dstftw 's opinion and see.

**Comment by mdawar** [comment]
@dstftw can you please review this request and let me know your opinion on renaming the original file before forcing a convert ? Thank you.

**Pull request closed without merging**
