### PR TITLE
[youtube] Add additional method for extracting artist and track name, per #20599

### PR DESCRIPTION
**Pull request by rryanq**
Added fix for issue #20599: some YouTube music videos did not properly extract artist and track name

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
This PR adds an additional method for extracting artist and track names on YouTube music videos that were previously returning null for both of these values. This PR fixes issue #20599 

The following videos were returning null for both 'artist' and 'track' when using the --dump-json flag:
https://music.youtube.com/watch?v=MgNrAu2pzNs
https://music.youtube.com/watch?v=z7e54L8usac
https://music.youtube.com/watch?v=Z47pGUpMy-E

Now, they all return the proper artist and track values. In many cases, this also affects the 'creator' field which is assigned to the value of 'artist' in the event that the value for 'video_creator' is null.

### CODE REVIEW

**Comment by rryanq** [comment]
@ealgase if you're available to review these changes, @jgalp and I would appreciate it!

**Comment by ealgase** [comment]
Everything looks good to me, but I'm not a project maintainer (just an active community member).

**Comment by remitamine** [comment]
the description of the music video contains more information that should be extracted(`album`, `release_date`), and it might be better to parse `video_description` variable then parsing the raw HTML layout.

**Comment by rryanq** [comment]
@remitamine Thank you for the feedback. The requested changes have been made.

**Comment by remitamine** [comment]
I tested this on more videos, those are some of the cases that need to be handled better:
- `artist` should be extracted from `Artist: ` part when it's present:
https://www.youtube.com/watch?v=k0jLE7tTwjY
- does not work with multiple artists:
https://www.youtube.com/watch?v=Yv0x3kdWbTg
https://www.youtube.com/watch?v=74qn0eJSjpA
- some videos have `release_year` and no `release_date`:
https://www.youtube.com/watch?v=-hcAI0g-f5M
https://www.youtube.com/watch?v=aUDDP9RR_VU
https://www.youtube.com/watch?v=t6g2tKgF9HQ
https://www.youtube.com/watch?v=TUnEJM6W-Fw
- some videos have `release_date` and no `release_year`(`release_year` should be extracted from `release_date`):
https://www.youtube.com/watch?v=k0jLE7tTwjY
https://www.youtube.com/watch?v=8TkIgZze8vw

**Comment by rryanq** [comment]
@remitamine would you suggest returning both `release_date` and `release_year` as two separate values, or just a `release_date` field that gets as specific as it can? (i.e. return date if available, otherwise return year)

**Comment by rryanq** [comment]
@remitamine Also, for the case where there are multiple artists, should they be returned as:
`artist: artist1 and artist2 and artist3`
or separated by commas like:
`artist: artist1, artist2, artist3`
or should `artist` be returned as a list of artists or something else?

**Comment by remitamine** [comment]
> would you suggest returning both release_date and release_year as two separate values, or just a release_date field that gets as specific as it can?

both, and when only the `release_date` is available from the description, then fill `release_year` using `release_date`.
> Also, for the case where there are multiple artists, should they be returned as:
artist: artist1 and artist2 and artist3
or separated by commas like:
artist: artist1, artist2, artist3
or should artist be returned as a list of artists or something else?

`artist1, artist2, artist3`

**Comment by rryanq** [comment]
@remitamine The requested changes have been made.

**Comment by remitamine** [comment]
ok, now, just squash your commits into a single commit(the convention in the project is to prefix commits to extractor files with `[EXTRACTOR_FILE_NAME]` in this case `[youtube] COMMIT_MESSAGE`).

**Comment by rryanq** [comment]
Done!

**Comment by remitamine** [comment]
Thanks, cherry-picked.

**Pull request closed without merging**
