### PR TITLE
[canvas] fix gone error vrtnu. fixes #26957

### LINKED ISSUE #26957: Error 410: Gone (VRT.BE)
Hello, can you help to download that ? :)
With the subtitles it would be perfect.
Thank you in advance.

> C:\Users\hehe\Downloads>youtube-dl https://www.vrt.be/vrtnu/a-z/belpop/10/belpop-s10a1
> [VrtNU] belpop-s10a1: Downloading webpage
> [VrtNU] belpop-s10a1: Downloading JSON metadata
> [Canvas] pbs-pub-85aaef91-3bd4-496e-8be3-706e26f698f3$vid-4af6ec24-8876-4409-b003-57fd23adff63: Downloading asset JSON
> WARNING: Unable to download asset JSON: HTTP Error 410: Gone
> [Canvas] pbs-pub-85aaef91-3bd4-496e-8be3-706e26f698f3$vid-4af6ec24-8876-4409-b003-57fd23adff63: Downloading token
> [Canvas] pbs-pub-85aaef91-3bd4-496e-8be3-706e26f698f3$vid-4af6ec24-8876-4409-b003-57fd23adff63: Downloading video JSON
> ERROR: An extractor error has occurred. (caused by KeyError('title',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### PR DESCRIPTION
**Pull request by bendekeersm**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by bendekeersm** [comment]
fixes #26957

**Comment by Jan-PieterBaert** [comment]
I have checked this with https://www.vrt.be/vrtnu/a-z/de-ideale-wereld/2020-nj/de-ideale-wereld-d20201117/ and it works fine locally :smiley:

**Comment by cypheron** [comment]
You should re-trigger the CI by force pushing your code unchanged (commit --amend first). Travis CI is showing jobs failed even if they didn't run, like in my case and also yours.

**Comment by bendekeersm** [comment]
> You should re-trigger the CI by force pushing your code unchanged (`commit --amend` first). Travis CI is showing jobs failed even if they didn't run, like in my case and also yours.

Thanks for pointing that out. Was my very first pull request, so a bit uncertain if I did something wrong or not. Will check it later today

**Comment by ottob** [comment]
This did not work for me:
```
% python -m youtube_dl https://www.vrt.be/vrtnu/a-z/wanderlust/1/wanderlust-s1a2/
[VrtNU] wanderlust-s1a2: Downloading webpage
[VrtNU] vid-22d8766f-ec31-4ffe-b4aa-3682f46db7ce: Downloading token
[VrtNU] vid-22d8766f-ec31-4ffe-b4aa-3682f46db7ce: Downloading video JSON
WARNING: Unable to download JSON metadata: HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/ottobretz/Downloads/youtube-dl-master/youtube_dl/__main__.py", line 19, in <module>
    youtube_dl.main()
  File "youtube_dl/__init__.py", line 474, in main
    _real_main(argv)
  File "youtube_dl/__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "youtube_dl/YoutubeDL.py", line 2029, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "youtube_dl/YoutubeDL.py", line 796, in extract_info
    return self.__extract_info(url, ie, download, extra_info, process)
  File "youtube_dl/YoutubeDL.py", line 803, in wrapper
    return func(self, *args, **kwargs)
  File "youtube_dl/YoutubeDL.py", line 824, in __extract_info
    ie_result = ie.extract(url)
  File "youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "youtube_dl/extractor/canvas.py", line 375, in _real_extract
    for target in data['targetUrls']:
TypeError: 'bool' object has no attribute '__getitem__'
```

**Comment by Jan-PieterBaert** [comment]
@ottob it works for me when using the netrc file, but not without, it's probably something you need a token for

**Comment by ottob** [comment]
That was it, thanks. I updated my netrc and now it works with this patch.

**Comment by ghen2** [comment]
Same here, but it used to fail gracefully (with a clear error) when not logged in, not with `HTTP 400: Bad request`.

**Comment by editicalu** [comment]
Can confirm that this fixes 410 Gone.

**Comment by doxxuni** [comment]
Tested and working

**Comment by ghen2** [comment]
Hi
What is needed to get this merged besides 6 positive reviews?
This affects only a single extractor, that has been broken for >2 months now (https://github.com/ytdl-org/youtube-dl/issues/26957).

**Comment by bendekeersm** [comment]
> Hi
> What is needed to get this merged besides 6 positive reviews?
> This affects only a single extractor, that has been broken for >2 months now (#26957).

Good question. It was my first time contributing. I expected creating a pull request would be enough to get it merged.

**Comment by Jan-PieterBaert** [comment]
If you can, you could try to ask a review from one of the maintainers

**Comment by MatthiasCoppens** [comment]
@bendekeersm People on IRC said to clean the commented out code first. If no-one reviews it after those changes, you could maybe ping the maintainers on IRC (#youtube-dl on Freenode).

**Pull request closed without merging**
