### PR TITLE
Added optional www prefix to pattern in weibo extractor

### PR DESCRIPTION
**Pull request by RexYuan**
It’s a tiny fix so I thought I’d just make a PR instead of going through filing an issue and all that.

### CODE REVIEW

**Comment by dstftw** [comment]
Do not capture groups you don't use.

**Comment by RexYuan** [comment]
Weibo redirects you to the URL with the www record. For the test example ```https://weibo.com/6275294458/Fp6RGfbff?type=comment'```, Weibo redirects you to ```https://www.weibo.com/6275294458/Fp6RGfbff?type=comment%2527```. So if you try to copy and paste the URL from the browser and run youtube-dl with it directly, you'll get an Unsupported URL error. Sorry if I wasn't clear enough.

**Comment by dstftw** [comment]
Did you even read my comment?

**Comment by RexYuan** [comment]
I'm not sure if I understand. That was my response to your comment.

**Comment by RexYuan** [comment]
Sorry I misunderstood your comment. Took another look at the file and fixed it now.

**Pull request merged**
