### PR TITLE
[nick] fix extraction

### PR DESCRIPTION
**Pull request by DennyDai**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

1. beta.nick.com and beta.nickjr.com are no longer available, so I removed them. 
2. #27470
3. updates tests (videos from previous tests are no longer available).

### CODE REVIEW

**Comment by Sipherdrakon** [comment]
Sweet, got nick.com working again, thank you so much for this. :-)

**Comment by 1033Forest** [comment]
I downloaded the latest version of youtube-dl and nick.com still doesn't work. What is going on?

**Comment by DennyDai** [comment]
@1033Forest this PR haven't been merged yet.

**Comment by 1033Forest** [comment]
Oh. How can I compile yours so I can use it for myself? I want to download episodes from there again.
And I am running Windows 10. How can I compile it into an .exe

**Comment by DennyDai** [comment]
@1033Forest Yes you can, and you don't have to compile it.

Step 1. Check out the PR:
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

Step 2. Install:
https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree

Step 3. Run:
https://github.com/ytdl-org/youtube-dl#developer-instructions

**Comment by 1033Forest** [comment]
Thanks! Got it working and nick.com works again.

**Comment by Danker1990** [comment]
Can someone write a simpiler guide on running this branch as i read through the 3 steps above and it really has frazzled my brain. i kinda get what you are saying but haven't a clue where to start. Once i get this in a simpiler format i can use this on other builds as there are a few more forks being developed that i want to try out.

**Comment by Danker1990** [comment]
> @1033Forest Yes you can, and you don't have to compile it.
> 
> Step 1. Check out the PR:
> https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally
> 
> Step 2. Install:
> https://packaging.python.org/tutorials/installing-packages/#installing-from-a-local-src-tree
> 
> Step 3. Run:
> https://github.com/ytdl-org/youtube-dl#developer-instructions

Can someone write a simpiler guide on running this branch as i read through the 3 steps above and it really has frazzled my brain. i kinda get what you are saying but haven't a clue where to start. Once i get this in a simpiler format i can use this on other builds as there are a few more forks being developed that i want to try out.

**Comment by viceless** [comment]
I still can't get this to work.

**Comment by Steveland** [comment]
It does not work, I get ERROR: Unsupported URL for nick.com urls on latest youtube-dl version 2021.06.06

**Comment by Steveland** [comment]
Thanks Sipherdrakon for the information! The fix is from January, it should be merged with the official build already, what is taking so long?

**Comment by Sipherdrakon** [comment]
You're welcome. And yeah not sure why the dev team hasn't merged it yet. I know it works as I've been using it since this pull request was made.

**Comment by genebean** [comment]
Is this PR intended to fix the fact that that downloading http://www.nickjr.com/blues-clues-and-you/videos/what-i-like-about-blue-s2-ep10-full-episode/ results in this list of files instead of a single video?

```bash
$ ls
'Blue'\''s Clues &amp; You - '\''What I Like About Blue'\'' S1-6521107c-0699-4563-90c1-d6bd8fe87525.mp4'
'Blue'\''s Clues &amp; You - '\''What I Like About Blue'\'' S2-47d6e05b-1076-4a88-b324-dddfe5de70ca.mp4'
'Blue'\''s Clues &amp; You - '\''What I Like About Blue'\'' S3-cabdbe11-7353-47e9-8133-6049a334792a.mp4'
'Blue'\''s Clues &amp; You - '\''What I Like About Blue'\'' S4-628a8836-ecc7-465d-b080-01f05e380be3.mp4'
'Blue'\''s Clues &amp; You - '\''What I Like About Blue'\'' S5-b0576d60-e4e7-4222-b6ef-3dedf2115090.mp4'
```

**Comment by DennyDai** [comment]
@genebean No

**Comment by genebean** [comment]
Thanks @DennyDai! Do you happen to have any tips on how to solve that or can you point me in the right direction?

**Comment by DennyDai** [comment]
@genebean sorry I don't know

**Comment by genebean** [comment]
No problem, thanks for taking the time to respond!

**Pull request closed without merging**
