### PR TITLE
Added Support for HGTV.ca

### PR DESCRIPTION
**Pull request by vallieres**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

**Added support for hgtv.ca**
Since both hgtv.ca and hgtv.com are using the same CMS, by updating the
existing script to support both domains, it works well with videos on both
websites.

### CODE REVIEW

**Comment by hmnd** [comment]
I meant to pr this earlier but never got to it. I believe it's also possible to support food network the same way.

**Comment by dstftw** [comment]
Invalid. This is covered by corus extractor.

**Comment by vallieres** [comment]
The reason why I put this PR up is because it's actually not working with the Corus one. No I did not investigate too much why the Corus extractor does not work, I'll take a look. 

This is the error I got on the latest youtube-dl:
```$ youtube-dl https://www.hgtv.ca/shows/love-it-or-list-it-vancouver/videos/samia-and-darren/1504201795839/
[generic] 1504201795839: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 1504201795839: Downloading webpage
[generic] 1504201795839: Extracting information
ERROR: Unsupported URL: https://www.hgtv.ca/shows/love-it-or-list-it-vancouver/videos/samia-and-darren/1504201795839/```

**Comment by dstftw** [comment]
As already said this is covered by corus extractor. You either does not use the latest version or messed up.
```
>youtube-dl.exe https://www.hgtv.ca/shows/love-it-or-list-it-vancouver/videos/samia-and-darren/1504201795839/ -F
[Corus] 1504201795839: Downloading JSON metadata
[Corus] 1504201795839: Downloading hls smil file
...
```

**Pull request closed without merging**
