### PR TITLE
[jwplatfom] do not match video URLs(#20596)

### PR DESCRIPTION
**Pull request by ipaha**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

URL 'https://content.jwplatform.com/videos/WbFsN7Kl-WdGqK18o.mp3?exp=1566156755\&sig=e60548f2434c12279baff74cf8327b9bd9ffc7383'
was broken by https://github.com/ytdl-org/youtube-dl/commit/7c072f00d66f3b3f44d301059443480a5c83d3c0 and approach for the fix was introduced here 
https://github.com/ytdl-org/youtube-dl/commit/9c017253e83ac3dfd363566ccbb9fc63f4e2ac07

[JWPlatform] WbFsN7Kl: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

### CODE REVIEW

**Comment by dstftw** [comment]
This has no effect.

**Comment by ipaha** [comment]
I've checked the fix locally. Why you have left jwplatfom  video ULR broken?

**Comment by dstftw** [comment]
There are no telepathists here to know what you have checked. The URL provided does not work in both cases making this PR useless.

**Comment by ipaha** [comment]
Sorry for the mess. Just copy and past here mail text to the author of the code line I am fixing. The author is @remitamine 

> Here we have 2 problems after this commit https://github.com/ytdl-org/youtube-dl/commit/7c072f00d66f3b3f44d301059443480a5c83d3c0
Broken URLS:
1) https://content.jwplatform.com/manifests/NdSc5Qlg.m3u8?exp=1554638831&sig=b7f01a3ce1e275dffe6ff74599f02ac5
2) https://content.jwplatform.com/videos/WbFsN7Kl-WdGqK18o.mp3?exp=1566156755\&sig=e60548f2434c12279baff74cf8327b9bd9ffc7383' 
Both URLs were processed in youtube_dl/extractor/common.py
before your commit. 
And now it is processed by  youtube_dl/extractor/jwplatform.py

Both errorrs the same with different ID
[JWPlatform] WbFsN7Kl: Downloading JSON metadata
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError());  

This URL https://content.jwplatform.com/manifests/ you have fixed here https://github.com/ytdl-org/youtube-dl/commit/9c017253e83ac3dfd363566ccbb9fc63f4e2ac07
And the output in this email chain is for manifest URL. Now manifest ULR is working and processed by extractor/common.py
https://content.jwplatform.com/videos/  was fixed by me here https://github.com/ytdl-org/youtube-dl/pull/22148/files with the same approach and similar success download not listed here.

To check URL I use my paid account with temporary URL with my credentials and expiration as HTTP GET parameters ?exp=1566156755\&sig=e60548f2434c12279baff74cf8327b9bd9ffc7383
That is why dstftw can't use this url directly to check downloading.

I need to contribute the fix. Can you support? 
Please

**Pull request merged**
