### PR TITLE
Fixed vrt.be, sporza.be and removed old sites.

### PR DESCRIPTION
**Pull request by principis**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

I removed deredactie.be, cobra.be and cobra.canvas.be because they do not exist anymore.
This also fixes vrt.be and sporza.be which was not working anymore because the website were overhauled.

Let me know if I need to change anything!

### CODE REVIEW

**Comment by rdehuyss** [comment]
I can confirm the fix works.

**Comment by rdehuyss** [comment]
@principis Is it possible to use youtube-dl for the livestream? I get a 500 error when using the live stream, **all other url's work fine!**

**Comment by principis** [comment]
> @principis Is it possible to use youtube-dl for the livestream? I get a 500 error when using the live stream, **all other url's work fine!**

I don't think so. I can try to make a fix for it but I'm not that experienced with it. :)

**Comment by principis** [comment]
Is it possible for this to be merged? Or do I need to change something?

**Comment by thibmaek** [comment]
@nicerman1 VRT might have changed something on their end, doesn't seem to work any longer with the current extractor implementation in youtube-dl. I was however able to download an episode by finding the link to a MPD (MPEG-DASH manifest) in a JSON response and pointing youtube-dl to that link

image

**Comment by nicerman1** [comment]
> @nicerman1 VRT might have changed something on their end, doesn't seem to work any longer with the current extractor implementation in youtube-dl. I was however able to download an episode by finding the link to a MPD (MPEG-DASH manifest) in a JSON response and pointing youtube-dl to that link
> 
> image
> 
> EDIT: nvm this method above works, but the issue downloading was easily fixed after logging in via youtube-dl

Awesome, this works! Thanks a lot!

**Pull request closed without merging**
