### PR TITLE
[rai] extend formats with direct http mp4 link

### LINKED ISSUE #27902: download from raiplay
## Checklist

- [x ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE
i've tried to download the video from link:
https://www.raiplay.it/video/2021/01/Che-Dio-ci-aiuti-S6E1-E-tu-sei-pronto-b4b77f3a-0496-4c99-95ab-097034450b02.html
but the result is without audio
the only stream downloaded is video
my config parameters are:
-o "I:\downloads\youtube-dl\%(title)s-%(id)s.%(ext)s"
where i'm wrong?
thanks

### PR DESCRIPTION
**Pull request by nixxo**
### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] Improvement
- [x] New feature

---

### Description of your *pull request* and other information

Creates url for direct http mp4 based on the relinker url and adds them to the formats.

BEFORE:
```
[info] Available formats for b4b77f3a-0496-4c99-95ab-097034450b02:
format code               extension  resolution note
hls-aac-Audiodescrizione  mp4        audio only [Audiodescrizione]
hls-aac-Italiano          mp4        audio only [Italiano]
hls-1200                  mp4        736x414    1288k
hls-1800                  mp4        1024x576   1758k
hls-2400                  mp4        1280x720   2344k  (best)
```

AFTER:
```
[info] Available formats for b4b77f3a-0496-4c99-95ab-097034450b02:
format code               extension  resolution note
hls-aac-Audiodescrizione  mp4        audio only [Audiodescrizione]
hls-aac-Italiano          mp4        audio only [Italiano]
hls-1200                  mp4        736x414    1288k
https-1200                mp4        736x414    1288k
hls-1800                  mp4        1024x576   1758k
https-1800                mp4        1024x576   1758k
hls-2400                  mp4        1280x720   2344k
https-2400                mp4        1280x720   2344k
https-3600                mp4        1440x810   3600k
https-5000                mp4        1920x1080  5000k  (best)
```

Kinda fixes #27902

### CODE REVIEW

**Comment by nixxo** [comment]
normal run works but test fails...
```
λ python test\test_download.py TestDownload.test_RaiPlay
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading video JSON
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading XML metadata for platform mon
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading m3u8 information
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading XML metadata for platform flash
[RaiPlay] cb27157f-9dd0-4aee-b788-b1f67643a391: Downloading XML metadata for platform native
C:\Users\Utente\scoop\apps\python\current\lib\socket.py:740: ResourceWarning: unclosed <socket.socket fd=444, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.5', 52119), raddr=('212.162.82.12', 80)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Utente\scoop\apps\python\current\lib\socket.py:740: ResourceWarning: unclosed <socket.socket fd=424, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.5', 52120), raddr=('212.162.82.12', 80)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Utente\scoop\apps\python\current\lib\socket.py:740: ResourceWarning: unclosed <socket.socket fd=444, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.5', 52121), raddr=('2.16.186.9', 80)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Utente\scoop\apps\python\current\lib\socket.py:740: ResourceWarning: unclosed <socket.socket fd=424, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.5', 52122), raddr=('2.16.186.8', 80)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Utente\scoop\apps\python\current\lib\socket.py:740: ResourceWarning: unclosed <socket.socket fd=444, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.5', 52123), raddr=('2.16.186.26', 80)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Utente\scoop\apps\python\current\lib\socket.py:740: ResourceWarning: unclosed <socket.socket fd=424, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.1.5', 52124), raddr=('2.16.186.32', 80)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
[info] Writing video description metadata as JSON to: test_RaiPlay_cb27157f-9dd0-4aee-b788-b1f67643a391.info.json
.
----------------------------------------------------------------------
Ran 1 test in 3.384s

OK
```

**Comment by nixxo** [comment]
basically the server can be tricked into giving a direct http mp4 url by not sending the User-Agent header as seen in this two curl requests:
```
λ curl "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=R1NUM8Klj9TcWu6Y9xMnFQeeqqEEqualeeqqEEqual" -v
*   Trying 212.162.82.12:80...
* Connected to mediapolisvod.rai.it (212.162.82.12) port 80 (#0)
> GET /relinker/relinkerServlet.htm?cont=R1NUM8Klj9TcWu6Y9xMnFQeeqqEEqualeeqqEEqual HTTP/1.1
> Host: mediapolisvod.rai.it
> User-Agent: curl/7.74.0
> Accept: */*
>
...
< Location: https://vod1-rai-it.akamaized.net/podcastcdn/teche_root/YT_ITALIA_TECHE_HD_multiaudio/13838144_,1200,1800,2400,3600,5000/playlist.m3u8?auth=daEdvc8cbabaFcZc0avc6cSd8bpdkdqcEaW-bGeT7E-c0-BlrwsEo&aifp=V001
...
```

```
λ curl "http://mediapolisvod.rai.it/relinker/relinkerServlet.htm?cont=R1NUM8Klj9TcWu6Y9xMnFQeeqqEEqualeeqqEEqual" -v -H User-Agent:
*   Trying 212.162.82.12:80...
* Connected to mediapolisvod.rai.it (212.162.82.12) port 80 (#0)
> GET /relinker/relinkerServlet.htm?cont=R1NUM8Klj9TcWu6Y9xMnFQeeqqEEqualeeqqEEqual HTTP/1.1
> Host: mediapolisvod.rai.it
> Accept: */*
>
...
< Location: http://creativemedia6-rai-it.akamaized.net/podcastcdn/teche_root/YT_ITALIA_TECHE_HD_multiaudio/13838144_1800.mp4
...
```
I tried to use the standard function provided by youtubedl to make this request but it did't seem to work. I was not able to force youtubedl to make a "clean" request so I written the get_location function to solve the problem (and not pollute the output).

It works when executing youtubedl normally but it fails then doing the tests. Any ideas?

**Comment by dirkf** [comment]
IS this still relevant?

**Comment by nixxo** [comment]
no, already merged. It can be closed.

**Comment by dirkf** [comment]
Thx

**Comment by dirkf** [comment]
Merged with 60f513d71fa5412056ce6013fd1df1b595135132.

**Pull request closed without merging**
