### PR TITLE
Added piped instances

### PR DESCRIPTION
**Pull request by JordanWeatherby**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Adds urls for other instances of piped. I was already doing this for yt-dlp ( https://github.com/yt-dlp/yt-dlp/pull/3714 ) and I thought it was worth adding to youtube-dl too (especially after coming across https://github.com/ytdl-org/youtube-dl/issues/30820 ).
This does not offer a permanent solution to other instances but given the invidious instances are added in a similar fashion I thought a half solution was better than none

Didn't add tests as the insidious instances in the same file do not have tests, have tested and all instances work however.

### CODE REVIEW

**Comment by gamer191** [comment]
Note for maintainers: This does not add Piped support, it simply redirects Piped URLs to their respective Youtube URLs (the same behaviour that youtube-dl currently uses for invidious).

See https://github.com/yt-dlp/yt-dlp/issues/3053 for more info

**Comment by dirkf** [comment]
As piped != invidious, I'd prefer to have a separate list:
```py
    ...
        r'(?:www\.)?hpniueoejy4opn7bc4ftgazyqjoeqwlvh2uiku2xqku6zpoa4bf5ruid\.onion',
    )
    _PIPED_SITES = (
        # piped instances from https://github.com/TeamPiped/Piped/wiki/Instances
        r'(?:www\.)?piped\.kavin\.rocks',
        r'(?:www\.)?piped\.silkky\.cloud',
        r'(?:www\.)?piped\.tokhmi\.xyz',
        r'(?:www\.)?piped\.moomoo\.me',
        r'(?:www\.)?il\.ax',
        r'(?:www\.)?piped\.syncpundit\.com',
        r'(?:www\.)?piped\.mha\.fi',
        r'(?:www\.)?piped\.mint\.lgbt',
        r'(?:www\.)?piped\.privacy\.com\.de',
   )
   ...
                            %(invidious)s|
                            %(piped)s
   ...
                     $""" % {
        'invidious': '|'.join(_INVIDIOUS_SITES),
        'piped': '|'.join(_PIPED_SITES),
    }
                            
   
```
In the end I'd rather refactor in line with [my comment](https://github.com/ytdl-org/youtube-dl/issues/30820#issuecomment-1090092832), but this is OK for now.

**Comment by rautamiekka** [comment]
Is it really necessary to have `r'(?:www\.)?` spammed by having every single one as its own item ?

**Comment by dirkf** [comment]
You mean s/t like this, with appropriate deletions in `_PIPED_SITES`?
```
        'piped': '|'.join(r'(?:www\.)?' + x for x in _PIPED_SITES),
```
Or maybe the whole `https://` branch of the pattern should have `(?:www\.)?` and any domains that don't allow a `www.` prefix should be prefixed with `(?<!www\.)`? Who knows what the performance implications of these choices are?

**Comment by rautamiekka** [comment]
Nah, just do it in RegEx, and TBH I don't see any point in regarding whether the site currently accepts/uses a `www.` since that part usually doesn't matter to ytdl anyway.

**Pull request closed without merging**
