### PR TITLE
disable --mtime by default

### LINKED ISSUE #1709: Problems with automatically setting the video's mtime to the server's modification time
Youtube-DL recently changed its behaviour in a way that broke how I was using it. It used to set the `mtime` to when the file was downloaded; now it's set to when the file was uploaded to the video site.

This means that I can't sort my videos by download time anymore. It's problematic when you have a large download directory, or multiple collections, which you slowly process over time.

The only other downloader I've found with this default behaviour is `wget`. All the other downloaders -- browsers, torrent programs, curl, scp -- set the `mtime` to the time that you downloaded the file. (This is the [the definition of mtime](https://en.wikipedia.org/wiki/Mtime).)

I can see how people would want to save the video creation date. Luckily, there's a pull request in the pipeline (#1708) that writes this information -- _and more_ -- to the file's xattrs.

So, you can have it all: files sorted by download date, and their creation date!

How 'bout it?

### PR DESCRIPTION
**Pull request by flisk**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [ ] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

the mtime of a file normally reflects the last modification time of the file on disk rather than what the contents of the file represent. youtube-dl goes against this convention by default, which can cause issues when users don't know about youtube-dl special mtime behavior, e.g. premature deletion of files by cleanup scripts or time-based file searches.

instead of behaving in this unconventional way by default, youtube-dl should not modify the mtime of its output files unless the user specifically asks for that.

fixes #1709

### CODE REVIEW

**Comment by dirkf** [comment]
The problem is that the setting has been as it is for so long that if the default is changed people's workflows may be affected. The solution was already provided [10 years ago](https://github.com/ytdl-org/youtube-dl/issues/1709#issuecomment-27641159), ie `--no-mtime`.

yt-dlp also retains this default, presumably for the same reason.

**Comment by flisk** [comment]
a bit of pedantry that's necessary in my view: `--no-mtime` is not a solution to the problem "youtube-dl's default behavior is surprising and unconventional". that flag shouldn't be necessary for youtube-dl to behave in a reasonable way.

yt-dlp retains this default for no other reason than youtube-dl retaining it. see also: https://github.com/yt-dlp/yt-dlp/pull/6585#issuecomment-1477813545

is this your final decision?

**Comment by dirkf** [comment]
I don't think it's obvious that 
> ...default behavior is surprising

Personally I'm happy to see a downloaded file take on a modification time that matches the content. If you want to know when a file was put on the disk, use its creation time.

Also: https://github.com/yt-dlp/yt-dlp/pull/6585#issuecomment-1483808528

**Comment by flisk** [comment]
there is no "creation time" on unix-like systems. you may be confusing "ctime" with "creation time". the latter is only used as such on windows. https://en.wikipedia.org/wiki/MAC_times#Change_time_and_creation_time_(ctime)

**Comment by dirkf** [comment]
True enough, but dependent on filesystem: this just shows that most of my media collection is on NTFS external disks.

The WP article reflects exactly the issue being discussed in #1709.

**Comment by flisk** [comment]
>I don't think it's obvious that

linux documents `st_mtime` in `stat(2)` as such:
>This is the time of last modification of file data.

`stat(2)` on macos documents `st_mtime` as such:
>Time when file data last modified.  Changed by the mknod(2), utimes(2) and write(2) system calls.

since this is the expected default behavior for `st_mtime`, i don't think it's reasonable to deviate from it unless the user has explicitly asked for that.

>If you want to know when a file was put on the disk, use its creation time.

`mtime` is not the same as creation time, it's for recording when the data of a file was last modified. the fact that `mtime` matches the time of file creation if the file hasn't been modified after its creation is incidental.

**Comment by dirkf** [comment]
The controversial point is whether the "time of last modification of file data" (and the equivalent text for macOS) means when the current bits were written to that file, or when the file data that was written was modified.

The latter interpretation avoids the need for filesystem tools to parse file content or extended attributes to determine the "content modification time".

**Comment by flisk** [comment]
there clearly isn't a single correct interpretation of what this attribute should be used for, and changing youtube-dl's default behavior now to align with a different interpretation now seems like a lateral move to me.

thanks for taking the time to discuss this.

**Pull request closed without merging**
