### PR TITLE
Add support for gaana.com

### PR DESCRIPTION
**Pull request by GourangaDas**
Hi!

As per request of [Gaana Support #12575](https://github.com/rg3/youtube-dl/issues/12575), I have tried to add the support of [gaana.com](https://gaana.com). It's the third time to make a better PR.
It currently support three types of url:

    https://gaana.com/song/-------------
    https://gaana.com/album/-------------
    https://gaana.com/artist/-------------

For single song:
`youtube-dl https://gaana.com/song/mera-dil-bhi-kitna-pagal-hai-1 -f best`

For all songs in the album:
`youtube-dl https://gaana.com/album/saajan-hindi -f best`

For all songs of the artist:
`youtube-dl https://gaana.com/artist/kumar-sanu -f best`

It will download song in .mp4 format.
Gaana.com uses various server as **vodhls-vh.akamaihd.net**, **cloudfront.net** and some others for hosting purpose and uses different algorithm to get it as far I have come to know. This infoextractor works only with 'vodhls-vh.akamaihd.net'. Support for other server will be implemented soon. The code has been checked with flake8. I have tested it from INDIA and works fine.
One more thing, I have just coded first time in Python, so the code may be non-smooth. It's a appeal to all maintainers and moderators of [youtube-dl](https://github.com/rg3/youtube-dl) to guide and help me to make myself suitable in this platform.  

Thanks all.

### CODE REVIEW

**Comment by GourangaDas** [comment]
Sir,
Thanks for your helpful review.
As much I've understood your guidence, I've reconstructed the code.

Supported url type:

```
https:/gaana.com/song/------
https:/gaana.com/album/------
https:/gaana.com/artist/------
https:/gaana.com/playlist/------
```

Basically, the webpages of above-said url-types are delivered in same way and style. It contains the related data of underlying songs in json format which are partially encrypted(method:CryptoJS.AES.encrypt, mode:CBC, pad:Pkcs7). Static key & iv are involved for decryption. But a few json info doesn't contain the urls of media. Then the media urls are usally captured in json format by posting a dymanic md5 string and some other data to a specific url. If I create a seperate info-extractor for playlist and call url_result() to create entries (i.e downloading the webpage for each song to get the info that are already in main webpage), then the process will consume data, time and much more. For this reason, I have written a single info-extractor that can deliver dynamic playlist result when required (means if the webpage contains more than one song's info).

For your reference:
https://css375.gaanacdn.com/min/?b=js&f=gaana.min.js&version=980.27&980.27
This js includes all the above-said method.

All print() function, used for debug, has been removed.

I know that my writing is also non-smooth like my code. Sorry for that.
Now, I am just waiting to hear you.
Thank you.

**Comment by arizzubair** [comment]
@GourangaDas can you provide a build for testing this?

**Comment by GourangaDas** [comment]
> 
> 
> @GourangaDas can you provide a build for testing this?

How?

**Comment by nikhgupta** [comment]
@arizzubair chiming in here. How can I help to get this merged into the core?

**Comment by arizzubair** [comment]
Never mind. I can simply check out this branch and run `python -m youtube_dl` to check whether gaana.com urls are working or not.

**Comment by nikhgupta** [comment]
Have a look at this PR instead: https://github.com/ytdl-org/youtube-dl/pull/22095
I know 2 PRs for the same extractor, but could not push to this PR obviously.

**Comment by captn3m0** [comment]
@GourangaDas Are you still working on this?

**Comment by Rubbesh** [comment]
❤️

**Pull request closed without merging**
