### PR TITLE
implement ThisVid extractor

### LINKED ISSUE #17713: [Site support request] ThisVid
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.09.26*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2018.09.26**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [ ] Bug report (encountered problems with youtube-dl)
- [x] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://thisvid.com/videos/im-back6/']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2018.09.26
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-91158-g63c4a4b0d6, ffprobe N-91158-g63c4a4b0d6
[debug] Proxy map: {}
[generic] im-back6: Requesting header
WARNING: Falling back on generic information extractor.
[generic] im-back6: Downloading webpage
[generic] im-back6: Extracting information
ERROR: Unsupported URL: https://thisvid.com/videos/im-back6/
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\YoutubeDL.py", line 792, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\common.py", line 507, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpcaq35cl9\build\youtube_dl\extractor\generic.py", line 3298, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://thisvid.com/videos/im-back6/
...
<end of log>
```

---

### If the purpose of this *issue* is a *site support request* please provide all kinds of example URLs support for which should be included (replace following example URLs by **yours**):
- Single video: https://thisvid.com/videos/blatino-foot-flash-42/
- Channel: https://thisvid.com/members/516677/
- Category: https://thisvid.com/categories/gay-feet/
- Playlist: https://thisvid.com/playlist/45051/video/smoke-break2/

Note that **youtube-dl does not support sites dedicated to [copyright infringement](https://github.com/rg3/youtube-dl#can-you-add-support-for-this-anime-video-site-or-site-which-shows-current-movies-for-free)**. In order for site support request to be accepted all provided example URLs should not violate any copyrights.

---

### Description of your *issue*, suggested solution and other information

Site is not supported. Videos are easy to download manually by using the in-built network log of Chrome.

### PR DESCRIPTION
**Pull request by rigstot**
deobfuscates the video URL using a reverse engineered version of KVS
player's algorithm. This was tested against version 4.0.4, 5.0.1 and
5.1.1.4 of the player and a warning will be issued if the major version
changes.

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

I managed to f--- up #21651 by pushing a grafted repository, hence the new PR. no functional changes, but updated the version check. This PR obsoletes / closes #20940 and closes #17713. For this extractor I have reverse-engineered how the URLs are generated and recreated the algorithm in python. #20940 chose to outsource this task to phantomJS, which may not be available on every users' system.

re-ccing @jhwgh1968 @fusey-may2020 @dstftw

### CODE REVIEW

**Comment by rigstot** [comment]
I cannot reproduce this, @jhwgh1968. can you please try again with --verbose? 

```
$ ./__main__.py https://thisvid.com/videos/black-converse-and-super-skinny-jeans
[ThisVid] black-converse-and-super-skinny-jeans: Downloading webpage
[download] Destination: Black converse and super skinny jeans-2044785.mp4
[download]   8.4% of 23.75MiB at  3.36MiB/s ETA 00:06^C
ERROR: Interrupted by user

**Comment by jhwgh1968** [comment]
Verbose did not display the cause of issue, but looking at the page did:

```
<script type="text/javascript" src="https://thisvid.com/player/kt_player.js?v=5.1.1.4"></script>
```

That doesn't match the regex, due to the fourth digit. Manually patching in version 5.1.1 with the Python debugger made the download succeed.

Perhaps the regex should be loosened to `version=((\d\.)+\d)`?

**Comment by rigstot** [comment]
I believe you might are still looking at the old PR's code. The regex in this version is already (nearly) exactly what you suggested

**Comment by jhwgh1968** [comment]
Whoops, you're right! My bad.

LGTM.

**Comment by master-leonardo** [comment]
i've been waiting for this for a long time!
While we are at it, do you think you could create one where we download a whole profile? as in, mainly public videos.

**Comment by rigstot** [comment]
Thanks @kubosho112 for noticing the test failure. I updated the test to a non-NSFW video from the front page.

@master-leonardo: This looks like it's not very hard to implement, but I will not do it before this PR is merged (I don't want to waste my time). If you are using GNU/Linux, you can use this CURL pipeline to download public videos (the example downloads pages 1 to 10 of a random channel. the range is interpreted by curl, not the shell):

       curl -s 'https://thisvid.com/members/1242462/public_videos/[1-10]/' | grep ' class="tumbpu">' | cut -d'"' -f2 | xargs ./youtube_dl/__main__.py

ping, @dstftw: pepole are interested in this, please consider merging!

**Comment by kubosho112** [comment]
> Thanks @kubosho112 for noticing the test failure. I updated the test to a non-NSFW video from the front page.
> 
Just run the test, and it works fine. Thanks!
I'm trying to download one video and it keep saying kvs-version error, and I guess its because the kvs-version of the video is 5.2.0. I think probably I need new extractor code maybe?

**Comment by rigstot** [comment]
The kvs-version is the same for every video at the same time. I could not reproduce your issue. Can you post the link you have problems with?

**Comment by master-leonardo** [comment]
i have been using this extractor from _blackjack4494/yt-dlc_ fork, it's working great.
@rigstot did you create one to download a full profile?

**Pull request closed without merging**
