### PR TITLE
[metaebene] new extractor for metaebene podcasts

### PR DESCRIPTION
**Pull request by kayb94**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)

### What is the purpose of your *pull request*?
- [x] New extractor

---

### Description of your *pull request* and other information

Metaebene.me is the website of a podcast producer, whose podcasts all have the same kind of webpage. This is an extractor for them.

### CODE REVIEW

**Comment by kayb94** [comment]
I found a mistake, please wait for the next commit (today). Just a small thing.

Regards

**Comment by kayb94** [comment]
Good now from my side!

Regards

**Comment by kayb94** [comment]
@dstftw
Is this merge request acceptable, or shall I improve something?

**Comment by kayb94** [comment]
In case you studied some of the unit tests and wondered, why the extractor is neccessary, when there already is a download button: It requires JS, which of course every user of NoScript and similar tries to circumvent.
Would be great, if this would become available for others, too (and #15873) :) If anything speaks against that, I'd be glad to hear.
I've been using the branch since March multiple times a week and it never failed so far.

Regards

**Comment by duracell** [comment]
@rg3 Is nobody active anymore in reviewing PR?

**Comment by rg3** [comment]
Pinging @dstftw again just in case...

**Comment by dstftw** [comment]
This extraction approach should go in the generic extractor.

**Pull request closed without merging**
