### PR TITLE
[instagram] fix retrieving video URL when logged in (with cookies)

### PR DESCRIPTION
**Pull request by Tatsh**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Instagram now (maybe only sometimes) puts the video information in another JSON dictionary used in a call to `window.__additionalDataLoaded()`.

### CODE REVIEW

**Comment by dstftw** [comment]
1. Post concrete example URLs of what this is supposed to fix.
2. Add tests.

**Comment by Tatsh** [comment]
This applies to any current URL when using cookies to be logged in.

I am doing so because I am processing a batch of URLs where some posts may be non-public. I don't know how I can add tests for a logged in state.

**Review by deepak-quo — APPROVED** [review]

**Comment by Kikobeats** [comment]
please merge 🙏

**Comment by Tatsh** [comment]
Can GitHub fix branch/repo references? I got my youtube-dl repository back and I'm pushing my branches back up but it still says 'unknown repository' here. That links to a non-existent branch.

**Comment by Tatsh** [comment]
@dstftw If you want me to make changes, I'll need to re-make this PR. I asked GitHub and they cannot fix branch references.

**Pull request closed without merging**
