### PR TITLE
Pad fragment data to the appropriate AES blocksize

### PR DESCRIPTION
**Pull request by kevinoconnor7**
### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Pads fragment data out to the AES-128 block size of 16 using PKCS#7 padding. This generally shouldn't be an issue for real downloads unless we've gotten truncated data somehow, but for tests the data is trimmed to exactly 10241 bytes and `10241 % 16 == 1` so we end with a malformed trailing block. This makes it impossible to run with `--test` or have extractor unit tests pass when the data being processed is encrypted with AES-128. Without this change you'll end up with an error like:

```
  File "/Users/kevinoconnor/Development/youtube-dl/youtube_dl/downloader/hls.py", line 182, in real_download
    decrypt_info['KEY'], AES.MODE_CBC, iv).decrypt(frag_content)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length
```

I didn't add explicit new tests for this as there's currently no unit tests for this file and (in theory) existing extractor tests will exercise this code (ex. #27621 tests only pass with this change).

### CODE REVIEW

**Comment by dstftw** [comment]
That's not acceptable. Data being downloaded must stay intact. What's really should be done in this case is disabling decryption while in test. There is a WIP PR #21962 with such changes.

**Comment by kevinoconnor7** [comment]
I see two issues with those suggestions: the former doesn't actually verify that the decryption key is correct in tests, and the latter just punts on test coverage entirely.

Alternatively, I could amend this change to only pad for when `test` is `true`. Since it's the trailing block it shouldn't matter if we pad it out, especially if we do it consistently for tests.

**Comment by dstftw** [comment]
This main point of md5 file tests is to test that downloaded data matches not to test how decryption works.

**Comment by kevinoconnor7** [comment]
Fair enough. Given that #21962 seems to have stalled I'll split of that specific portion into a separate PR.

**Pull request closed without merging**
