### PR TITLE
Add support for LBRY

### LINKED ISSUE #23695: Add support for lbry.tv
## Checklist

- [x] I'm reporting a new site support request
- [x] I've verified that I'm running youtube-dl version **2020.01.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that none of provided URLs violate any copyrights
- [x] I've searched the bugtracker for similar site support requests including closed ones

## Example URLs

- Single video: https://lbry.tv/@christitustech:5/lbry-vs-youtube:e
- Single video: https://lbry.tv/@Lunduke:e/lbry-the-viable-youtube-alternative-in:4
- Single video: https://lbry.tv/@DesktopMonologues:b/why-windows-users-are-switching-to-linux:2

## Description

lbry.tv is a new open-source video publishing site. The site is still a bit funky, sometimes videos load on the first try sometimes not, and sometimes they fail halfway through watching them.

### PR DESCRIPTION
**Pull request by vedranmiletic**
### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [X] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Add support for extracting videos from [LBRY](https://lbry.tv/) (fixes #23695).

### CODE REVIEW

**Comment by metalx1000** [comment]
I'm running the current Version of Youtube-dl (2020.03.24).
When trying to run it using an LBRY url I get the following erro
`youtube-dl "https://lbry.tv/@metalx1000:c/april-fools-follow-up:1"             
[generic] april-fools-follow-up:1: Requesting header
WARNING: Falling back on generic information extractor.
[generic] april-fools-follow-up:1: Downloading webpage
[generic] april-fools-follow-up:1: Extracting information
[generic] 17ad9eb9a2acc8a7309ec30359ed6a09bbce8a2e: Requesting header
WARNING: Falling back on generic information extractor.
[generic] 17ad9eb9a2acc8a7309ec30359ed6a09bbce8a2e: Downloading webpage
[generic] 17ad9eb9a2acc8a7309ec30359ed6a09bbce8a2e: Extracting information
ERROR: Unsupported URL: https://lbry.tv/$/embed/april-fools-follow-up/17ad9eb9a2acc8a7309ec30359ed6a09bbce8a2e`

Which is very close to the proper link.  The error says:
https://lbry.tv/$/embed/april-fools-follow-up/17ad9eb9a2acc8a7309ec30359ed6a09bbce8a2e

The correct download link is the same, but with 'download' in place of 'embed'
https://lbry.tv/$/download/april-fools-follow-up/17ad9eb9a2acc8a7309ec30359ed6a09bbce8a2e

**Comment by vedranmiletic** [comment]
@metalx1000 That's expected as the code has not been merged yet.

**Comment by Mati20187** [comment]
I hope youtube-dl devs will merge it soon. LBRY support is very much needed

**Comment by vedranmiletic** [comment]
> I hope youtube-dl devs will merge it soon. LBRY support is very much needed.
> I've just tested your code and it works perfectly. Amazing job!

Glad to hear it's still working as I expect LBRY to change over time potentially in a breaking way.

**Comment by vedranmiletic** [comment]
@dstftw is there anything else I have to do to get this considered for merging?

**Comment by MarcinWieczorek** [comment]
This patch works great for http urls. Is there a chance for `lbry://` urls to be implemented too?
Good job.

**Comment by vedranmiletic** [comment]
> This patch works great for http urls. Is there a chance for `lbry://` urls to be implemented too?
> Good job.

Yeah, that should be pretty straightforward. I'll see if I can get it done this week.

**Comment by r3k2** [comment]
yay! is this on master yet?

**Comment by MarcinWieczorek** [comment]
> yay! is this on master yet?

I don't think so, you can patch it yourself and provide feedback. (adding `.patch` to the end of PR's url is a nice trick)

**Comment by r3k2** [comment]
> > yay! is this on master yet?
> 
> I don't think so, you can patch it yourself and provide feedback. (adding `.patch` to the end of PR's url is a nice trick)

haha is not for me, some services I use like mozilla hubs and peertube use youtube-dl libs under it to import videos etc... so now I can import into peertube from youtube but I cant import from lbry, so when I upload one video to one service with this path I can  use the import feature to auto import to other places from lbry.

**Comment by kauffj** [comment]
Hi @vedranmiletic -- I'm the CEO of LBRY and just wanted to let you know we're friendly to this kind of thing

Come by our chat (if you're not there already) and say hi to me (@kauffj). I'll send you some LBC.

**Comment by Tatsh** [comment]
I am getting a timeout on the call to `player.lbry.tv/content/claims/<name>/<hash>/stream?download=1`. I do not think the call to `/content/claims` is necessary.

I have had no issue with generating a URL with the CDN name (which generally stays the same) and a random value at the end before `?download=true`.

The format is:

```
https://cdn.lbryplayer.xyz/api/v3/streams/free/<username without @>/<video hash>/<random 6 chars a-f0-9?>?download=true
```

The CDN could be figured out from regex'ing the JS.

**Comment by Tatsh** [comment]
I would make the following changes:

```patch
diff --git a/youtube_dl/extractor/lbry.py b/youtube_dl/extractor/lbry.py
index 6a609e5a6..dc72baa55 100644
--- a/youtube_dl/extractor/lbry.py
+++ b/youtube_dl/extractor/lbry.py
@@ -1,8 +1,10 @@
 # coding: utf-8
 from __future__ import unicode_literals
 
+import random
 import re
 
+from ..utils import mimetype2ext
 from .common import InfoExtractor
 
 
@@ -42,16 +44,15 @@ class LBRYIE(InfoExtractor):
             self._og_search_property('twitter:player', webpage)
 
         video_id = embed_url.split('/')[-1]
+        slug = embed_url.split('/')[-2]
+        suffix_chars = list(range(48, 59)) + list(range(97, 123))
 
-        video_type = self._og_search_property('video:type', webpage)
-        video_ext = video_type.replace('video/', '')
-
-        format_url = embed_url.replace('lbry.tv/$/embed', 'player.lbry.tv/content/claims') + '/stream?download=1'
-        formats = [{'ext': video_ext, 'url': format_url, 'vcodec': 'h264', 'acodec': 'aac'}]
+        format_url = 'https://cdn.lbryplayer.xyz/api/v3/streams/free/%s/%s/%s?download=true' % (
+            slug.split(':')[0], video_id, ''.join(chr(random.choice(suffix_chars)) for x in range(7)))
+        formats = [{'ext': mimetype2ext(self._og_search_property('video:type', webpage)), 'url': format_url, 'vcodec': 'h264', 'acodec': 'aac'}]
 
         return {
             'id': video_id,
-            'ext': video_ext,
             'title': title,
             'title_url': title_url,
             'thumbnail': thumbnail,
```

**Comment by Lamieur** [comment]
Tatsch's fix works.

I just added odysee.com to the list:

`    _VALID_URL = r'https?://(?:www\.)?(lbry\.tv|odysee\.com)/@(?P<uploader_url>[^/?#&]+:[0-9a-f]+)/(?P<title_url>[^/?#&]+:[0-9a-f]+)'`

and the fixed extractor works fine for Odysee as well. In fact, maybe the extractor itself should be renamed to odysee.py, as  that's going to become the mainstream brand instead of lbry.tv.

**Comment by Lamieur** [comment]
@Tatsh
For the last two days I'm getting a '?' at the end of embed_url, so I did
`video_id = embed_url.split('/')[-1].split('?')[0]`
and it works again. Couldn't be arsed to look deeper where it's coming from, just a quick hack :)

**Comment by Tatsh** [comment]
@vedranmiletic are you planning to update this PR?

**Comment by vedranmiletic** [comment]
> @vedranmiletic are you planning to update this PR?

Sorry, I haven't been following this PR much. I'll update it in a few days.

**Pull request closed without merging**
