### PR TITLE
[sxyprn] Add new extractor

### PR DESCRIPTION
**Pull request by v-delta**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

As `yourporn.sexy` was renamed to `sxyprn.com` and all HTTP requests to `yourporn.sexy` are being 301-redirected to `https://www.youporn.com/?utm_source=yourporn.sexy&utm_medium=redirects&utm_campaign=tldredirects`, making `yourporn.sexy` unavailable, it makes sense to rename the according extractor as well.

This PR renames extractor `yourporn` to `sxyprn`and fixes the existing `video_url` extraction error.

### CODE REVIEW

**Comment by dstftw** [comment]
Do not touch extractor name.

**Comment by v-delta** [comment]
So you want to keep "YourPorn" as the extractor name although the site is not available under [https://yourporn.sexy](https://yourporn.sexy) anymore?

**Comment by dstftw** [comment]
I've already pointed out what I want. By changing extractor name you **break all existing download archives** for this extractor.

**Comment by v-delta** [comment]
Better?

**Pull request closed without merging**
