### PR TITLE
Added support for TVN (http://player.pl/)

### PR DESCRIPTION
**Pull request by pkilar**
Support for TVN. Please note that API key is required for this plugin to work.

### CODE REVIEW

**Comment by yan12125** [comment]
Any test case available outside Poland?

**Comment by dstftw** [comment]
Is it a duplicate of #6436?

**Comment by kasper93** [comment]
> Any test case available outside Poland?

No. It is against TOS to use this site outside Poland. All videos are geo restricted. 

Here is wording: 
```
10) Użytkownik Player.pl – Użytkownik korzystający z Serwisu Player.pl, przebywający na terytorium
Rzeczpospolitej Polskiej; 
```
Roughly it means that user can use this site only on territory of Poland.
Source: http://player.pl/regulamin.pdf

**Comment by yan12125** [comment]
Since #8497 landed, please move changes in ```youtube_dl/extractors/__init__.py``` to ```youtube_dl/extractors/extractors.py```. Check step 5 of the new [developer instructions](https://github.com/rg3/youtube-dl/blob/master/README.md#adding-support-for-a-new-site) for more information.

**Pull request closed without merging**
