### PR TITLE
[RaiPlay] New video json source

### PR DESCRIPTION
**Pull request by timendum**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Code changed because of changed logic on the site.

Also fixed invalid and valid test cases.

Note: partially overlaps with  #23040

### CODE REVIEW

**Comment by timendum** [comment]
Hi @dstftw, can you check this pull? Thanks.

**Comment by iamleot** [comment]
@timendum Hello!  Can you please elaborate further what's missing in #23040 and how to possibly merge the two PRs? (in the commit message there is no rationale and I think that #23040 address RaiPlayLiveIE and RaiPlayPlayListIE classes too that doesn't seem addressed by this PR)

**Comment by timendum** [comment]
@iamleot this pull is smaller, I'm hoping it will be simpler to review.

**Comment by iamleot** [comment]
I've just double-checked all the tests in #23040 and updated a test in RaiIE test and removed two tests that are no longer available.

@timendum you said that the pull request is smaller but it seems that this pull requests ATM adds 44 lines and removes 48 lines, while in #23040 49 lines are added and 78 lines are removed so, while #23040 diff is bigger the code in the rai extractor after applying the PR is smaller.

**Comment by de666** [comment]
@timendum I think this one should not overlap #23040 or #23040 should be included in this one because this one fixes the Base extractor but not the playlist extractor like #23040 does. So both patches are needed to make things working correctly for both items and playlists. Furthermore having only one PR means that you can apply the patch in your own build while you are waiting that is merged in the master branch (which in this case could be a very long time, as seen for #23040)

**Comment by remitamine** [comment]
There is a fix that has been applied to fix this raiplay.it support

**Pull request closed without merging**
