### PR TITLE
[Niconico] Back-port extractor and add new search extractors from yt-dlp

### LINKED ISSUE #14582: [niconico] Downloading long videos requires heartbeat signals
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Python Console:
youtube_dl.YoutubeDL({'username': "username",'password': 'password','verbose':True}).extract_info(url="http://www.nicovideo.jp/watch/sm29409391")

[debug] Encodings: locale cp1252, fs utf-8, out UTF-8, pref cp1252
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.6.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1619, in process_video_result
    self.process_info(new_info)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1892, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1831, in dl
    return fd.download(name, info)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\http.py", line 297, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 582, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries
```

### Description of your *issue*, suggested solution and other information

As of today, Nicovideo's seem to implemented a new session system. After every few minutes, the url of the video changes. This causes a 403 Forbidden error on the old url, Causing the Downloader to fail.
A screenshot of part of a video session:
chrome 2017-10-25 10 43 35 396

Resuming the download works just for a few minutes before the session is dropped.  
Note: I have only tested on a non-premium account. Im not sure if it applies to the permium accounts or not.

### LINKED ISSUE #19261: Unable to download from nicovideo.jp
### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [x] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
PS D:\Music> youtube-dl --verbose http://www.nicovideo.jp/watch/sm34642257
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'http://www.nicovideo.jp/watch/sm34642257']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2019.02.18
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg 4.0.2, ffprobe 4.0.2
[debug] Proxy map: {}
[niconico] sm34642257: Downloading webpage
[niconico] sm34642257: Downloading JSON metadata for h264_1080p-aac_192kbps
ERROR: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\extractor\common.py", line 605, in _request_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpw73a_6nx\build\youtube_dl\YoutubeDL.py", line 2225, in urlopen
  File "C:\Python\Python34\lib\urllib\request.py", line 470, in open
  File "C:\Python\Python34\lib\urllib\request.py", line 580, in http_response
  File "C:\Python\Python34\lib\urllib\request.py", line 508, in error
  File "C:\Python\Python34\lib\urllib\request.py", line 442, in _call_chain
  File "C:\Python\Python34\lib\urllib\request.py", line 588, in http_error_default
```

### Description of your *issue*, suggested solution and other information
For the past few days youtue-dl is unable to download most niconico videos.
URL example (not working): `http://www.nicovideo.jp/watch/sm34642257`
URL example (working): `http://www.nicovideo.jp/watch/sm34425299`

### LINKED ISSUE #24093: [niconico] Support encrypted official videos
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.02.16**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

I did a pull requests (https://github.com/ytdl-org/youtube-dl/pull/23824) before, but I'll post it to the issue just in case.

niconico (Nico Nico Douga) is not known outside of Japan, but is the largest video sharing site in Japan.

### Problem

niconico began using HLS to encrypt the distribution of some official videos, such as anime, on March 5, 2019.
As a result, some official videos can no longer be downloaded with the previously used Extractor.
(Example of video that can be downloaded as before: https://www.nicovideo.jp/watch/sm32868846)
(Example of video that cannot be downloaded due to HLS encryption: https://www.nicovideo.jp/watch/so36189921)

### Correction and resolution

The pull requests I mentioned earlier include an improvement that allows you to download niconico's encrypted HLS videos.
Specifically, it has been modified to make a request to the (most recently published) Ping API (otherwise the download will fail).
In addition, the encrypted HLS video has been modified to send different parameters to the API for acquiring the viewing session than the HTTP video.

On niconico, if you do not send a "heartbeat" every 60 seconds, the download session will be closed and a 403 error will occur.
Short videos can complete the download before the session closes, but long videos do not.
You can "resume" videos that support HTTP, but you can't resume videos that are HLS only.
Therefore, it is necessary to implement a "heartbeat".

The pull requests also include a change that allows you to send a "heartbeat" once every 60 seconds during the download, and to download long videos to the end.
I understand that although some pull requests implementing "heartbeat" have been sent in the past, such as https://github.com/ytdl-org/youtube-dl/issues/14582, they have not been merged even now doing.
The code for "heartbeat" is based on https://github.com/archiif/youtube-dl/pull/1/commits/84995347fccc12f588efe59540418b9070a3c177.
I tried it on various video sites, but adding this feature will not hinder other sites from downloading.
Also, since February 2018, it has been improved to play videos without logging in, so you do not need an account to download.

### lastly

As a side change, we made changes to get high quality thumbnails and original titles.
In addition, support for "heartbeat" has made it easier to download normal niconico HTTP videos (especially long videos) as a side effect, eliminating the need to "resume".

I strongly hope that this change will be incorporated into the project.
Can you merge this (https://github.com/ytdl-org/youtube-dl/pull/23824) Pull requests?

Thank you.

(Sentence may be a bit strange because I am using translation)

### LINKED ISSUE #29225: nicovideo.jp issue
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\XXXXX>"C:\Users\XXXXX\Desktop\Video Tools\Youtube DL\youtube-dl.exe" --verbose  https://www.nicovideo.jp/watch/sm12134023
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nicovideo.jp/watch/sm12134023']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[niconico] sm12134023: Downloading webpage
[niconico] sm12134023: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\niconico.py", line 291, in _real_extract
KeyError: 'smileInfo'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\niconico.py", line 291, in _real_extract
KeyError: 'smileInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpkqxnwl31\build\youtube_dl\extractor\niconico.py", line 310, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

## Description

Unable to download from the above website. Related bugs suggest problems with downloading speeds or requiring a login. Neither of those issues appear to be related to the problem I am having.

### LINKED ISSUE #29974: Unable to download from Nicovideo (NicoNico)
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.06.06**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.nicovideo.jp/watch/sm38036476', '-u,', '--username', 'PRIVATE']
Type account password and press [Return]:
[debug] Encodings: locale cp936, fs utf-8, out utf-8, pref cp936
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.6 (CPython) - Windows-10-10.0.19042-SP0
[debug] exe versions: ffmpeg git-2020-06-23-ce297b4, ffprobe git-2020-06-23-ce297b4
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm38036476: Downloading webpage
[niconico] sm38036476: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Unable to download even with -u command
Type account password and press [Return]:
[niconico] Logging in
[niconico] sm38036476: Downloading webpage
[niconico] sm38036476: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

WRITE DESCRIPTION HERE

### LINKED ISSUE #30003: Nicovideo; Unable to find URL
`[niconico] sm17195023: Downloading webpage
[niconico] sm17195023: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.`
Here is a full screenshot, and proof that i am in the latest version as of now.
Image

### LINKED ISSUE #30316: niconico dl not working
for link: https://www.nicovideo.jp/watch/sm12745574

```
aceldama@DietPi3LLMP:~/mnt/hdd-a/music/000-new $ youtube-dl https://www.nicovideo.jp/watch/sm12745574 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nicovideo.jp/watch/sm12745574', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.2 (CPython) - Linux-5.10.63-v7+-armv7l-with-glibc2.31
[debug] exe versions: ffmpeg 4.3.3-0, ffprobe 4.3.3-0
[debug] Proxy map: {}
[niconico] sm12745574: Downloading webpage
[niconico] sm12745574: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 291, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'smileInfo'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 291, in _real_extract
    video_real_url = api_data['video']['smileInfo']['url']
KeyError: 'smileInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/niconico.py", line 310, in _real_extract
    raise ExtractorError('Unable to find video URL')
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

aceldama@DietPi3LLMP:~/mnt/hdd-a/music/000-new $
```

### LINKED ISSUE #30395: [Niconico]Unable to find video URL
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

D:\>youtube-dl --version
2021.12.17

D:\>youtube-dl "https://www.nicovideo.jp/watch/sm34923907"
[niconico] sm34923907: Downloading webpage
[niconico] sm34923907: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

D:\>youtube-dl "https://www.nicovideo.jp/watch/sm34923907" --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.nicovideo.jp/watch/sm34923907', '--verbose']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.4-full_build-www.gyan.dev, ffprobe 4.4-full_build-www.gyan.dev
[debug] Proxy map: {}
[niconico] sm34923907: Downloading webpage
[niconico] sm34923907: Downloading flv info
ERROR: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\niconico.py", line 291, in _real_extract
KeyError: 'smileInfo'
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\niconico.py", line 291, in _real_extract
KeyError: 'smileInfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 815, in wrapper
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 836, in __extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\common.py", line 534, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\extractor\niconico.py", line 310, in _real_extract
youtube_dl.utils.ExtractorError: Unable to find video URL; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


D:\>
```

## Description

If my memory is certain, this software about 2 years ago used to be able to download NiconicoVideo.
However, after that, although it became impossible to download, it was possible to download by using aria2c until around version 2021.4.26.
After that, I tried various things, but I couldn't download it anymore. And that's still going on as of version 2021.12.17.
My English is so poor, I'm sorry...

### PR DESCRIPTION
**Pull request by dirkf**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

The  Niconico extractor has been broken following site changes, and also served files that couldn't be downloaded in a single yt-dl run because the server cancelled the download in the absence of a regular heartbeat POST.

The corresponding module in yt-dlp has been actively maintained and additional search extractors have been implemented, as well as adding support for the heartbeat function for downloads.

This PR adapts the current version of the yt-dlp module to yt-dl conventions, in particular replacing `f'strings'` and `yield from`.

The playlist limit in download tests from yt-dlp is implemented.

Additionally, if the optional `threading` module is available, the heartbeat function is enabled for DMC-type downloads. This requires a small change to `downloader/__init__.py`

Credit goes to @CXwudi, @animelover1984 and @pukkandan for recent changes on the yt-dlp version, and see also [below](https://github.com/ytdl-org/youtube-dl/pull/30329#issuecomment-988158605) for other contributors.

The PR should fix these issues where extraction failed:
* resolve #29225
* resolve #29974
* resolve #30003
* resolve #30316
* resolve #30395.

The PR should fix these issues where downloading needed a heartbeat:
* resolve #14582
* resolve #19261
* resolve #24093.

### CODE REVIEW

**Comment by horahoradev** [comment]
(I'm animelover1984)
This repo has 900 unmerged PRs... isn't this an exercise in futility?

**Comment by dirkf** [comment]
This isn't the only place where PRs might be merged, but they're here for the record. The discussion about the value of the yt-dl has already been well covered [elsewhere](https://github.com/ytdl-org/youtube-dl/issues/29965).

**Comment by pukkandan** [comment]
The `niconico_dmc` formats won't download without also implementing "heartbeat" logic to the downloader. See https://github.com/ytdl-org/youtube-dl/issues/14582 and the many associated issues/PRs

**Comment by pukkandan** [comment]
btw, large parts of this code should be attributed to @bbepis, @kurumigi and @tsukumijima as well. See the file history on yt-dlp for details

**Comment by dirkf** [comment]
Thanks, I only went back through the committers to the point where the page format broke but happy to acknowledge all the above.

The heartbeat feature was never merged in yt-dl  but the yt-dlp solution of defining a custom download protocol is cleaner than any of the proposals on the yt-dl table, so I've pulled in a minimal version of that too. If the (optional for Py < 3.7) `threading` module should be absent, the PR falls back to the non-heartbeat mode in case it can be made to work by eg [repeatedly running yt-dl until the whole file has been acquired](https://github.com/ytdl-org/youtube-dl/issues/19261#issuecomment-476604716).

**Comment by bbepis** [comment]
While I appreciate the effort, this will most likely never get merged. Even when this repo had many active maintainers, NND related PRs were *actively* being ignored.

There are PRs that are older than elementary school kids which have been locked, and comments by @horahoradev deleted mentioning that these changes have been included in another fork.

I've never been sure why this has been the case, but I'm guessing it's because a maintainer commented that you could run ytdl in a bash script, repeating until it returned a successful error code. And that was a "good enough" fix

**Comment by dirkf** [comment]
If a shell script was good enough, why isn't yt-dl just a shell script around `wget` or `curl`? Obviously not.

The maintainers seem to have been unhelpful at least, but I can see why they weren't keen to merge either of the PRs linked from #14582 one as-is. It looks like the first one fell when the lead maintainer moved on, and the later one put the NND heartbeat logic in the core `YoutubeDL.py`, which was never going to be acceptable, though no-one got around to saying so in a review.

The solution with a custom downloader protocol handles NND with a small change to the downloader module and can be extended to another site that imposes weird downloading requirements with a site-specific module just as for extraction, not tied to the NND heartbeat. Big win, and congratulations to those who put the design in place.

Regardless of merging here, Niconico fans can update their yt-dl by pip-ing a checkout of the repo, or otherwise.

**Comment by horahoradev** [comment]
> Regardless of merging here, Niconico yt-dl fans can update their yt-dl by pip-ing a checkout of the repo, or otherwise.

Why wouldn't they just use yt-dlp?

**Comment by dirkf** [comment]
Because they're **yt-dl fans**, obvs. You'd have to ask them why, but possible reasons are mentioned in the [issue linked above](https://github.com/ytdl-org/youtube-dl/issues/29965).

**Comment by Ashish0804** [comment]
@dirkf I'm genuinely curious as to why haven't you made your own fork (something like yt-dld) instead of making PRs here which would never be merged and at best best closed without any explanation? 🤔 
At least then people who want these sites and py2 support won't have to manually merge and resolve conflicts.

**Comment by dirkf** [comment]
I have a private version but it's not fit to release and only has a few PRs of interest to me merged. Maybe when time permits and if @maintainers never reappear ...

**Pull request merged**
