### PR TITLE
[tiktok] Support watermarkless tiktok videos

### PR DESCRIPTION
**Pull request by runraid**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This updates the tiktoc downloader to download the non-watermarked video.

Feature request here https://github.com/ytdl-org/youtube-dl/issues/20644

### CODE REVIEW

**Comment by karottenbaum** [comment]
For me, the extractor throws an unhelpful "ERROR: substring not found" on some videos that are still available, apparently just not without a watermark (ex. https://www.tiktok.com/@daviidmitchell/video/6855340347090898182):

```
[TikTok] 6855340347090898182: Downloading webpage
[TikTok] 6855340347090898182: Downloading webpage
ERROR: substring not found
Traceback (most recent call last):
  File "/media/sg/youtube_dl_proc/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/media/sg/youtube_dl_proc/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/media/sg/youtube_dl_proc/youtube-dl/youtube_dl/extractor/tiktok.py", line 55, in _real_extract
    idpos = watermarked_response.index("vid:")
ValueError: substring not found
```

My environment: Python 3.7.3, Debian 10

**Comment by qsniyg** [comment]
Videos uploaded after July 27th remove the vid:[id]{32} comment unfortunately. It should still work for older videos though.

**Comment by notpushkin** [comment]
Would be nice to have watermarkless downloads as a separate format for those videos which support it! (Possibly after #22838 gets merged)

**Comment by makeworld-the-better-one** [comment]
@runraid @karottenbaum @qsniyg Downloading recent videos without the watermark should also be possible, I've been able to do it with a site like https://ttdownloader.com/.

**Comment by qsniyg** [comment]
@makeworld-the-better-one Yes, but IIRC this requires the mobile APIs, which would require a username and password. It's probably not _impossible_ for youtube-dl to support it, but it's likely going to be a really hard challenge.

**Comment by makeworld-the-better-one** [comment]
Ah so that site is using their own account then? Also youtube-dl supports authentication options like `--username` and `--password`, so that feature could be added. No idea how hard the code would be though.

**Pull request closed without merging**
