### PR TITLE
[youtube] Fix extracting YouTube search URLs and feeds

### LINKED ISSUE #25696: Request like this dont' work youtube.com/results?search_query=...
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
>youtube-dl -v "https://www.youtube.com/results?search_query=HYPNODANCER"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/results?search_query=HYPNODANCER']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:search_url] HYPNODANCER: Downloading webpage
[download] Downloading playlist: HYPNODANCER
[youtube:search_url] playlist HYPNODANCER: Downloading 0 videos
[download] Finished downloading playlist: HYPNODANCER
```
BUT THIS WORK FINE!
```
>youtube-dl -v ytsearchdate15:HYPNODANCER
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'ytsearchdate15:HYPNODANCER']
[debug] Encodings: locale cp1251, fs mbcs, out cp866, pref cp1251
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg N-89794-gc51301db14, rtmpdump 2.4
[debug] Proxy map: {}
[youtube:search:date] query "HYPNODANCER": Downloading page 1
[download] Downloading playlist: HYPNODANCER
[youtube:search:date] playlist HYPNODANCER: Collected 15 video ids (downloading 15 of them)
[download] Downloading video 1 of 15
[youtube] dxVmmmlJGyA: Downloading webpage
...
```
## Description

Earlier, a search using the link to the search page on Youtube worked fine, but yesterday all such queries began to produce empty values. I can use the youtube-dl query language, but there’s no way to use ALL the search filters that Youtube offers. I tried to fulfill requests both using cookies (with authorization) and without it. if it’s not difficult, then add a detailed description of the use of keywords to the documentation and add to them all that youtube offers. thank.

### PR DESCRIPTION
**Pull request by xarantolus**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix (closes #25696, #25695)
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description
URLs like `https://www.youtube.com/results?search_query=test` have been broken for a few days since the data is now in a JSON object instead of being embedded into the HTML of the search page.

Now the `window["ytInitialData"]` variable is extracted and then searched recursively for any object containing the key `videoId`. These objects are all over the place in the JSON document.

The change also affects feed urls like `https://www.youtube.com/feed/subscriptions`, `https://www.youtube.com/feed/history` etc. For those the same logic is implemented. 

Subscriptions additionally contain a `nextContinuationData` object that is then used (in combination with data from a `ytcfg.set` call from a script in the page) to make a request to fetch the next pages.

#### TODO / Requests for input
- [ ] Some regexes feel like they are easy to break, so if they should be more general please let me know how.
- [ ] Maybe implement continuations for other feeds?

Please feel free to point out anything that doesn't seem right

### CODE REVIEW

**Comment by scout719** [comment]
I also have a similar problem when extracting the videos from the subscriptions page. After inspecting the page I think the `window["ytInitialData"]` variable is also used to list the videos. Can you try to also fix the subscriptions extractor? Thank you!

**Comment by xarantolus** [comment]
I tried it, but the login using cookies doesn't seem to work right now (see #24508).

When I set a breakpoint in line 3226 and replace the `page` variable with the content of the subscription page I get in my browser, the extraction part of this pull request *does not* work and throws this error:

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.youtube.com/results?search_query=raf+camora']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Git HEAD: 6dad89289
[debug] Python version 3.6.6 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg N-93083-g8522d219ce, ffprobe N-93083-g8522d219ce, phantomjs 2.1.1
[debug] Proxy map: {}
[youtube:search_url] raf camora: Downloading webpage
[download] Downloading playlist: raf camora
ERROR: None: Failed to parse JSON  (caused by JSONDecodeError("Expecting ',' delimiter: line 1 column 5076 (char 5075)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\__init__.py", line 354, in loads    
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 339, in decode    
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5076 (char 5075)
Traceback (most recent call last):
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\extractor\common.py", line 899, in _parse_json
    return json.loads(json_string)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 5076 (char 5075)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\YoutubeDL.py", line 969, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\extractor\youtube.py", line 329, in _process_page
    for video_id, video_title in self.extract_videos_from_page(content):
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\extractor\youtube.py", line 3253, in extract_videos_from_page
    self.extract_videos_from_page_impl(page, ids_in_page, titles_in_page)
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\extractor\youtube.py", line 3226, in extract_videos_from_page_impl
    search_response = self._parse_json(self._html_search_regex(self._SEARCH_DATA, page, 'ytInitialData'), None)
  File "D:\Bibliotheken\Desktop\contrib\youtube-dl\youtube_dl\extractor\common.py", line 903, in _parse_json
    raise ExtractorError(errmsg, cause=ve)
youtube_dl.utils.ExtractorError: None: Failed to parse JSON  (caused by JSONDecodeError("Expecting ',' delimiter: line 1 column 5076 (char 5075)",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

So this isn't easily transferable to other feeds. The search urls work though

**Comment by scout719** [comment]
> I tried it, but the login using cookies doesn't seem to work right now (see #24508).
That's weird, I have it working here, with cookies. When I run with the subscriptions url and use `--dump-page` I get the correct page source

**Comment by xarantolus** [comment]
When I tried extracting cookies using another browser, it worked and logged me in correctly, so there's no issue in that part.

I fixed the extraction part for these feeds (history, subscriptions, recommended), but it will only download the first page now. 

There *sometimes* is an object called `continuationItemRenderer` that contains some stuff that is then POSTed somewhere to load additional videos, but I couldn't figure out how that one works. One would need to extract an api key that is somewhere in the `window.ytplayer` object in the page source.

If you want to try out the current version (and installed over pip):

    pip3 install -U git+https://github.com/xarantolus/youtube-dl@fixYTSearch

**Comment by scout719** [comment]
> When I tried extracting cookies using another browser, it worked and logged me in correctly, so there's no issue in that part (probably some issue when using firefox containers and cookie extraction extensions?).

Could be, I extracted mine using Chrome

> I fixed the extraction part for these feeds (history, subscriptions, recommended), but it will only download the first page now.

Awesome! It works now, thank you so much! 💪

At least for me the first page is enough. Don't forget to update the description on the PR to mention this limitation

**Comment by AthenaAzuraea** [comment]
Downloading youtube subscriptions worked with this yesterday, but today something seems to have broken:

[debug] System config: []
[debug] User config: ['-f', 'bestvideo[height<=1080]+bestaudio/bestvideo+bestaudio/best', '--merge-output-format', 'mkv', '--sub-lang', 'enUS', '--write-sub', '-i', '-o', '%(uploader)s - %(title)s.mkv', '--no-playlist', '--mark-watched', '--reject-title', 'English dub|Portuguese Dub|Spanish Dub|(Live)|Spawncast|(Charity stream)| Podcast | (Dub) |WAN Show|Broken Silicon']
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://www.youtube.com/feed/subscriptions', '--cookies', 'Cookies.txt']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.06.16.1
[debug] Python version 3.8.3 (CPython) - Windows-10-10.0.18362-SP0
[debug] exe versions: ffmpeg 4.2.3, ffprobe 4.2.3
[debug] Proxy map: {}
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
ERROR: Unable to extract ytInitialData; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Essen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Essen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\YoutubeDL.py", line 968, in process_ie_result
    entries = list(itertools.islice(
  File "C:\Users\Essen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\youtube.py", line 3325, in _entries
    search_response = self._parse_json(self._search_regex(self._FEED_DATA, page, 'ytInitialData'), None)
  File "C:\Users\Essen\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by xarantolus** [comment]
Yeah, it seems like they changed the format to the old one again. With the old code the extraction will work, but it will extract an seemingly infinite number of video pages instead of downloading any videos.
I reverted my changes and added a default limit of 1000 videos that will be extracted before the download starts, but it can also be adjusted with the `--max-downloads` option. This limit is a temporary solution, it's not optimal.
It might be necessary to wait until youtube finalizes their changes as they seem to change stuff every few hours.

**Comment by bungarayasdk** [comment]
Hello bro How to Fix com.google.android.youtube

**Comment by bungarayasdk** [comment]
Check my website https://www.vivo.com/sa/ar/index/countrys what the problems youtube.com

**Comment by glenn-slayden** [comment]
FWIW, there is an interaction when `?disable_polymer=true` (or `1`) appears in the initial URL. As you know, playlists which have more than 100 videos are listed via chained continuation URLs. Previously, the first 100 got special extraction treatment, since that item data was rendered in HTML rather than JSON. The remaining files were then extracted via chained JSON fetches 100 at a time. 

So regarding the new change, if `window["ytInitialData"]` is found in the initial HTML file it means that you won't find any HTML item data any more. I have found that you can reliably extract the new JSON chunk by selecting within the entire HTML content from the point of `window[\"ytInitialData\"]` ...to the ***first match*** of `};` beyond that point. As before, this is valid JSON for the initial up to 100 items. It also still contains a continuation URL if further iteration is needed.

The problem with using `?disable_polymer=true` (which **youtube-dl** does specify when downloading playlists) is that even with that option you will still occasionally get the new `window["ytInitialData"]` format--but **some of those times**, the JSON data island will be16 bytes of JSON data, basically something like `{ reload now }`. I haven't figured out how to recover any data (or a continuation URL) in this sub-case, but my point here is that that bad sub-case appears to **never happen** if `?disable_polymer=true` is omitted (or `false / 0`).

**Comment by marabu88** [comment]
almost 2 weeks this problem continues. Is there any alternative method to get a video ID from an arbitrary search query with various parameters? I am beginning to fear that the search function will not be fixed.

I heard that it is possible to load a page into a browser object and receive an already processed version of the page with all the necessary links. can this option be used or will it be too cumbersome?

**Comment by milahu** [comment]
> With the old code the extraction will work,

yes, commit 7a74feda7837bc54b6b0ccfed980ca9bf7c8a906 works fine, please rollback

> but it will extract an seemingly infinite number of video pages instead of downloading any videos.

not here - "Downloading 19 videos"

i can append `&page=2` etc. for pagination

**Comment by marabu88** [comment]
> yes, commit [7a74fed](https://github.com/ytdl-org/youtube-dl/commit/7a74feda7837bc54b6b0ccfed980ca9bf7c8a906) works fine, please rollback

Yes, it definitely works for me. but why are there no changes in the main program? 20 days have passed :( I hope the work on this application is not abandoned.

**Comment by xarantolus** [comment]
So a quick update here, from my end the current code seems to work fine both for subscriptions and search queries. It looks like introducing the limit with feeds was unnecessary as they end at some point (for me it downloaded about 170 subscription pages) so I removed it again.

**Comment by romanrm** [comment]
Seems like this is still not fixed in the main release of YTDL? Today I had to update it because extracting of YouTube videos broke (in general). But now I lost the fix from that special branch with fixes for  /results?search_query=... When will it get merged? Or how to combine both for now?

**Comment by xarantolus** [comment]
Well, I rebased this to include upstream commits (and I think I made some kind of mess because GitHub now shows me as committer) and it seems to work when installing this branch again:

    pip3 install -U git+https://github.com/xarantolus/youtube-dl@fixYTSearch

**Comment by phyr** [comment]
> Well, I rebased this to include upstream commits (and I think I made some kind of mess because GitHub now shows me as committer) and it seems to work when installing this branch again (it now combines all changes):
> 
> ```
> pip3 install -U git+https://github.com/xarantolus/youtube-dl@fixYTSearch
> ```

How do I install this with wget (macOS terminal)?

**Comment by romanrm** [comment]
@xarantolus thanks! Works again now.

**Comment by milahu** [comment]
> > ```
> > pip3 install -U git+https://github.com/xarantolus/youtube-dl@fixYTSearch
> > ```
> 
> 
> How do I install this with wget (macOS terminal)?

1. visit https://github.com/xarantolus/youtube-dl
2. switch to branch [fixYTSearch](https://github.com/xarantolus/youtube-dl/tree/fixYTSearch)
3. code > download zip > https://github.com/xarantolus/youtube-dl/archive/fixYTSearch.zip

**Comment by xarantolus** [comment]
@phyr you can try [this binary](https://github.com/ytdl-org/youtube-dl/files/4988771/youtube-dl.zip) I just built, but I'm not sure if it will run correctly on Mac (built on windows, tested on a Raspberry Pi with python installed where it worked). Download the zip file, unpack it and `chmod +x ./youtube-dl`; then move it to your `$PATH`

**Comment by AthenaAzuraea** [comment]
Strangely doesn't seem to work with subscriptions (of course the official release is affected too):
youtube-dl.exe "https://www.youtube.com/feed/subscriptions" --playlist-end 200 --cookies Cookies.txt
[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
[youtube:subscriptions] playlist Youtube Subscriptions: Downloading 0 videos
[download] Finished downloading playlist: Youtube Subscriptions

**Comment by scout719** [comment]
> Strangely doesn't seem to work with subscriptions (of course the official release is affected too)

I also noticed this, but after reverting to the last revision on this PR that successfully extracted subscriptions I was able to do it with no problems. I used rev: [b3fd4b1](https://github.com/ytdl-org/youtube-dl/pull/25734/commits/b3fd4b155e7460ffd21e87eb29bc8a95902a429a)

@xarantolus Please take this into account to fix the subscriptions extraction

**Comment by harroguk** [comment]
> > Strangely doesn't seem to work with subscriptions (of course the official release is affected too)
> 
> @AthenaAzuraea
>  I used rev: [b3fd4b1](https://github.com/ytdl-org/youtube-dl/pull/25734/commits/b3fd4b155e7460ffd21e87eb29bc8a95902a429a)

For anyone that doesnt know how to do this you can use
`pip install git+https://github.com/xarantolus/youtube-dl@b3fd4b155e7460ffd21e87eb29bc8a95902a429a --upgrade --no-cache-dir`

to get a version that will handle the subscription feed for now.

**Comment by xarantolus** [comment]
I fixed feed extraction again, but this time it also extracts all necessary info to download further pages. In my case I was able to go back the entire subscription feed (about 170 requests, 17k videos).
This *should* fix #25695

**Comment by marabu88** [comment]
I can still see it (for youtube-dl version 2020.07.28). is there any chance of getting a fix? Or is it a principled position not to repair this function?
```
>youtube-dl.exe https://www.youtube.com/results?q=test&sp=EgQIBBgB
[youtube:search_url] test: Downloading webpage
[download] Downloading playlist: test
[youtube:search_url] playlist test: Downloading 0 videos
[download] Finished downloading playlist: test
```
and
```
>youtube-dl.exe ytsearch:test
[youtube:search] query "test": Downloading page 1
ERROR: An extractor error has occurred. (caused by KeyError(1,)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by mungr** [comment]
Thank you @xarantolus . The git branch solves my youtube subscriptions problem as well (0 videos downloaded, started for me on 29th July). 
 
@dstftw Can we please get this merged into upstream? 
Right now youtube-dl doesn't correctly download youtube subscriptions... Seems like a core feature to me. 
There's a bunch of "youtube subs no longer work" issues and they're all locked, so I don't see a point in opening another one. This fix works (not saying it is right though, I didn't go through the code).

**Comment by mungr** [comment]
Looks like youtube changed the page again, see traceback:
```[youtube:subscriptions] Youtube Subscriptions: Downloading webpage
[download] Downloading playlist: Youtube Subscriptions
ERROR: Unable to extract ytInitialData; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 969, in process_ie_result
    ie_entries, playliststart, playlistend))
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/youtube.py", line 3355, in _entries
    search_response = self._parse_json(self._search_regex(self._FEED_DATA, page, 'ytInitialData'), None)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract ytInitialData; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by xarantolus** [comment]
This probably happens when your cookies expire (just log in again and export a new cookie file).
I tried `https://www.youtube.com/feed/subscriptions` with normal cookies and it worked as expected, but when I edited some of them to something else (should be similar to expired), it would throw this exact error. The error message should probably better, but `_search_regex` doesn't seem to offer an option for that.

**Comment by harroguk** [comment]
@xarantolus 
I am still getting `ERROR: Unable to extract ytInitialData` even if I download a new cookie. What method are you using to grab them?

Currently I use https://chrome.google.com/webstore/detail/cookiestxt/njabckikapfpffapmjgojcnbfjonfjfg

**Comment by xarantolus** [comment]
I also used that addon (in Vivaldi), so that shouldn't be the problem 🤔
If you go the the page, then view the source code, can you find (with Control+F) the text `window["ytInitialData"]`? If not, then the previous way of extracting might still work.
I cannot reproduce this though, for me it always seems to contain the variable.

**Comment by harroguk** [comment]
Hey man, thanks for the reply.

> If you go the the page, then view the source code, can you find (with Control+F) the text `window["ytInitialData"]`? If not, then the previous way of extracting might still work.

I am not finding that exact string, I see two mentiones of `ytInitialData` on the whole page

1. `<script>var ytInitialData = {"responseContext [...snip remaining huge script...]`
2. `var data = {page: 'browse', player: window.ytplayer.config, playerResponse: window.ytInitialPlayerResponse,url: '\/feed\/subscriptions',response: window.ytInitialData, endpoint: endpoint,}`

> I cannot reproduce this though, for me it always seems to contain the variable.

I can pass you the entire page source if that is helpful? I did try using older versions of the extraction method (from the master branch of youtube-dl/youtube-dl but that hasnt worked since your original changes were required.

**Comment by xarantolus** [comment]
Ah nice, that really helped. I'm not entirely sure if it will work as I always get the other declaration type; maybe this one doesn't have the semicolon at the end (I'm not sure how to get rid of it without extracting the data wrong, without it the regex would be nicer)

**Comment by harroguk** [comment]
getting closer. Its now able to pull the list of videos but cant download any of them.

```
ERROR: DPCL9kj7_bU: YouTube said: Unable to extract video data
Traceback (most recent call last):
  File "c:\installedprograms\python38\lib\site-packages\youtube_dl\YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "c:\installedprograms\python38\lib\site-packages\youtube_dl\extractor\common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "c:\installedprograms\python38\lib\site-packages\youtube_dl\extractor\youtube.py", line 1892, in _real_extract
    raise ExtractorError(
youtube_dl.utils.ExtractorError: DPCL9kj7_bU: YouTube said: Unable to extract video data
```

**Comment by harroguk** [comment]
If you want it, here is a pastebin of the JSON of a the single entry from above. Obviously it was taken from my view-source:https://www.youtube.com/feed/subscriptions

https://pastebin.com/EYwNBDJJ

**Comment by xarantolus** [comment]
I think this is a problem with the video page specifically (as line 1892 is in `YoutubeID`), even though on my end the command `youtube-dl DPCL9kj7_bU` seems to download it. Something like `youtube-dl -j --flat-playlist https://www.youtube.com/feed/subscriptions` should work (if it works, the current regex is ok).

I have absolutely no idea how the actual video player extraction works (and don't plan to work on that), but it seems like that is the broken part (or more specifically: somewhere around [this part](https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L1888-L1893) that extracts YouTubes' error message; at least one of the variables isn't extracted correctly).

**Comment by harroguk** [comment]
`youtube-dl -j --flat-playlist` is working fine (dont judge me)

```
{"_type": "url", "url": "DhXkbUgoEBk", "ie_key": "Youtube", "title": "7 Games That Made Fun of the Haters"}
{"_type": "url", "url": "VxpOdUOjxaU", "ie_key": "Youtube", "title": "Generative Design in Minecraft Competition 2020 - Live Judging (Part 2)"}
{"_type": "url", "url": "mV16Hbh5hig", "ie_key": "Youtube", "title": "Pro Hairstylist Uses Kool-Aid To Color Hair (It didn't go well)"}
{"_type": "url", "url": "lMfMq5tyaOA", "ie_key": "Youtube", "title": "Why A Child Can (But Shouldn't) Eat Fire"}
{"_type": "url", "url": "DPCL9kj7_bU", "ie_key": "Youtube", "title": "How Oak Trees Manipulate Squirrels To Abandon Their Acorns"}
{"_type": "url", "url": "O9QuRZ-MBm0", "ie_key": "Youtube", "title": "Doom Eternal Gameplay: Let's Have a Chill Time Playing Doom Eternal - HELL ON EARTH"}
```

So I guess I sit tight and wait for the extraction to be fixed elsewhere as I guess it cant just be me with this issue. 
Thanks very much for looking into this. Much appreciated.

**Comment by mungr** [comment]
Just to confirm:
```
ERROR: Unable to extract ytInitialData
```
was caused by a stale cookie in my case. The code in this PR holds.
OT: I would love to find a way to automate the way to provide the cookie without any (fragile) browser extensions and manual copy pasting. Did anyone here solved this part?

**Comment by xarantolus** [comment]
I think you can use the [-u and -p command line flags](https://github.com/ytdl-org/youtube-dl#authentication-options) to log in with your username and password, didn't test if it works though.

**Comment by xarantolus** [comment]
Closing this pull request because this has already been resolved for some time.

**Comment by jakeogh** [comment]
Not working on git-latest b8b622fbebb158db95edb05a8cc248668194b430

```
$ youtube-dl --version
2021.03.03

$ /usr/bin/youtube-dl --verbose "https://www.youtube.com/results?search_query=antenna+design"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/results?search_query=antenna+design', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.03.03
[debug] Python version 3.8.7 (CPython) - Linux-5.10.12-gentoo-x86_64-x86_64-Intel-R-_Core-TM-_i7-4910MQ_CPU_@_2.90GHz-with-glibc2.2.5
[debug] exe versions: ffmpeg N-100888-gd43a27ab6f, ffprobe N-100888-gd43a27ab6f
[debug] Proxy map: {}
[youtube:tab] results: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 805, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 826, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/common.py", line 532, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.8/site-packages/youtube_dl/extractor/youtube.py", line 2706, in _real_extract
    raise ExtractorError('Unable to recognize tab page')
youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

**Comment by xarantolus** [comment]
Ah, didn't really check the search URL extractor when closing this. The `YoutubeSearchURLIE` implementation from this pull request works with the current youtube site, e.g. your search query returns 31 items with correct id and title. The `YoutubeFeedsInfoExtractor` also works fine, or at least my tests with cookies + subscription, history feed seemed to work fine for the first page, but it no longer finds `nextContinuationData`.

I'm not entirely sure what to do because my fork got taken down and I can't seem to get it back, so I can't make any edits to this pull request. And in its current state it's not mergeable at all. Should I create a new fork & pull request and add both, or only the search url extractor?

**Comment by jakeogh** [comment]
Thanks! IMHO new pulls for each.

**Comment by radiolondra** [comment]
Same problem, search URL still not working:
youtube-dl version: 2021-3-25

```
Query: https://www.youtube.com/results?search_query=marooned
[youtube:tab] results: Downloading webpage
ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 Exception in thread SearchThread-1:
 Traceback (most recent call last):
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 806, in wrapper
     return func(self, *args, **kwargs)
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 827, in __extract_info
     ie_result = ie.extract(url)
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\extractor\common.py", line 534, in extract
     ie_result = self._real_extract(url)
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\extractor\youtube.py", line 2706, in _real_extract
     raise ExtractorError('Unable to recognize tab page')
 youtube_dl.utils.ExtractorError: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "C:\Users\Robi\AppData\Local\Programs\Python\Python37\lib\threading.py", line 917, in _bootstrap_inner
     self.run()
   File "C:/kivy-projects/KYT/main.py", line 156, in run
     ydl.download([self.query])
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 2060, in download
     url, force_generic_extractor=self.params.get('force_generic_extractor', False))
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 799, in extract_info
     return self.__extract_info(url, ie, download, extra_info, process)
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 815, in wrapper
     self.report_error(compat_str(e), e.format_traceback())
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 628, in report_error
     self.trouble(error_message, tb)
   File "C:\kivy-projects\KYT\kivy_venv\lib\site-packages\youtube_dl\YoutubeDL.py", line 598, in trouble
     raise DownloadError(message, exc_info)
 youtube_dl.utils.DownloadError: ERROR: Unable to recognize tab page; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by xarantolus** [comment]
Yes, it still doesn't work.

I tried integrating the changes from this pull request into the current code, but I failed at doing so. It seems like no matter what I try, the Youtube Tab extractor is always prefered before the SearchURL extractor is called. And the tab extractor fails.

I did uncomment [this line](https://github.com/ytdl-org/youtube-dl/blob/c78591187080e7316c0042309fe956bfd0d38d30/youtube_dl/extractor/extractors.py#L1598) and tried a lot of other stuff (such as returning `False` from `YoutubeTabIE`s `suitable` method if the search URL extractor matches like this:

```py
@classmethod
def suitable(cls, url):
    if YoutubeIE.suitable(url) or YoutubeSearchURLIE.suitable(url):
        return False
    return super(YoutubeTabIE, cls).suitable(url)
```

But it didn't seem to work and I gave up since I currently don't have much time. If someone else finds out how to work around the tab extractor, it would be nice to know. The changes I made are [here](https://github.com/ytdl-org/youtube-dl/compare/master...xarantolus:yt-search-url)

**Pull request closed without merging**
