### PR TITLE
Add tests for format selector criteria longside/shortside

### PR DESCRIPTION
**Pull request by mk-pmb**
### Before submitting a *pull request* make sure you have:
- [ ] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

I hope these tests will help us evaluate potential implementations of feature #30737.

### CODE REVIEW

**Comment by dirkf** [comment]
>AssertionError: None is not true : Regexp didn't match: '(?:(?:#.*?|\\s*)\\n)*from __future__ import (?:[a-z_]+,\\s*)*unicode_literals' not found, unicode_literals import  missing in /home/runner/work/youtube-dl/youtube-dl/test/formatselection/criteria_longside_shortside.py

All Python source for yt-dl should have these lines at the top:
```py
# coding: utf-8
from __future__ import unicode_literals
```

**Comment by mk-pmb** [comment]
> should have these lines at the top:

I'm not sure I understand "at the top": When I move the `unicode_literals` line to above the docstring, flake8 complains "D100 Missing docstring in public module".

**Comment by mk-pmb** [comment]
I've removed the tabwidth and `-*-` from the modeline though.

**Comment by dirkf** [comment]
>I'm not sure I understand "at the top": ...

Sorry, at the top of the code, but below any `#!` line which for OS reasons has to be the first one.

**Comment by mk-pmb** [comment]
Ok, then maybe our flake8s are different. This is the change I understood you suggest: [e1e760ea](https://github.com/mk-pmb/youtube-dl-rg3/commit/e1e760ea739e66f86482b9b1be93a9a22d5d3f37) but

```text
$ flake8 test/formatselection/criteria_longside_shortside.py
test/formatselection/criteria_longside_shortside.py:1:1: D100 Missing docstring in public module
```

**Pull request closed without merging**
