### PR TITLE
Comcast_SSO another way how Comcast can autologin users

### LINKED ISSUE #11257: Unable to extract post url, --ap-mso=Comcast_SSO does not work
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like that [x])
- Use *Preview* tab to see how your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2016.11.18*. If it's not read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2016.11.18**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through [README](https://github.com/rg3/youtube-dl/blob/master/README.md) and **most notably** [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

Tried to use Comcast_SSO with fox and amc

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ap-mso=Comcast_SSO', u'--ap-username=PRIVATE', u'--ap-password=PRIVATE', u'--verbose', u'http://www.fox.com/watch/813014083891/7684601088']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.12 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[FOX] 813014083891: Downloading webpage
[FOX] 813014083891: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/fox.py", line 48, in _real_extract
    query['auth'] = self._extract_mvpd_auth(url, video_id, 'fbc-fox', resource)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1399, in _extract_mvpd_auth
    provider_redirect_page_res, 'Downloading Provider Login Page')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1322, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 669, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

```
[debug] System config: []
[debug] User config: []
[debug] Command-line args: [u'--ap-mso=Comcast_SSO', u'--ap-username=PRIVATE', u'--ap-password=PRIVATE', u'--verbose', u'http://www.amc.com/shows/the-walking-dead/full-episodes/season-07/episode-05/go-getters']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2016.11.18
[debug] Python version 2.7.12 - Darwin-16.1.0-x86_64-i386-64bit
[debug] exe versions: avconv 11.4, avprobe 11.4, ffmpeg 3.2, ffprobe 3.2
[debug] Proxy map: {}
[AMCNetworks] go-getters: Downloading webpage
[AMCNetworks] go-getters: Downloading JSON metadata
[AMCNetworks] HJLoSZIQJoKa: Downloading Provider Redirect Page
ERROR: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 694, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 357, in extract
    return self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/amcnetworks.py", line 64, in _real_extract
    query['auth'] = self._extract_mvpd_auth(url, video_id, requestor_id, resource)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1399, in _extract_mvpd_auth
    provider_redirect_page_res, 'Downloading Provider Login Page')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/adobepass.py", line 1322, in post_form
    post_url = self._html_search_regex(r'<form[^>]+action=(["\'])(?P<url>.+?)\1', form_page, 'post url', group='url')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 669, in _html_search_regex
    res = self._search_regex(pattern, string, name, default, fatal, flags, group)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 660, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract post url; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

### PR DESCRIPTION
**Pull request by outcoldman**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

Fixes #11257

Comcast has another way how it can autologin users

### CODE REVIEW

**Comment by raleeper** [comment]
@outcoldman This code works for me. I tested an autologin site (usanetworks) and a manual login site (syfy). Both worked from my Comcast connection. I ran the same tests through a Verizon Wireless hotspot. Both worked via the hotspot, but usanetworks did a manual login as expected. 

The code here has the same effect as PR #11080, which is still pending. If this gets applied, that PR can be ignored and closed.

[test_comcast_network.log.txt](https://github.com/rg3/youtube-dl/files/604257/test_comcast_network.log.txt)
[test_vz_network.log.txt](https://github.com/rg3/youtube-dl/files/604258/test_vz_network.log.txt)

**Comment by Mr-Jake** [comment]
I can also confirm that this works. I compiled youtube-dl with this fix and I can finally login in with a Comcast account. Thank you!

**Comment by Mr-Jake** [comment]
This fix no longer seems to work with discoverygo.com, animalplanetgo.com, sciencechannelgo.com, etc. It was working until a couple days ago.

`ERROR: This video is only available via cable service provider subscription that is not currently supported. You may want to use --cookies.`

This fix still works with the other sites that require a Comcast login, but not the Discovery Channel GO family of network sites.

**Comment by joetex72** [comment]
Will this work on AT&T network?
I'd like to test it but I'd need instructions on how to compile youtube-dl.exe for Windows.

**Comment by rajiv** [comment]
this patch is still working for me with youtube-dl 2017.05.18.1 and comcast xfinity. how can we get this PR merged? thanks.

**Comment by tv21** [comment]
This patch did not work for me but this newer one did:

https://github.com/bhamboss/youtube-dl/blob/patch-1/youtube_dl/extractor/adobepass.py

I can confirm this works with Xfinity's new login if you are coming in from an Xfinity IP address.

Just to be clear, Xfinity authenticates differently if you are coming in from one of their IP addresses vs. if you are coming in from the IP of some other provider.  I tested the above patch coming from an Xfinity IP.  I did NOT test it from another provider's IP.

If I run diff -u on the original and patched files I get this:

```
$ diff -u adobepass.py.original adobepass.py.patched
--- adobepass.py.original	2018-10-17 01:22:56.000000000 -0400
+++ adobepass.py.patched	2019-04-23 08:53:36.000000000 -0400
@@ -1433,6 +1433,14 @@
                             provider_redirect_page, 'oauth redirect')
                         self._download_webpage(
                             oauth_redirect_url, video_id, 'Confirming auto login')
+                    elif 'automatically signed in with' in provider_redirect_page:
+                        # Seems like comcast is rolling up new way of automatically signing customers
+                        oauth_redirect_url = self._html_search_regex(
+                            r'continue:\s*"(https://oauth.xfinity.com/oauth/authorize\?.+)"',
+                            provider_redirect_page, 'oauth redirect (signed)')
+                        # Just need to process the request. No useful data comes back
+                        self._download_webpage(
+                            oauth_redirect_url, video_id, 'Confirming auto login')
                     else:
                         if '<form name="signin"' in provider_redirect_page:
                             provider_login_page_res = provider_redirect_page_res

```

The only difference I can see at a quick glance between the two patches is that login.comcast.net is changed to oauth.xfinity.com.

**Comment by tv21** [comment]
I'm going to leave a comment here because the developers closed and locked issue #22105 a few minutes ago, with a TV-Provider-Account-Needed tag, even though that issue was about a network and NOT a provider, and there was active discussion taking place.  The problem with USA network is one that could be observed from nearly ANY active provider account for a USA-based provider.  So I think locking it with that tag shows a misunderstanding of the issue. In any case I wanted to make an addition to one of my previous posts in that issue but was stopped because it was suddenly limited to collaborators.  While I agree that issues such as this are not really the best place to hold a discussion, there are few alternatives when it comes to youtube-dl, in fact all I could find was a little used Reddit forum that doesn't even show up in search engines.

But what I really wanted to say is that you guys are fundamentally misunderstanding the problem with Comcast.  You say you need a TV Provider Account but THAT WILL NOT HELP YOU UNLESS YOU ARE ACTUALLY USING COMCAST AS YOUR BROADBAND PROVIDER.  Sorry for shouting, but just trying to get you to understand that if you had a thousand Comcast logins none of them would help you fix this issue unless you were actually using Comcast as your provider, and if you were already actually using Comcast then you do NOT need login credentials, because Comcast doesn't use them when you are logged into their network.  When you are using a web browser and log into something that uses typically uses account passwords and shows you a provider tiles that you can choose for login purposes, if you have Charter (as an example) and pick it, even if you are on Charter's network it will let you enter a user name and password.  BUT COMCAST DOESN'T WORK THAT WAY!!! If you are connected to their network, you NEVER enter a username and password assuming you select Comcast (or Xfinity as they prefer to be called) as your provider on whatever site you're trying to watch video on.  You never even see a username/password entry field! There is this whole automatic handshake that takes place and that's what the code in my previous post takes care of (which I did not write, just reposted from what I found at https://github.com/bhamboss/youtube-dl/blob/patch-1/youtube_dl/extractor/adobepass.py).

The other thing you need to realize, which has absolutely nothing to do with this because of what I've just explained to you but I'll say it anyway, is that Comcast is one of the worst of the (non-cellular) providers for enforcing usage caps and charging overage charges.  Therefore I understand why users are somewhat reluctant to provide account credentials, especially in a case like this where they will not help you a bit.  The code above will never be used if you are not already coming in from a Comcast account, so there is no way for you to test it from afar.  There is no possible scenario in which having Comcast account credentials would help you test this code.

Basically you can either accept that it works (which it does) or you can decide not to support Comcast, or maybe if you are ever in a Comcast area you could use a computer on their network (again, if it is logged into Comcast then it won't ask you for a username and password), but saying you can't do anything until you have account credentials shows a serious misunderstanding of the issue.  Honestly I'm not trying to annoy you guys, I realize that maintaining youtube-dl is probably a thankless job, but I do think you did us a disservice by limiting talk on that other issue (#22105) while it was still being hashed out.  I don't know if it was my post that mentioned this issue that annoyed you, and if so I profusely apologize, or if it was 
netuser0 trying to get your attention because he thought that issue was SO important that you'd immediately want to jump on it, but I'd much appreciate it if you'd reopen it at least long enough that we can try to hash this issue out.  And I really do appreciate all the effort you guys put into youtube-dl, especially when you are faced with the aggravation of sites constantly changing their pages and methods of operation!

**Comment by dstftw** [comment]
:facepalm:
1. I'm not referring to **any particular tv provider** in #22105. It's an issue with **particular extractor** not **particular tv provider**.
2. Regarding issues with Comcast tv provider. One must provide complete reproducible environment whether it will include credentials, access to proxy/VPN with Comcast client IP or whetever else is needed for accessing the video in browser.

**Comment by netuser0** [comment]
tv21, I totally agree with your comment. My intention was not to come across as impatient. I apologize if I did come off as impatient. I do not know that TV providers credentials had to be provided. I could not find where it stated that TV providers credentials had to be provided in order for project contributors to work on an issue. I agree with you that even if the TV provider credentials where given to the project contributors, it would not work due to them not being on the provider's network.

**Pull request closed without merging**
