### PR TITLE
Fix SSO with Xfinity

### PR DESCRIPTION
**Pull request by bhamboss**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Changes to the auth redirect broke the Comcast_SSO provider.

A previous attempt was made here, but it wasn't working on the latest Comcast auth portal. https://github.com/rg3/youtube-dl/pull/11258

### CODE REVIEW

**Comment by TheJayMann** [comment]
I have been able to verify that this patch has allowed me to download a locked ABC video where without the patch I couldn't. I haven't been able to try with FOX because FOX recently made some breaking change.

What would be necessary to get this request accepted? The official release is essentially useless for me until this is added.

**Comment by mma38e** [comment]
This worked for me thanks!

**Comment by tv21** [comment]
Just to be clear, Xfinity authenticates differently if you are coming in from one of their IP addresses vs. if you are coming in from the IP of some other provider.  I tested this patch coming from an Xfinity IP, and it works!  Hope it can be merged soon because Xfinity (a.k.a. Comcast) is the largest or second largest cable provider in the USA (since Charter's recent merger they may be the largest now, not really sure).

**Comment by ealgase** [comment]
@remitamine could you take a look at this?

**Comment by remitamine** [comment]
there are multiple problems, with the AdobePass code:
- the code needs to be refactored to into a design similar to the way extractors work for a better code quality and to make easy to add new providers(not a giant if-else block).
- the auto login workflow can't be tested by the reviewers.
- the requirement of an account(for review or for adding support for requested TV providers in the issues) is also one of the reasons that most of the requests are not processed.

so, i think the best way(especially with the large number of TV providers) in my opinion is to have a way to extract the needed session from the browser(the session is stored in the Local Storage, and it's reason why this can't be supported using the `--cookies` option) and pass it to youtube-dl, and then deprecate the current `--ap` options, this method makes it possible to use all TV Providers with youtube-dl without having to add support for each TV provider manually and reduce the maintainability burden.

**Comment by ealgase** [comment]
That makes sense.  Is there a known way to export and use session storage data, or would we need to implement that ourselves.

**Comment by remitamine** [comment]
as far as i know there isn't a addon that can export local storage data, the manual way is to look at the local storage is to use the `Developer Tools` -> `Storage` -> `LocalStorage`.

**Comment by tv21** [comment]
> as far as i know there isn't an addon that can export local storage data, the manual way is to look at the local storage is to use the `Developer Tools` -> `Storage` -> `LocalStorage`.

The problem I see here is that whatever shortcomings there may be with the current `--ap` options, just about anyone can figure out how to use them, and in many cases you can get by without ever going into a browser (except to get the required link to a media item).  Maybe I'm wrong, but the sense I get is that what you're proposing here sounds much more complicated, particularly if users have to go into Developer Tools and then attempt to figure out what they need to copy, and to where.  Please don't make usage any more difficult than it already is! If you do you will lose a lot of users that can barely figure out which options they need to use as it is.

That said I understand your desire to redesign the current AdobePass code, however in this case all we need is the addition of a few lines to make this work again for users of one of the largest cable providers in the world.  It always baffles me a bit that when someone hands you guys a solution and several users report it works, and it's not a very complicated fix, that you still often seem to mull it over for months before applying the fix.  Or, as in this case, rather than making the quick fix that will get things working again, you start to think about rewriting a major section of the module or even the entire module.  It's all well and good that you want to improve the software, but you can do that whether or not you apply a patch such as this one.  This may be a case of not being able to see the forest for the trees, where the forest is all your users that just want the program to work and really don't care that much about how it's coded, whereas the trees are your desire for coding perfection (or as close to it as you can get).  Whatever the flaws of the current AdobePass code may be, for right now it is working for many users and could work for more users if you would simply add the few lines in this patch.  Obviously it's your software and you can support or not support whatever you want, but I have to wonder what it was about this particular patch that made you start thinking about making serious changes that could take months or years to develop, rather than "how can we get this working again for our users?"

The other thing I wanted to briefly address is you spoke about the requirement of an account.  Unfortunately, as you've probably discovered, very few people are going to hand over their account credentials and even if they did, in this particular case it would do you no good because this particular cable company's authentication acts differently depending on whether you are coming in from one of their IP addresses or someone else's.  So even if you had someone's username and password, you would probably not see the authentication issues that those actually on their network are seeing (unless perhaps you somehow got a VPN connection into their network).  I would suggest that there are probably situations such as this one where you need to have a little trust in the reports that users post, that tell you if a particular fix is working.  If we were talking about major code changes I'd understand your reluctance more, but this is simply the addition of a few more lines in a single block of code.

Anyway, in the long term I fully support your desire to clean up the code and maybe make it more universally applicable IF it doesn't make the program harder to use, or require users to understand the inner workings of web browsers or something like that.   But if it's going to make usage of your software more complicated, then my plea would be to leave well enough alone.  Users don't care much about how a program is coded, but they do care whether it's easy to use, and if something breaks they do care about seeing it get fixed sooner rather than later.  You could have a program that takes 10,000 lines of code to do something that could be done in 10 lines of code, and as a _user_ I'm not going to care as long as the program works and isn't a big hassle to use!  Thank you for all your efforts on this software; I truly hope you can come up with something that allows you to have code more to your liking without sacrificing ease of use.

**Comment by remitamine** [comment]
> Maybe I'm wrong, but the sense I get is that what you're proposing here sounds much more complicated, particularly if users have to go into Developer Tools and then attempt to figure out what they need to copy, and to where.

you're making me say things that I didn't even mention at all, I simply answered @ealgase question on the current state of exporting the `Local Storage` data, I didn't talk here about the user, obviously when I propose something for the user, I will try to make it as simple as possible, such as creating an addon to export the Local Storage similar to the add-ons available for cookies.
> If you do you will lose a lot of users that can barely figure out which options they need to use as it is.
This may be a case of not being able to see the forest for the trees, where the forest is all your users that just want the program to work and really don't care that much about how it's coded, whereas the trees are your desire for coding perfection (or as close to it as you can get). 
Users don't care much about how a program is coded, but they do care whether it's easy to use and if something breaks they do care about seeing it get fixed sooner rather than later.

so only user's opinion matter and has the priority, but our need(developers) for clean and maintainable code does not matter?
>  It always baffles me a bit that when someone hands you guys a solution and several users report it works, and it's not a very complicated fix, that you still often seem to mull it over for months before applying the fix.

it's not about if it's working, I can make the worst possible code and make it work, the user would be happy of course, but for us developers, it will be more difficult for us to maintain it and keep it working while making changes in other parts as well, it's not just about `it's working`, it's about making the code up to the project's coding standards(make it less possible for the code to be broken...), and in this case there was a case that previously happened with the Verizon code, I merged the code that contains the auto-login functionality even though I couldn't test it and check if it can be improved and then shortly after merging it stopped working, and we got into the same cycle users reporting issues and complaining and we have to deal with it.
> Or, as in this case, rather than making the quick fix that will get things working again, you start to think about rewriting a major section of the module or even the entire module.
but I have to wonder what it was about this particular patch that made you start thinking about making serious changes that could take months or years to develop.

again, this is inaccurate, I didn't start now thinking about refactoring as an excuse for not merging this, the need for refactoring has been expressed from the beginning by @dstftw, and I do agree that the refactoring is needed, with the current code, every addition makes the code more difficult to deal with, and makes the changes for a particular TV provider might break support for others in some cases, it's not about this patch in particular, it's about the accumulating effect of all the patches related to the AdobePass code.

in the end, it's my fault for adding the code directly without sending it as PR for code review, and may I shouldn't create the support this way at all and instead from the beginning try to figure out why it doesn't work with cookies and make a working solution for all the TV Providers, but now I'm not even sure if all of that is really worth it.

**Comment by tv21** [comment]
> > Maybe I'm wrong, but the sense I get is that what you're proposing here sounds much more complicated, particularly if users have to go into Developer Tools and then attempt to figure out what they need to copy, and to where.
> 
> you're making me say things that I didn't even mention at all, I simply answered @ealgase question on the current state of exporting the `Local Storage` data, I didn't talk here about the user, obviously when I propose something for the user, I will try to make it as simple as possible, such as creating an addon to export the Local Storage similar to the add-ons available for cookies.

Understood, but my point is that using the cookies addon requires an extra step that's normally not required.  For example, if I have a list of URL's of media to get, I normally can simply enter youtube-dl and the URL and that's all I need - I don't need to leave the command prompt at all.  But when I have to use a cookies file, now I need to fire up the browser, go to the provider site, download the cookies file, and only then can I begin.  It's not a LOT of extra work in the grand scheme of things, but it is going from easy-peasy to harder, and involves more steps that someone unfamiliar with the process may not understand.  The first time I had a need to use a cookies file I was totally lost as to the process involved, and it took me much more time than it should have to finally figure it out.

> > If you do you will lose a lot of users that can barely figure out which options they need to use as it is.
> > This may be a case of not being able to see the forest for the trees, where the forest is all your users that just want the program to work and really don't care that much about how it's coded, whereas the trees are your desire for coding perfection (or as close to it as you can get).
> > Users don't care much about how a program is coded, but they do care whether it's easy to use and if something breaks they do care about seeing it get fixed sooner rather than later.
> 
> so only user's opinion matter and has the priority, but our need(developers) for clean and maintainable code does not matter?

Now you're putting words in my mouth.  Of course your need for clean and maintainable code matters, I just can't understand why this particular short and easy to implement patch that would benefit a whole lot of users in the USA is the one you want to make that stand on.  If you want to work on more clean and maintainable that is great and I fully support that effort, but in the meantime why not add these eight lines (two of which are comments) so that users don't have to wait while you rewrite all that code?  I don't know how quickly you write code, and maybe you can knock it out in a day or two and if so that's great.  But if this is something that will take you months or years, or is something that you plan to do when you get around to it or feel sufficiently motivated, then why not at least add this patch in the meantime so you aren't making youtube-dl nearly unusable for people so unlucky as to be customers of this particular cable company (which is the only high speed broadband provider in much of the USA).

I just don't get what is so special, or awful, about this particular patch that made you think "I'd rather rewrite this code than add these few lines, and make users wait until I do."  And also, it's not as though adding this patch would make it any more difficult for you to rewrite this code; doing one doesn't in any way stop or inhibit you from doing the other.  I just really don't get your reluctance here.

> > It always baffles me a bit that when someone hands you guys a solution and several users report it works, and it's not a very complicated fix, that you still often seem to mull it over for months before applying the fix.
> 
> it's not about if it's working, I can make the worst possible code and make it work, the user would be happy of course, but for us developers, it will be more difficult for us to maintain it and keep it working while making changes in other parts as well, it's not just about `it's working`, it's about making the code up to the project's coding standards(make it less possible for the code to be broken...), and in this case there was a case that previously happened with the Verizon code, I merged the code that contains the auto-login functionality even though I couldn't test it and check if it can be improved and then shortly after merging it stopped working, and we got into the same cycle users reporting issues and complaining and we have to deal with it.

I could understand that thinking if this was a complex patch, but it's only six lines of active code and two lines of comments, in one contiguous block.  Very easy to add, and very easy to remove if people start reporting problems.  Have you actually looked at this patch?

Now granted that nobody can guarantee that if you implement it, it won't stop working - in fact it probably WILL stop working somewhere down the line, because companies like to change up their web sites from time to time, and that's why so many services work for a while and then stop working, as you well know.  But you can only deal with a site as it is today.  If you apply the patch and they change the site again in a week, well at least it worked for a week.  And maybe they will only change some text on the site and the next fix will only be a single line change.  I do understand that you want to make the code easier to maintain and again that's a very laudable effort, but you probably spent considerably more time replying to me than it would have taken to apply that patch, which would have helped many users in the short term.

> > Or, as in this case, rather than making the quick fix that will get things working again, you start to think about rewriting a major section of the module or even the entire module.
> > but I have to wonder what it was about this particular patch that made you start thinking about making serious changes that could take months or years to develop.
> 
> again, this is inaccurate, I didn't start now thinking about refactoring as an excuse for not merging this, the need for refactoring has been expressed from the beginning by @dstftw, and I do agree that the refactoring is needed, with the current code, every addition makes the code more difficult to deal with, and makes the changes for a particular TV provider might break support for others in some cases, it's not about this patch in particular, it's about the accumulating effect of all the patches related to the AdobePass code.

Again, I could be more understanding of that position if this were a complex patch that affected several modules, but it's not.  I understand where you are coming from, or at least I'm trying to, but as far as I can see this patch would only affect users of this one cable company, and it would only fix a problem that they are having.  If you see some way that it would break support for users of other providers, then your position makes a whole lot more sense, but as I said I just don't get what it is about this particular patch that would make you start worrying about the accumulating effect of all the patches related to the AdobePass code.  I really suspect that maybe you haven't actually looked at this patch and don't realize what a minor change it is.

> 
> in the end, it's my fault for adding the code directly without sending it as PR for code review, and may I shouldn't create the support this way at all and instead from the beginning try to figure out why it doesn't work with cookies and make a working solution for all the TV Providers, but now I'm not even sure if all of that is really worth it.

Well now I am even more confused.  It sounds like you are having some kind of existential crisis or something, and if so I have no idea why this simple patch would trigger that.  If I said something that would have triggered that I profusely apologize; on the other had if there are other things going on in your life right now that you are dealing with then I'm sorry if I added to your burdens in any way.  To my way of thinking adding this patch was the easy fix that solves the immediate issue, even if it kicks the can down the road on any other issues that exist in the code.  All I was trying to report is that this fix actually works in April, 2019 and that I felt it would be worth implementing even if just for the short term.  To me, objecting to this patch is like obsessing over a pebble in the road when there's a mountain to climb up ahead (but only if you choose to climb it).  I understand that as a developer you need to have code that's easy to maintain, and I'm not trying to discourage you from that in any way.  I just find it really incomprehensible that you think that this particular very short patch is the place to make that stand.

**Comment by remitamine** [comment]
obviously, before I comment, I did look at the patch, and again I'm not talking specifically about this patch, I'm talking in general about all the issues and PRs related to AdobePass code(https://github.com/ytdl-org/youtube-dl/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+adobepass and https://github.com/ytdl-org/youtube-dl/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+--ap-password).

In simple terms, I want to have a solution where I don't have to keep looking at code that can't be tested, asked to support hundreds of login workflows(my estimation is that there is about 150 unique login workflow), asked why did you support provider A and not B, and deal with the ones that broke.

**Comment by sufr3ak** [comment]
> In simple terms, I want to have a solution where I don't have to keep looking at code that can't be tested, asked to support hundreds of login workflows(my estimation is that there is about 150 unique login workflow), asked why did you support provider A and not B, and deal with the ones that broke.

This is an understandable sentiment. As it stands, Xfinity/Comcast happens to be the largest ISP/Cable Co in the US. I recognize that this tool is not US only. But as it stands, the function is broken. If this commit will fix it, and has been tested by many folks, which will likely alleviate gripes from a lot of users, it seems there is limited reasons not to do it.

As for "Why provider A and not B". The same reason as current. You don't have the personal means, nor enough other people to develop the fix/patch. If others can submit patches which are tested but many people and work, then it can be evaluated.

As it stands now, this is a broken feature. In the unlikely chance this merge doesn't fix all the errors, it is still broken, so no real loss there.

**Comment by remitamine** [comment]
i already explained before that this type of patches(similar to patches related to Youtube 429) lacks the ability to test the code, it doesn't matter if the change is small or big it has to be verifiable before merging.
Voting can be easily corrupted(any one can send a patch, and then create a dozons of accounts claiming that the fix works).
also as i said before, i have been asked before to refactor the code before making new changes and i did agree to that, but still didn't make the requested refactoring(there is already lots of issues besides the AdobePass issues).
and also as i have said, the way forward is to have a way to export local stoage(or at least, extarct the AuthN token from the adobe services requests) from the browser and pass it to youtube-dl, this way it will allow to support all TV Providers.

**Comment by tv21** [comment]
You know, you can try to make programmer/developer type explanations until you are blue in the face but the fact is that users have no idea what the heck you are ranting about.  All they know is that **there is a fix that works**, **it is only eight lines long** (so not something that requires hours of inspection to verify) and that because you are being so pedantic, your software for the most part doesn't work for users of the largest cable company in the United States, when they are going to a site that requires a provider login.

A reasonable developer might say that because this is such a simple fix (and therefore easy to back out later), it could be implemented on at least a temporary basis until a better solution is coded.  An unreasonable developer might say, in effect, "f--- all the users of that large cable company, they can twist in the wind until I find the time to do the absolutely perfect fix."  But what often happens to unreasonable developers is that someone else who is more reasonable forks their project and makes the fixes, and maybe the forked project becomes even more popular than the original.  Of course this causes fragmentation of the project, where even "perfect" fixes don't make it back to the original project because no one wants to contribute code back to a developer that has in essence told users to go f--- themselves.  But hey, I guess that is far better than not having the absolute most perfect and excellent code you can possibly have, whenever you can finally get around to writing it.

**Comment by BeeMuffins** [comment]
It seems that Xfinity/Comcast has changed the way they are authenticating as I've been getting a number of ```HTTP Error 401: Unauthorized``` errors.  Anyone have an idea on how to update to get it to work again?

There's been a couple issues raised over on yt-dlp that seem to be related as well as https://github.com/ytdl-org/youtube-dl/issues/29544 here.

**Pull request closed without merging**
