### PR TITLE
Youtube live chat

### LINKED ISSUE #25874: YouTube chat replay support
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.06.16.1**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

YouTube now has "chat replay" for recorded livestreams in the same style as Twitch, which youtube-dl already supports extraction of as a "subtitle".  It would be beneficial for youtube-dl to also support extraction as a subtitle for YouTube, as like on Twitch, chat on YouTube can form a very important part of the livestream in question.  There is no existing support for this in youtube-dl, or similar option that I can see.

There is a Python library at https://github.com/taizan-hokuto/pytchat which may be useful for the implementation of this. 
 Amongst other formats, it supports output as JSON, which could simply be passed back as the output for a new "subtitle" - the same style as the Twitch chat replay.

Use case example: The archiving of a YouTube channel, including all metadata.  At the moment the chat replay would not be saved, meaning there is no context for content in the video which may refer to it.

### PR DESCRIPTION
**Pull request by siikamiika**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Closes  #25874.

There was a ready-made solution linked in the thread https://github.com/taizan-hokuto/pytchat but I wasn't sure if Unlicense is compatible with MIT license so I made a new extractor. I didn't implement real-time live chat extraction because it was more complicated (used POST requests etc).

The chat replay is saved as multiple lines of JSON objects. I didn't do any finer processing on the chat replay and it's dumped as-is from YouTube. However, if conversion to other subtitle formats is desired, there's some code in the issue that can be used.

Example:
```
> youtube-dl --all-subs --skip-download 'https://www.youtube.com/watch?v=h4M5iFLKWqU'
[youtube] h4M5iFLKWqU: Downloading webpage
[youtube_live_chat_replay] Downloading live chat
[youtube_live_chat_replay] Total fragments: unknown (live)
[download] Destination: 【Celeste - End】Revisiting the Best Platformer Ever!-h4M5iFLKWqU.live_chat.json
[download] 100% of 9.98MiB in 01:18
```

```json
{"replayChatItemAction": {"actions": [{"addChatItemAction": {"item": {"liveChatViewerEngagementMessageRenderer": {"id": "ChwKGlJFUExBWV9WRU0xNTk2NTg4ODQxOTI0NDg5", "timestampUsec": "1596588841924551", "icon": {"iconType": "YOUTUBE_ROUND"}, "message": {"runs": [{"text": "Live chat replay is on. Messages that appeared when the stream was live will show up here."}]}}}}}], "videoOffsetTimeMsec": "0"}}
{"replayChatItemAction": {"actions": [{"addChatItemAction": {"item": {"liveChatTextMessageRenderer": {"message": {"runs": [{"text": "hello everyone coming in!"}]}, "authorName": {"simpleText": "Maddy M"}, "authorPhoto": {"thumbnails": [{"url": "https://yt3.ggpht.com/-Bc8B7g2NRjE/AAAAAAAAAAI/AAAAAAAAAAA/Jof_W55WiYg/s32-c-k-no-mo-rj-c0xffffff/photo.jpg", "width": 32, "height": 32}, {"url": "https://yt3.ggpht.com/-Bc8B7g2NRjE/AAAAAAAAAAI/AAAAAAAAAAA/Jof_W55WiYg/s64-c-k-no-mo-rj-c0xffffff/photo.jpg", "width": 64, "height": 64}]}, "contextMenuEndpoint": {"clickTrackingParams": "CAEQl98BIhMIjZ6T9uyC6wIVRMFPCB2hhw6_", "commandMetadata": {"webCommandMetadata": {"ignoreNavigation": true}}, "liveChatItemContextMenuEndpoint": {"params": "Q2p3S09nb2FRMGxEZWpZdE4yUnZkVzlEUmxKTVZHZG5iMlF5Uld0RFpuY1NIRU5PTmxndExWQlliM1Z2UTBaV2NraDRRVzlrTVVoTlNXOUJNVElRQUJvNEdnMEtDMmcwVFRWcFJreExWM0ZWS2ljS0dGVkRjV0ZKV21Oak5IQnBXamt4TVhsMFpXbFFURlZYVVJJTGFEUk5OV2xHVEV0WGNWVWdBU2dFTWhvS0dGVkRhWEptZW5WU1VGSlpUV041ZW5CaWIwNWpjSFV6WnclM0QlM0Q="}}, "id": "CjoKGkNJQ3o2LTdkb3VvQ0ZSTFRnZ29kMkVrQ2Z3EhxDTjZYLS1QWG91b0NGVnJIeEFvZDFITUlvQTEy", "timestampUsec": "1593286265067904", "authorBadges": [{"liveChatAuthorBadgeRenderer": {"customThumbnail": {"thumbnails": [{"url": "https://yt3.ggpht.com/IkKJ4CF9XyD61Pwq5wW9RmFk41psX_A01jNAsvVic0UB7jOXCQTg73P45JSoHLTcr45V8zOp=s16-c-k"}, {"url": "https://yt3.ggpht.com/IkKJ4CF9XyD61Pwq5wW9RmFk41psX_A01jNAsvVic0UB7jOXCQTg73P45JSoHLTcr45V8zOp=s32-c-k"}]}, "tooltip": "Member (4 months)", "accessibility": {"accessibilityData": {"label": "Member (4 months)"}}}}], "authorExternalChannelId": "UCirfzuRPRYMcyzpboNcpu3g", "contextMenuAccessibility": {"accessibilityData": {"label": "Comment actions"}}, "timestampText": {"simpleText": "-4:13"}}}, "clientId": "CN6X--PXouoCFVrHxAod1HMIoA12"}}], "videoOffsetTimeMsec": "0"}}
{"replayChatItemAction": {"actions": [{"addChatItemAction": {"item": {"liveChatTextMessageRenderer": {"message": {"runs": [{"text": "Hello chat"}]}, "authorName": {"simpleText": "alberto cos"}, "authorPhoto": {"thumbnails": [{"url": "https://yt3.ggpht.com/-9Lqq3ySulO8/AAAAAAAAAAI/AAAAAAAAAAA/cjVGgRoHow8/s32-c-k-no-mo-rj-c0xffffff/photo.jpg", "width": 32, "height": 32}, {"url": "https://yt3.ggpht.com/-9Lqq3ySulO8/AAAAAAAAAAI/AAAAAAAAAAA/cjVGgRoHow8/s64-c-k-no-mo-rj-c0xffffff/photo.jpg", "width": 64, "height": 64}]}, "contextMenuEndpoint": {"clickTrackingParams": "CAEQl98BIhMIjZ6T9uyC6wIVRMFPCB2hhw6_", "commandMetadata": {"webCommandMetadata": {"ignoreNavigation": true}}, "liveChatItemContextMenuEndpoint": {"params": "Q2pzS09Rb2FRMHRYTlMxbE4yUnZkVzlEUmxOTWEyZG5iMlF6UjFsSlIyY1NHME5PUjJGNlpVeGtiM1Z2UTBaaWJsSTBkMk5rUlZSWlNGRjNNQkFBR2pnYURRb0xhRFJOTldsR1RFdFhjVlVxSndvWVZVTnhZVWxhWTJNMGNHbGFPVEV4ZVhSbGFWQk1WVmRSRWd0b05FMDFhVVpNUzFkeFZTQUJLQVF5R2dvWVZVTnViVmd4ZHpNeWFXOXRRemd0TWt4Q2VVRkhkMGhu"}}, "id": "CjkKGkNLVzUtZTdkb3VvQ0ZTTGtnZ29kM0dZSUdnEhtDTkdhemVMZG91b0NGYm5SNHdjZEVUWUhRdzA%3D", "timestampUsec": "1593286265298085", "authorExternalChannelId": "UCnmX1w32iomC8-2LByAGwHg", "contextMenuAccessibility": {"accessibilityData": {"label": "Comment actions"}}, "timestampText": {"simpleText": "-4:13"}}}, "clientId": "CNGazeLdouoCFbnR4wcdETYHQw0"}}], "videoOffsetTimeMsec": "0"}}
...
```

### CODE REVIEW

**Comment by Xalaxis** [comment]
Assuming I'm testing this right, the sample file doesn't seem to work:
```PS C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl> py -3 .\__main__.py --all-subs --skip-download 'https://www.youtube.com/watch?v=h4M5iFLKWqU'
[youtube] h4M5iFLKWqU: Downloading webpage
[youtube_live_chat_replay] Downloading live chat
[youtube_live_chat_replay] Total fragments: unknown (live)
[download] Destination: 【Celeste - End】Revisiting the Best Platformer Ever!-h4M5iFLKWqU.live_chat.json
[download] 602.40KiB at Unknown speedTraceback (most recent call last):
  File ".\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\YoutubeDL.py", line 2016, in download
    res = self.extract_info(
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\YoutubeDL.py", line 1840, in process_info
    dl(sub_filename, sub_info)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\YoutubeDL.py", line 1814, in dl
    return fd.download(name, info)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\downloader\youtube_live_chat.py", line 40, in real_download
    data = parse_yt_initial_data(raw_fragment)
  File "C:\Users\Wolf\Desktop\youtube-dl-youtube-live-chat\youtube_dl\downloader\youtube_live_chat.py", line 31, in parse_yt_initial_data
    raw_json = re.search(b'window\\["ytInitialData"\\]\\s*=\\s*(.*);', data).group(1)
AttributeError: 'NoneType' object has no attribute 'group'```

**Comment by siikamiika** [comment]
Hmm, not getting that on Windows 10 or Linux. Maybe it's a regional thing. Can you try adding this change and sharing the `youtube-dl-debug.html` file somewhere? It might contain personal data like IP address so you can clear those out. I'm mainly interested in the following part (or the lack of it):
```html
<script >
    window["ytInitialData"] = {"responseContext":...
```

```diff
diff --git a/youtube_dl/downloader/youtube_live_chat.py b/youtube_dl/downloader/youtube_live_chat.py
index f7478c336..d2677eec5 100644
--- a/youtube_dl/downloader/youtube_live_chat.py
+++ b/youtube_dl/downloader/youtube_live_chat.py
@@ -37,6 +37,9 @@ class YoutubeLiveChatReplayFD(FragmentFD):
             'https://www.youtube.com/watch?v={}'.format(video_id))
         if not success:
             return False
+        with open('youtube-dl-debug.html', 'wb') as f:
+            f.write(raw_fragment)
+        exit()
         data = parse_yt_initial_data(raw_fragment)
         continuation_id = data['contents']['twoColumnWatchNextResults']['conversationBar']['liveChatRenderer']['continuations'][0]['reloadContinuationData']['continuation']
         # no data yet but required to call _append_fragment
```

**Comment by Xalaxis** [comment]
Here's the debug file:
[youtube-dl-debug.zip](https://github.com/ytdl-org/youtube-dl/files/5053132/youtube-dl-debug.zip)

**Comment by siikamiika** [comment]
Thanks! Can you check if the updated version works?

**Comment by Xalaxis** [comment]
@siikamiika Sorry in the delay in getting back to you. I can confirm the updated version solves the issue.  Looks good 👌

**Comment by siikamiika** [comment]
Good to know! Meanwhile I came across one video that used the non-replay live chat style with POST requests for archived content, but in general things seem to work. I might add support for those too at some point.

**Comment by JomSpoons** [comment]
Would love to see this merged with the base branch. Been testing this out as of late and it works very well. This feature is extremely helpful to me so I hope that it can become a staple.

**Comment by JomSpoons** [comment]
It seems I've encountered an issue. I'm trying to download the chat to one of my streams but I encounter an error for some reason. This hasn't happened during any of my 20-ish prior attempts.
`[download] 430.49KiB at  1.05MiB/s (00:00) Traceback (most recent call last):
  File "C:\Other\youtube-dl-chat\youtube_dl\__main__.py", line 19, in <module>
    youtube_dl.main()
  File "C:\Other\youtube-dl-chat\youtube_dl\__init__.py", line 474, in main
    _real_main(argv)
  File "C:\Other\youtube-dl-chat\youtube_dl\__init__.py", line 464, in _real_main
    retcode = ydl.download(all_urls)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 2017, in download
    url, force_generic_extractor=self.params.get('force_generic_extractor', False))
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 1008, in process_ie_result
    extra_info=extra)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 870, in process_ie_result
    extra_info=extra_info)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 1840, in process_info
    dl(sub_filename, sub_info)
  File "C:\Other\youtube-dl-chat\youtube_dl\YoutubeDL.py", line 1814, in dl
    return fd.download(name, info)
  File "C:\Other\youtube-dl-chat\youtube_dl\downloader\common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "C:\Other\youtube-dl-chat\youtube_dl\downloader\youtube_live_chat.py", line 85, in real_download
    continuation_id = live_chat_continuation['continuations'][0]['liveChatReplayContinuationData']['continuation']
KeyError: 'liveChatReplayContinuationData'`

**Comment by siikamiika** [comment]
@JomSpoons Thanks for the report. I added error handling and logging in all places where I noticed that it was missing, and the error you got should be silently skipped because I assume that it's not actually an error.

**Comment by siikamiika** [comment]
Rebased on master

**Comment by siikamiika** [comment]
Closing because I lost access to my fork. There is a new pull request open at https://github.com/ytdl-org/youtube-dl/pull/27020.

**Pull request closed without merging**
