### PR TITLE
[hhu] Add new extractor

### PR DESCRIPTION
**Pull request by YtvwlD**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

[HHU Mediathek](https://mediathek.hhu.de) contains videos created by the Heinrich-Heine-Universität Düsseldorf (mostly recordings of lectures).
This extractor allows the download of single, publicly visible videos.

### CODE REVIEW

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by YtvwlD** [comment]
I read the coding conventions before but I didn't notice the rule regarding closing braces/brackets/parentheses. (I'm used to the guidelines in PEP8, sorry about that.)

**Comment by dstftw** [comment]
It does not say anything about brackets and braces. Also mostly it's nothing to do with closing parentheses which are perfectly valid PEP8.
As for extractor: jwplayer is already covered by generic extractor that should be extended to support such cases.

**Comment by YtvwlD** [comment]
The generic extractor doesn't work here because `_find_jwplayer_data` doesn't recognize the player config because the used regex [fails](https://regexr.com/4mhpb) at the `encodeURI` call.

I modified my PR to at least use `_parse_jwplayer_data`.
Also, I had to touch the regex in `_parse_jwplayer_formats` to also accept format descriptions that are not at the beginning of the label text. I really hope that this won't break existing stuff - I tested a few extractors using these functions, but most of them seem have broken already before my change.

**Comment by dstftw** [comment]
As already said jwplayer extraction code should be extended to support sanitizing function calls out of options JSON. HHU extractor must be removed. Extraction should be processed by generic extractor.

**Comment by YtvwlD** [comment]
For finding the options there is already #21132 which works in this case (but isn't merged yet).

So, I'm guessing I should close this PR and open two new ones - one for dada9f6db9427f0e8738ecf6551a9a0fc865bbb0 and the other one for parsing this JS?

**Pull request closed without merging**
