### PR TITLE
[zingmp3] Set upload_date where available

### PR DESCRIPTION
**Pull request by ping**
Use album "Release Date" as upload_date for for tracks if available.

### CODE REVIEW

**Comment by dstftw** [comment]
Generally, release date is not related with date media has been uploaded. What is the rationale?

**Comment by ping** [comment]
Actually, I was taking a cue from https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/qqmusic.py#L49 where the release date was used as upload date ("发行时间" in the regex refers to Release date).

If it's not kosher, go ahead and close this. No worries.

**Comment by yan12125** [comment]
If I'm correct, QQ music have cooperation agreements with several major media companies (Warner, Sony, etc.), so songs are uploaded to QQ almost the same time as they are released by the companies. I'm not sure if it is also the case for ZingMp3. If so, it will be great to use the release date as the upload date.

**Comment by ping** [comment]
To be honest, I can't say since I'm not Vietnamese. From what I can tell, the site is very popular in Vietnam but I don't know much beyond that.

**Comment by yan12125** [comment]
I'm closing this PR now. If you find new information for ```upload_date``` or other fields, feel free to open a new pull request.

**Pull request closed without merging**
