### PR TITLE
[streamzz] Add new extractor

### PR DESCRIPTION
**Pull request by ProgrammingByPermutation**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Adding a new extractor for the https://streamzz.to website.

### CODE REVIEW

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by ProgrammingByPermutation** [comment]
> Read coding conventions.

Hi @dstftw, sorry to be dense here but can you give me a hint for what I missed? I tried my best to follow the coding conventions by providing fallbacks, making sure I used "fatal=False" everywhere appropriate, and running flake8.  Can you give me a nudge in the right direction? I'm happy to change anything necessary.

**Comment by dstftw** [comment]
Coding conventions explains everything in details. If you don't want to read it see any recent new extractor PR review. All the issues are the same.

**Comment by ProgrammingByPermutation** [comment]
@dstftw Does this commit address the coding convention issues? [https://github.com/ytdl-org/youtube-dl/pull/27984/commits/a476ada900f94a7300828d26ce19e4e395ba0a1c](a476ada)

**Comment by cypheron** [comment]
@ProgrammingByPermutation Check out #27691 - dstftw is just to lazy to check the actual code and spams that "read coding conventions" everywhere, don't get discouraged!

**Pull request closed without merging**
