### PR TITLE
[trutv] fix extraction + downloading

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This fixes TruTV extraction and downloading, and it closes https://github.com/ytdl-org/youtube-dl/issues/24102.

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
On a second look, I need to fix more. Please do not merge at this time.

**Comment by ThatNerdyPikachu** [comment]
Alright, for some reason I can't get past where the first ad would be... strange.

**Comment by roadzy** [comment]
@ThatNerdyPikachu I am trying your commit 8dd2b6a and it's downloading where before it wasn't.  I'm getting [mp4 @ 0x3645cc0] Non-monotonous DTS in output stream 0:1; previous: 27255770, current: 7100823; changing to 27255771. This may result in incorrect timestamps in the output file.

Tried a different episode of Tacoma fd and its throwing this error:


[AVBSFContext @ 0x39bae00] Error parsing ADTS frame header! bitrate=4960.8kbits/s speed=2.38x
[AVBSFContext @ 0x39bae00] Failed to receive packet from filter aac_adtstoasc for stream 0
[hls @ 0x394b3c0] Opening 'crypto+https://tve.cdn.turner.com/trutv/ce1b1e9d334df68abb07e521c31756cf/layer7/seg-0_00071.ts' for reading

Let me know if you need help testing anything else.

**Comment by roadzy** [comment]
You could take a look at mtv/nick jr.  I know they break it up in to multiple files where the adds are.

**Comment by ThatNerdyPikachu** [comment]
Will check it out -- thanks.

**Comment by sofakng** [comment]
Thanks for checking this out!  I'm using v2020.03.24 and also getting unsupported URL for TruTV.

**Comment by sofakng** [comment]
I can confirm that this patch mostly fixes TruTV.  It no longer returns unsupported URL errors.

The only issue I noticed is that I randomly get 'did not receive any datablock' errors.  I can restart youtube-dl and it will resume the download but I need to restart sometimes three or four times before it will finally complete successfully.

**Pull request closed without merging**
