### PR TITLE
[YouTube] Support @owner format in uploader_id etc

### LINKED ISSUE #31530: [YouTube] Unable to extract uploader id
**This issue is solved: read the [Description](#Description) below**
If you still want to comment after reading that, **think again**: first read [this post below](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1520185289) to avoid your comment being deleted or marked as spam.

## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2021.12.17**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

<details><summary>[YouTube] Unable to extract uploader id</summary>

```
yt-dlp.exe" -x -4 --download-archive "C:\Youtube-dlp\download_history.txt" --external-downloader aria2c --restrict-filenames --match-filter "description*='ESTRENO'" --audio-format mp3 -o "E:\FOLDER\RENAME\%%(title)s.%%(ext)s" "https://www.youtube.com/watch?v=lcusH7ksCNw&list=PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3&index=67" -v
[debug] Command-line config: ['-x', '-4', '--download-archive', 'C:\\Youtube-dlp\\download_history.txt', '--external-downloader', 'aria2c', '--restrict-filenames', '--match-filter', "description*='ESTRENO'", '--audio-format', 'mp3', '-o', 'E:\\A.PROCESAR\\RENAME\\%%(title)s.%%(ext)s', 'https://www.youtube.com/watch?v=lcusH7ksCNw&list=PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3&index=67', '-v']
[debug] Encodings: locale cp1252, fs utf-8, pref cp1252, out utf-8, error utf-8, screen utf-8
[debug] yt-dlp version 2023.01.06 [6becd25] (win_exe)
[debug] Python 3.8.10 (CPython AMD64 64bit) - Windows-10-10.0.19044-SP0 (OpenSSL 1.1.1k  25 Mar 2021)
[debug] exe versions: ffmpeg N-109541-g94aa70d757-20230109 (setts), ffprobe N-109541-g94aa70d757-20230109, phantomjs 2.1.1
[debug] Optional libraries: Cryptodome-3.16.0, brotli-1.0.9, certifi-2022.12.07, mutagen-1.46.0, sqlite3-2.6.0, websockets-10.4
[debug] Proxy map: {}
[debug] Loaded 1760 extractors
[debug] Loading archive file 'C:\\Youtube-dlp\\ download_history.txt'
[youtube:tab] Extracting URL: https://www.youtube.com/watch?v=lcusH7ksCNw&list=PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3&index=67
[youtube:tab] Downloading playlist PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3 - add --no-playlist to download just the video lcusH7ksCNw
[youtube:tab] PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3: Downloading webpage
[youtube:tab] Extracting URL: https://www.youtube.com/playlist?list=PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3
[youtube:tab] PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3: Downloading webpage
[youtube:tab] PLuXU-g7mjkKPvWSFq7xI_N4Xj7A3iSOU3: Redownloading playlist API JSON with unavailable videos
[download] Downloading playlist: LA VENGANZA SERÁ TERRIBLE (Programas)
[youtube:tab] Playlist LA VENGANZA SERÁ TERRIBLE (Programas): Downloading 67 items of 67
[download] Downloading item 1 of 67
[youtube] Extracting URL: https://www.youtube.com/watch?v=3h5-QPbKoVg
[youtube] 3h5-QPbKoVg: Downloading webpage
[youtube] 3h5-QPbKoVg: Downloading android player API JSON
[debug] Loading youtube-nsig.1cbba2b4 from cache
WARNING: [youtube] 3h5-QPbKoVg: Native nsig extraction failed: Trying with PhantomJS
         n = GDZ_5inyZ3r6QSP ; player = https://www.youtube.com/s/player/1cbba2b4/player_ias.vflset/en_US/base.js
[debug] [youtube] Signature function returned an exception; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
[youtube] 3h5-QPbKoVg: Executing signature code
[debug] [youtube] PhantomJS command line: phantomjs "--ssl-protocol=any" "C:\Users\USER\AppData\Local\Temp\tmp88untizd"
[debug] [youtube] Decrypted nsig GDZ_5inyZ3r6QSP => ECvndyupC0ex4A
ERROR: [youtube] 3h5-QPbKoVg: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
  File "yt_dlp\extractor\common.py", line 680, in extract
  File "yt_dlp\extractor\youtube.py", line 4049, in _real_extract
  File "yt_dlp\extractor\common.py", line 1228, in _search_regex
```
</details>

<a id=Description>

## Description

</a>

[Revised by @dirkf]
OP actually reported the bug for _yt-dlp_.

The problem, which was revealed by a change in the metadata served by YouTube, applied to both [_youtube-dl_](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433230848) and [_yt-dlp_](https://github.com/yt-dlp/yt-dlp/issues/6247) and has been fixed in both programs.

There is a release of [_yt-dlp_](https://github.com/yt-dlp/yt-dlp) that includes the fix. See #31535 for discussion of whether this would be a good choice for you.

**See [below](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435975611) for ways to update to a fixed version of _youtube-dl_**. Using `-U` doesn't (yet) work. [A new release may be created, including the final fix, some time later than now](https://github.com/ytdl-org/youtube-dl/issues/31585).

There's **no point posting your log that shows the error** now: feel free to thumb-up [this post](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433230848). Also, be aware that the initial patch still flagged the original issue [as a WARNING](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1436130288); the [fully fixed yt-dl](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1443615453) doesn't. [Consider raising a separate issue](https://github.com/ytdl-org/youtube-dl/issues/30839) if your fixed yt-dl shows a different error.

### PR DESCRIPTION
**Pull request by dirkf**
<details>
<summary>Boilerplate: own code, bug fix</summary>
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

</details>

### Description of your *pull request* and other information

According to #31530, YouTube has changed its metadata so that the owner URL has the format `.../@ownerslug` rather than `.../user/user_id` or `.../channel/channel_id`. Some, if not all, music videos retain the previous scheme.

This caused several problems:
1. Owing to an extraction bug, failing to match the previous patterns crashed the extractor.
2. After resolving the crash, various metadata items were not being extracted, and some [study was needed to work out what values should be extracted](https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435734719).
3. The resolution of this meant that many tests failed.

Proposed final resolution from linked post:
* `uploader` is the author text value
* `channel` is the same
* `uploader_id` becomes the @... value
* `channel_id` is `channelId`
* `uploader_url` is the author URL with /@...
* `channel_url` is `/channel/{channel_id}` at least while that is valid.

The linked post identifies that these metadata items may be available in various parts of the YT webpage, with slightly different access paths depending on the page type.

Thus, this PR
1. updates the YouTube extractor to handle the new format
2. returns values as proposed in https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1435734719
3. updates the tests affected by the changes
4. to support one of the tests, solves a long-standing issue in the download test that prevented testing cases where the `id` changed.

Closes #31568
Resolves #31530

### CODE REVIEW

**Comment by dirkf** [comment]
These tests pass locally but not in CI:
```log
2023-02-24T03:41:39.4591969Z ======================================================================
2023-02-24T03:41:39.4592162Z FAIL: test_YoutubePlaylist_2 (test.test_download.TestDownload):
2023-02-24T03:41:39.4592438Z ----------------------------------------------------------------------
2023-02-24T03:41:39.4592564Z Traceback (most recent call last):
2023-02-24T03:41:39.4592944Z   File "/home/runner/work/youtube-dl/youtube-dl/test/test_download.py", line 192, in test_template
2023-02-24T03:41:39.4593104Z     len(res_dict['entries'])))
2023-02-24T03:41:39.4593493Z   File "/home/runner/work/youtube-dl/youtube-dl/test/helper.py", line 266, in assertGreaterEqual
2023-02-24T03:41:39.4593638Z     self.assertTrue(got >= expected, msg)
2023-02-24T03:41:39.4593974Z AssertionError: Expected at least 1 in playlist https://www.youtube.com/embed/videoseries?list=PL6IaIsEjSbf96XFRuNccS_RuEXwNdsoEu, but got only 0
2023-02-24T03:41:39.4594254Z -------------------- >> begin captured stdout << ---------------------
2023-02-24T03:41:39.4594455Z [youtube:tab] PL6IaIsEjSbf96XFRuNccS_RuEXwNdsoEu: Downloading webpage
2023-02-24T03:41:39.4594594Z [download] Downloading playlist: JODA15
2023-02-24T03:41:39.4594749Z [youtube:tab] playlist JODA15: Downloading 0 videos
2023-02-24T03:41:39.4594907Z [download] Finished downloading playlist: JODA15
2023-02-24T03:41:39.4594916Z 
2023-02-24T03:41:39.4595193Z --------------------- >> end captured stdout << ----------------------
2023-02-24T03:41:39.4595201Z 
2023-02-24T03:41:39.4595314Z ======================================================================
2023-02-24T03:41:39.4595497Z FAIL: test_YoutubeTab_20 (test.test_download.TestDownload):
2023-02-24T03:41:39.4595767Z ----------------------------------------------------------------------
2023-02-24T03:41:39.4596076Z Traceback (most recent call last):
2023-02-24T03:41:39.4596472Z   File "/home/runner/work/youtube-dl/youtube-dl/test/test_download.py", line 192, in test_template
2023-02-24T03:41:39.4596647Z     len(res_dict['entries'])))
2023-02-24T03:41:39.4597023Z   File "/home/runner/work/youtube-dl/youtube-dl/test/helper.py", line 266, in assertGreaterEqual
2023-02-24T03:41:39.4597169Z     self.assertTrue(got >= expected, msg)
2023-02-24T03:41:39.4597425Z AssertionError: Expected at least 350 in playlist https://www.youtube.com/hashtag/cctv9, but got only 339
2023-02-24T03:41:39.4597704Z -------------------- >> begin captured stdout << ---------------------
2023-02-24T03:41:39.4597826Z [youtube:tab] cctv9: Downloading webpage
2023-02-24T03:41:39.4597964Z [download] Downloading playlist: #cctv9
2023-02-24T03:41:39.4598090Z [youtube:tab] Downloading page 1
2023-02-24T03:41:39.4598211Z [youtube:tab] Downloading page 2
2023-02-24T03:41:39.4598333Z [youtube:tab] Downloading page 3
2023-02-24T03:41:39.4598459Z [youtube:tab] Downloading page 4
2023-02-24T03:41:39.4598579Z [youtube:tab] Downloading page 5
2023-02-24T03:41:39.4598720Z [youtube:tab] playlist #cctv9: Downloading 339 videos
2023-02-24T03:41:39.4598850Z [download] Downloading video 1 of 339
2023-02-24T03:41:39.4598979Z [download] Downloading video 2 of 339
...
2023-02-24T03:41:39.4650471Z [download] Downloading video 338 of 339
2023-02-24T03:41:39.4650595Z [download] Downloading video 339 of 339
2023-02-24T03:41:39.4650765Z [download] Finished downloading playlist: #cctv9
2023-02-24T03:41:39.4650935Z 
2023-02-24T03:41:39.4651433Z --------------------- >> end captured stdout << ----------------------
2023-02-24T03:41:39.4651442Z 
2023-02-24T03:41:39.4651570Z ======================================================================
```
Presumably there is some regional difference in the availability of the playlist items.

**Comment by Tectract** [comment]
Does this mean I can update youtube-dl using youtube-dl -U and get the fix now?

**Comment by dirkf** [comment]
No. That requires an actual release.

**Comment by Tectract** [comment]
I don't really understand the difference between merging a commit into the master branch, and doing a release. Isn't that the same thing?

**Comment by dirkf** [comment]
Starting from a selected commit, there's preparation (eg changelog), and a build step, and a deployment step to make the built versions available.

**Comment by ToddAndMargo** [comment]
On 3/3/23 16:14, dirkf wrote:
> Starting from a selected commit, there's preparation (eg changelog), and 
> a build step, and a deployment step to make the built versions available.
> 

Would you consider posting it to this ticket when that occurs?

**Comment by xk** [comment]
@dirkf Could you please please please make a new release now?

**Comment by dirkf** [comment]
Follow #31350.

**Comment by CeliaBlorville** [comment]
Thank you @dirkf for the fix ! Everything goes fine now :)

**Comment by varelycode** [comment]
Tried to upgrade with brew the version there is from 2021 

Warning: youtube-dl 2021.12.17 already installed

**Comment by dirkf** [comment]
> Tried to upgrade with brew the version there is from 2021

Read #31530.

**Comment by ArticRigid** [comment]
Today this is happening again: (with the last version 2021.12.17) 

youtube-dl -F https://www.youtube.com/watch?v=bYsDfGASWV4

[youtube] bYsDfGASWV4: Downloading webpage
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by gosuto-inzasheru** [comment]
idem:
```
youtube-dl https://www.youtube.com/watch\?v\=yY9lL4Jxkd8 --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.youtube.com/watch?v=yY9lL4Jxkd8', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.12.17
[debug] Git HEAD: ac0663ae5
[debug] Python version 3.11.3 (CPython) - macOS-13.3.1-arm64-arm-64bit
[debug] exe versions: none
[debug] Proxy map: {}
[youtube] yY9lL4Jxkd8: Downloading webpage
WARNING: unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on 'https://rr5---sn-oguesndl.googlevideo.com/videoplayback?expire=1681979600&ei=cKRAZJ3YBsKDrQTGq5bwDg&ip=37.19.205.225&id=o-AAbyL4vJ9FwrvwJ_Xj66ErrhKEQAJnyEL4SH9x4SltSA&itag=22&source=youtube&requiressl=yes&mh=HU&mm=31%2C29&mn=sn-oguesndl%2Csn-oguelnl7&ms=au%2Crdu&mv=m&mvi=5&pl=24&initcwndbps=733750&vprv=1&mime=video%2Fmp4&ns=sta-jV5M0zXOaAT29ONiE7gM&cnr=14&ratebypass=yes&dur=403.284&lmt=1681930934724193&mt=1681957731&fvip=5&fexp=24007246&c=WEB&txp=5318224&n=KvP63n5rHoQuri&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIhANfYYAoltP5niJL0ejb7eEyLkJBJ3yp1LMzyrYzuvABgAiA7hfSBvtdUX5j8UuuMWRsIjZShOg-w9vjNuN5a-moSPw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRAIgWBuzeXhs3MCj0JzexJoeCFtuRFPFbG6Zh0gklb2YA0kCIDxnG-larL5FRW1Gm589jhEdUmN12a7RrbciMWoe1V9q'
[download] Error _ Testing with Foundry-yY9lL4Jxkd8.mp4 has already been downloaded
[download] 100% of 15.53MiB
```

**Comment by benjibasson83** [comment]
Hi, Youtube-dl said it is up too date although it is obsolete since February 2012. ( Broken support for YouTube)

pip install --upgrade youtube-dl give
Requirement already satisfied: youtube-dl in /data/data/com.termux/files/usr/lib/python3.11/site-packages (2021.12.17)

Please give me the fix for youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
return func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
ie_result = ie.extract(url)
^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
ie_result = self._real_extract(url)
^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.


Add a quote, <Ctrl+Shift+.>
Add code, <Ctrl+e>
Add a link, <Ctrl+k>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply

**Comment by benjibasson83** [comment]
## Checklist



- [ x] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [x ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [ x] I've searched the bugtracker for similar bug reports including closed ones
- [x ] I've read bugs section in FAQ


## Verbose log



```
youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```


## Description



Hi
pip install --upgrade --force-reinstall git+https://github.com/ytdl-org/youtube-dl.git
Collecting git+https://github.com/ytdl-org/youtube-dl.git
Give 
```
  Cloning https://github.com/ytdl-org/youtube-dl.git to /data/data/com.termux/files/usr/tmp/pip-req-build-zvolm8k6
  ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
```


pip install --upgrade youtube-dl give
`Requirement already satisfied: youtube-dl in /data/data/com.termux/files/usr/lib/python3.11/site-packages (2021.12.17)`

YouTube dl doesn't work for 3 mounth and there is zero solution. Zero fix although in this forum it is printed it has been fixed and that there is a 2023's update 
Please give me the fix for

 ```
youtube-dl --no-cache-dir --extract-audio --audio-format mp3 -w -i -o "%(title)s.%(ext)s" https://m.youtube.com/watch?v=JQCD5LBJ1jU --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--no-cache-dir', '--extract-audio', '--audio-format', 'mp3', '-w', '-i', '-o', '%(title)s.%(ext)s', 'https://m.youtube.com/watch?v=JQCD5LBJ1jU', '--verbose']
[debug] Encodings: locale utf-8, fs utf-8, out utf-8, pref utf-8
[debug] youtube-dl version 2021.12.17
[debug] Python version 3.11.3 (CPython) - Linux-4.19.157-perf+-aarch64-with-libc
[debug] exe versions: ffmpeg 6.0, ffprobe 6.0
[debug] Proxy map: {}
[youtube] JQCD5LBJ1jU: Downloading webpage
[youtube] JQCD5LBJ1jU: Downloading MPD manifest
ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
                ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by truebit** [comment]
we could use `brew install youtube-dl --HEAD` to install latest version

**Comment by dirkf** [comment]
>we could use `brew install youtube-dl --HEAD` to install latest version

The _homebrew_ people seem very unwilling to promote `--HEAD`, so it isn't recommended in #31530 even though (disclaimer: I don't use _homebrew_) it would normally be a better solution than the patch they added.

**Comment by makwanji** [comment]
Hello, I am still getting this issue in Ubuntu. 
OS : 5.19.0-1024-aws

Already updated:

ubuntu@ip-10-0-54-72:~$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

**Pull request merged**
