### PR TITLE
[Youtube] flat-playlist extractor correction for playlist results and added duration fetching for video results and playlist video count

### PR DESCRIPTION
**Pull request by Crypto90**
#25848 #25720 #16627 #25652

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

I have made some changes for the youtube.py extractor to add the new feature to get correct results when searching youtube playlists.
The changed code checks if the /wach?v= url also contains list=, if so, also the playlist id gets extracted.
The printed result will also be checked for the video id length (11 = video id, larger than 11 = playlist id)

RESULTS searching for playlists:
```
python youtube-dl -4 --no-warnings --no-check-certificate "ytsearch10:nightcore,playlist" --dump-json --playlist-start 1 --playlist-end 10 --flat-playlist
{"url": "https://www.youtube.com/playlist?list=PL0wqt_um4x0bsdViTJBmnl6KGMoSqxfZy", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PL0wqt_um4x0bsdViTJBmnl6KGMoSqxfZy", "title": "Most Viewed Nightcore"}
{"url": "https://www.youtube.com/playlist?list=PLckeMyCaCCIN_JU1V4oADW50DlGOREoLj", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLckeMyCaCCIN_JU1V4oADW50DlGOREoLj", "title": "Ultimatum [Nightcore playlist]"}
{"url": "https://www.youtube.com/playlist?list=PLyTi20i8cwsPyiwvjei-K6F04Rzm0uRpT", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLyTi20i8cwsPyiwvjei-K6F04Rzm0uRpT", "title": "Old School Nightcore"}
{"url": "https://www.youtube.com/playlist?list=PLMk3t51Sma9Ez2tjSzks3N06cwckoz2-m", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLMk3t51Sma9Ez2tjSzks3N06cwckoz2-m", "title": "NightCore Emo"}
{"url": "https://www.youtube.com/playlist?list=PLT5Nlf1NmV4Mqfha4j1YuCTk0GCL20bdN", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLT5Nlf1NmV4Mqfha4j1YuCTk0GCL20bdN", "title": "BoxBox Nightcore COMPLETE"}
{"url": "https://www.youtube.com/playlist?list=PLOTApxgUwuOKLxLhKAs8IVY7gPO7jBzD2", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLOTApxgUwuOKLxLhKAs8IVY7gPO7jBzD2", "title": "Nightcore - Gacha Songs"}
{"url": "https://www.youtube.com/playlist?list=PL_2-M0cHcLO4PYOoiyq0PxOeHqGlhlnmQ", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PL_2-M0cHcLO4PYOoiyq0PxOeHqGlhlnmQ", "title": "The Ultimate Nightcore Playlist"}
{"url": "https://www.youtube.com/playlist?list=PLT2qINU1sbUh0ECl94rEWddz9dLA10t6H", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLT2qINU1sbUh0ECl94rEWddz9dLA10t6H", "title": "Nightcore Playlist"}
{"url": "https://www.youtube.com/playlist?list=PLM6aAK5yk-8KWSSW8zJCBkNCP_Kvom6S5", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLM6aAK5yk-8KWSSW8zJCBkNCP_Kvom6S5", "title": "Sexual Nightcore Songs"}
{"url": "https://www.youtube.com/playlist?list=PLNNA4xoj8rtiyGCKKW-ZJAgE07puDN9wb", "_type": "url", "ie_key": "YoutubePlaylist", "id": "PLNNA4xoj8rtiyGCKKW-ZJAgE07puDN9wb", "title": "Upbeat Nightcore"}

```

RESULTS searching for single videos:
```
python youtube-dl -4 --no-warnings --no-check-certificate "ytsearch10:nightcore,video" --dump-json --playlist-start 1 --playlist-end 10 --flat-playlist
{"url": "fSlOHZXhcMk", "_type": "url", "ie_key": "Youtube", "id": "fSlOHZXhcMk", "title": "Nightcore - Dracula - (Lyrics)"}
{"url": "0NSCkfyA6uY", "_type": "url", "ie_key": "Youtube", "id": "0NSCkfyA6uY", "title": "Nightcore - Stick Together"}
{"url": "nuTsXUYUavw", "_type": "url", "ie_key": "Youtube", "id": "nuTsXUYUavw", "title": "Nightcore - What You Made Me - (Lyrics)"}
{"url": "E3FfwK81OsU", "_type": "url", "ie_key": "Youtube", "id": "E3FfwK81OsU", "title": "Nightcore - Savage Love - (Lyrics)"}
{"url": "hjGZLnja1o8", "_type": "url", "ie_key": "Youtube", "id": "hjGZLnja1o8", "title": "Nightcore - Rockefeller Street"}
{"url": "9xG5aPvrS-k", "_type": "url", "ie_key": "Youtube", "id": "9xG5aPvrS-k", "title": "Nightcore - No Friends (Lyrics)"}
{"url": "cvaIgq5j2Q8", "_type": "url", "ie_key": "Youtube", "id": "cvaIgq5j2Q8", "title": "Nightcore - Angel With A Shotgun"}
{"url": "Zm1vKR2hNyc", "_type": "url", "ie_key": "Youtube", "id": "Zm1vKR2hNyc", "title": "Nightcore - Odds Are - (Lyrics)"}
{"url": "z6lJlIp9Y50", "_type": "url", "ie_key": "Youtube", "id": "z6lJlIp9Y50", "title": "Nightcore - Tick Tick Tick - (Lyrics)"}
{"url": "cyW2ajAVyfA", "_type": "url", "ie_key": "Youtube", "id": "cyW2ajAVyfA", "title": "Nightcore - Take A Hint"}

```

UPDATE 1:
I have also changed the video regex to fetch the video durations and added duration variable to url_result(...) function in common.py.
 

Other topic relations:
https://github.com/ytdl-org/youtube-dl/issues/25720
https://github.com/ytdl-org/youtube-dl/issues/16627
https://github.com/ytdl-org/youtube-dl/issues/25652

### CODE REVIEW

**Comment by Crypto90** [comment]
Can someone add the last step to return:
yield self.url_result(video_id, 'Youtube', video_id, video_title, video_duration)
?

self.url_result(...) needs a 5th argument for the video duration.

**Comment by Crypto90** [comment]
Edited common.py to add "duration" argument to url_result(...) function and now passing video duration to url_result for search video results.

**Comment by Crypto90** [comment]
As far as I can see, the other 3-4 places which call the "extract_videos_from_page_impl" function needs now also the 4th argument (duration array)

**Comment by Crypto90** [comment]
I run into one issue since the code changes with ytsearchall and a playlist link, which worked before, any hints?

```
python youtube-dl -4 --no-warnings --no-check-certificate --default-search ytsearchall "https://www.youtube.com/playlist?list=PLMk3t51Sma9Ez2tjSzks3N06cwckoz2-m" --dump-json --flat-playlist
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "youtube-dl/__main__.py", line 19, in <module>
  File "youtube-dl/youtube_dl/__init__.py", line 474, in main
  File "youtube-dl/youtube_dl/__init__.py", line 464, in _real_main
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 2018, in download
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 807, in extract_info
  File "youtube-dl/youtube_dl/YoutubeDL.py", line 968, in process_ie_result
  File "youtube-dl/youtube_dl/extractor/youtube.py", line 314, in _entries
KeyError: u'content_html'

```

**Comment by Crypto90** [comment]
Is it mandatory to return "https://www.youtube.com/playlist?list=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" or can we also return "https://www.youtube.com/watch?v=YYYYYYYYYYY&list=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" as url value?
If we can return the second one too, would be better, because this way we still have the first video ID inside the playlist in the url string and we can generate the cover image url from the video id for frontend usage.
If we only return "https://www.youtube.com/playlist?list=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX" as url, we loose the first video ID inside the playlist which also represents the playlist cover image.

**Comment by Crypto90** [comment]
Can someone verify the changes?

**Comment by Crypto90** [comment]
Got everything working fine.
One last thing todo, parsing the duration for each video result on paring playlist content:

youtube.py:
```
 def extract_videos_from_page(self, page):
        ids_in_page = []
        titles_in_page = []
        durations_in_page = []
        print page

        for item in re.findall(
                r'(<[^>]*\bdata-video-id\s*=\s*["\'][0-9A-Za-z_-]{11}[^>]+>)', page):
            attrs = extract_attributes(item)
            video_id = attrs['data-video-id']
            video_title = unescapeHTML(attrs.get('data-title'))
            if video_title:
                video_title = video_title.strip()
            ids_in_page.append(video_id)
            titles_in_page.append(video_title)
            # TODO: ADD VIDEO DURATION HERE TOO?
            durations_in_page.append(None)

```

We need to get the durations from each video with the regex too, and add the duration to:
```
durations_in_page.append(None) <----- replace None with the duration found with the needed regex
```

Can someone help here?

**Comment by Crypto90** [comment]
Added functionality to extract youtube playlist results videos count and return it as duration parameter:

Search results for playlists with playlist video count as durations:
```
python youtube-dl -4 --no-warnings --no-check-certificate "ytsearch10:nightcore,playlist" --dump-json --playlist-start 1 --playlist-end 10 --flat-playlist
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "Most Viewed Nightcore", "url": "https://www.youtube.com/playlist?list=PL0wqt_um4x0bsdViTJBmnl6KGMoSqxfZy", "duration": "352", "id": "PL0wqt_um4x0bsdViTJBmnl6KGMoSqxfZy"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "Ultimatum [Nightcore playlist]", "url": "https://www.youtube.com/playlist?list=PLckeMyCaCCIN_JU1V4oADW50DlGOREoLj", "duration": "126", "id": "PLckeMyCaCCIN_JU1V4oADW50DlGOREoLj"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "BoxBox Nightcore COMPLETE", "url": "https://www.youtube.com/playlist?list=PLT5Nlf1NmV4Mqfha4j1YuCTk0GCL20bdN", "duration": "139", "id": "PLT5Nlf1NmV4Mqfha4j1YuCTk0GCL20bdN"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "NightCore Emo", "url": "https://www.youtube.com/playlist?list=PLMk3t51Sma9Ez2tjSzks3N06cwckoz2-m", "duration": "285", "id": "PLMk3t51Sma9Ez2tjSzks3N06cwckoz2-m"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "Old School Nightcore", "url": "https://www.youtube.com/playlist?list=PLyTi20i8cwsPyiwvjei-K6F04Rzm0uRpT", "duration": "78", "id": "PLyTi20i8cwsPyiwvjei-K6F04Rzm0uRpT"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "Nightcore - Gacha Songs", "url": "https://www.youtube.com/playlist?list=PLOTApxgUwuOKLxLhKAs8IVY7gPO7jBzD2", "duration": "127", "id": "PLOTApxgUwuOKLxLhKAs8IVY7gPO7jBzD2"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "Nightcore Playlist", "url": "https://www.youtube.com/playlist?list=PLT2qINU1sbUh0ECl94rEWddz9dLA10t6H", "duration": "3,277", "id": "PLT2qINU1sbUh0ECl94rEWddz9dLA10t6H"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "The Ultimate Nightcore Playlist", "url": "https://www.youtube.com/playlist?list=PL_2-M0cHcLO4PYOoiyq0PxOeHqGlhlnmQ", "duration": "152", "id": "PL_2-M0cHcLO4PYOoiyq0PxOeHqGlhlnmQ"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "newest nightcore songs 2014/2015", "url": "https://www.youtube.com/playlist?list=PLlicIl02Y7VpZGQnyd165Ib1AYsSgNson", "duration": "41", "id": "PLlicIl02Y7VpZGQnyd165Ib1AYsSgNson"}
{"_type": "url", "ie_key": "YoutubePlaylist", "title": "Sexual Nightcore Songs", "url": "https://www.youtube.com/playlist?list=PLM6aAK5yk-8KWSSW8zJCBkNCP_Kvom6S5", "duration": "52", "id": "PLM6aAK5yk-8KWSSW8zJCBkNCP_Kvom6S5"}
```

Search results for videos with video duration as durations:
```
python youtube-dl -4 --no-warnings --no-check-certificate "ytsearch10:nightcore,video" --dump-json --playlist-start 1 --playlist-end 10 --flat-playlist
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Oops!...I Did It Again - (Lyrics)", "url": "SuViEV1VdhI", "duration": "3:00", "id": "SuViEV1VdhI"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Stick Together", "url": "0NSCkfyA6uY", "duration": "2:47", "id": "0NSCkfyA6uY"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Savage Love - (Lyrics)", "url": "E3FfwK81OsU", "duration": "2:33", "id": "E3FfwK81OsU"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - No Friends (Lyrics)", "url": "9xG5aPvrS-k", "duration": "3:32", "id": "9xG5aPvrS-k"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Angel With A Shotgun", "url": "cvaIgq5j2Q8", "duration": "3:13", "id": "cvaIgq5j2Q8"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Dracula - (Lyrics)", "url": "fSlOHZXhcMk", "duration": "2:56", "id": "fSlOHZXhcMk"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Rockefeller Street", "url": "hjGZLnja1o8", "duration": "2:28", "id": "hjGZLnja1o8"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Phoenix (Lyrics)", "url": "_VA6eSOO88M", "duration": "2:55", "id": "_VA6eSOO88M"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Odds Are - (Lyrics)", "url": "Zm1vKR2hNyc", "duration": "2:34", "id": "Zm1vKR2hNyc"}
{"_type": "url", "ie_key": "Youtube", "title": "Nightcore - Take A Hint", "url": "cyW2ajAVyfA", "duration": "2:08", "id": "cyW2ajAVyfA"}

```

**Comment by dstftw** [comment]
No longer actual.

**Pull request closed without merging**
