### PR TITLE
[eHow] Updated URL regex matching

### PR DESCRIPTION
**Pull request by MobiDotS**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fixes https://github.com/ytdl-org/youtube-dl/issues/22649 by updating the URL regex since eHow changed their URL structure.

### CODE REVIEW

**Comment by dstftw** [comment]
Breaks lld schema URLs that is still in use.

**Comment by dstftw** [comment]
Also, does not work at all:
```
> py -2.7 .\youtube_dl\__main__.py https://www.ehow.com/13718302/diy-colorful-abstract-art-coasters
[eHow] 13718302: Downloading webpage
ERROR: Unable to download webpage: [Errno 10054] An existing connection was forcibly closed by the remote host (caused by error(10054, 'An existing connection was forcibly closed by the remote host')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by MobiDotS** [comment]
@dstftw I updated the regex to match old and new URLs. I've been fighting python for the past few days on why it's timing out when requesting the website. I recreated the request via Postman with the same headers but it's working on there but not in python. If you have any suggestions to try, I would love to hear them.

I broke it down to the basics and tried using `httplib` directly as so:

```
url = 'www.ehow.com'
conn = httplib.HTTPSConnection(url, timeout=15)
conn.request("GET", "/13721995/simply-awesome-pumpkin-carving-hacks")
r1 = conn.getresponse()
```

but this is also timing out.

**Comment by MobiDotS** [comment]
Will re-open once I figure out the timing out issue.

**Pull request closed without merging**
