### PR TITLE
[zattoo] Fix broken extractor (closes #22258)

### LINKED ISSUE #22258: [Zattoo] Update site web
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

```
NEW ADRESS:
youtube-dl https://zattoo.com/channels\?channel\=rts_un --username **** --password *** -f hls-3002-A-1500 --o "RTS Un - NCIS S16E13.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://zattoo.com/channels?channel=rts_un', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', 'hls-3002-A-1500', '--o', 'RTS Un - NCIS S16E13.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.5.3 (CPython) - Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[generic] channels?channel=rts_un: Requesting header
WARNING: Falling back on generic information extractor.
[generic] channels?channel=rts_un: Downloading webpage
[generic] channels?channel=rts_un: Extracting information
ERROR: Unsupported URL: https://zattoo.com/channels?channel=rts_un
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/generic.py", line 3333, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: https://zattoo.com/channels?channel=rts_un

[1]    2458 exit 1     youtube-dl https://zattoo.com/channels\?channel\=rts_un --username  --passwor

OLD ADRESS:

youtube-dl https://zattoo.com/watch/rts_un --username **** --password *** -f hls-3002-A-1500 --o "RTS Un - NCIS S16E13.mp4" -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://zattoo.com/watch/rts_un', '--username', 'PRIVATE', '--password', 'PRIVATE', '-f', 'hls-3002-A-1500', '--o', 'RTS Un - NCIS S16E13.mp4', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.08.13
[debug] Python version 3.5.3 (CPython) - Linux-4.19.0-0.bpo.5-amd64-x86_64-with-debian-9.9
[debug] exe versions: ffmpeg 3.2.14-1, ffprobe 3.2.14-1
[debug] Proxy map: {}
[ZattooLive] Downloading app token
[ZattooLive] Opening session
ERROR: Unable to download webpage: HTTP Error 400: Bad Request (caused by <HTTPError 400: 'Bad Request'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/extractor/common.py", line 627, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/usr/local/lib/python3.5/dist-packages/youtube_dl/YoutubeDL.py", line 2229, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

[1]    2502 exit 1     youtube-dl https://zattoo.com/watch/rts_un --username ****


```

## Description

New website, with new address to access the channel.
Example for RTS One, formerly: https://zattoo.com/watch/rts_un
New address: https://zattoo.com/channels?channel=rts_un
The 2 addresses no longer works on Youtube-DL
If need ids to make tests, thank you to contact me in private at the address rectv.forum@gmail.com
Thank.

### PR DESCRIPTION
**Pull request by goggle**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This PR fixes the currently broken Zattoo information extractor.
It supersedes my old PR #22759, which does not work anymore because of changes in the initialization process.
Note that this PR only fixes Zattoo, not the Zattoo resellers (I do not have access to any of them).

If this should be merged, someone with a Zattoo Premium account needs to provide account credentials to a maintainer of youtube-dl!

### CODE REVIEW

**Comment by goggle** [comment]
I'm not sure why the URL matching tests are failing. If anyone sees an easy fix, just tell me.

**Comment by remitamine** [comment]
I think it's caused by `|` in the `ZattooIE`:that causes [the second part of the regex](https://github.com/ytdl-org/youtube-dl/blob/49b4b838cb3b129d3adef071d3964e0c29d2eca4/youtube_dl/extractor/zattoo.py#L304-L310) to match regardless of domain.
https://github.com/ytdl-org/youtube-dl/blob/49b4b838cb3b129d3adef071d3964e0c29d2eca4/youtube_dl/extractor/zattoo.py#L303
that causes the second part of the regex:

**Comment by orangerkater** [comment]
>If this should be merged, someone with a Zattoo Premium account needs to provide account credentials to a maintainer of youtube-dl!

Whom shall I provide the credentials?

**Comment by orangerkater** [comment]
The did not react until now. Is by change any other maintainer interested?

**Comment by 0x4d4e** [comment]
I tried to download a recording from Zattoo and it only worked after these changes (based on the source branch of this merge request). I did not further troubleshoot the changes in _real_extract - they work for downloading recordings and since I won't be using Zattoo any further this is all that I was after.

FYI: if someone needs credentials to check the changes, there is the option to use the free trial of Zattoo (30days, CC/Paypal required).

```
index 11a20c27e..a7c2c6ff0 100644
--- a/youtube_dl/extractor/zattoo.py
+++ b/youtube_dl/extractor/zattoo.py
@@ -300,7 +300,8 @@ class ZattooIE(ZattooBaseIE):
                                 (?:
                                     ondemand/videos/([A-Za-z0-9]+)|
                                     (?:program|watch)/([^/]+)/(\d+)|
-                                    live/([^/]+)
+                                    live/([^/]+)|
+                                    recording/([0-9]+)
                                 )|
                                 (?:
                                     .+\?recording=([0-9]+)|
@@ -342,11 +343,12 @@ class ZattooIE(ZattooBaseIE):
     }]

     def _real_extract(self, url):
-        oid1, cid1, pid1, cid2, record_id, oid2, cid3, pid2 = re.match(
+        oid1, cid1, pid1, cid2, rid1, rid2, oid2, cid3, pid2, = re.match(
             self._VALID_URL, url).groups()
         ondemand_id = oid1 or oid2
         channel_id = cid1 or cid2 or cid3
         program_id = pid1 or pid2
+        record_id = rid1 or rid2
         if record_id:
             return self._extract_record(record_id)
         elif ondemand_id:
```

**Comment by goggle** [comment]
If anyone is interested: A follow-up PR has been merged into `yt-dlp`: https://github.com/yt-dlp/yt-dlp/pull/2288

**Pull request closed without merging**
