### PR TITLE
[bravotv] fix drupal settings parser, add atlanticbb

### LINKED ISSUE #19213: [bravo] Unable to extract drupal settings
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2019.02.08*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2019.02.08**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)

---

---

```
E:\>youtube-dl --verbose https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang']
[debug] Encodings: locale cp1252, fs mbcs, out cp437, pref cp1252
[debug] youtube-dl version 2019.02.08
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.17134
[debug] exe versions: ffmpeg N-92986-gaceb9131c1, ffprobe N-92986-gaceb9131c1, rtmpdump 2.4
[debug] Proxy map: {}
[BravoTV] ep-10-so-vain-in-solvang: Downloading webpage
ERROR: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\YoutubeDL.py", line 794, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 508, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\bravotv.py", line 35, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmp6w61832c\build\youtube_dl\extractor\common.py", line 983, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract drupal settings; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
<end of log>
```

---
### Description of your *issue*, suggested solution and other information

Something has apparently changed with Bravo within the last week. All videos produce this error: "Unable to extract drupal settings."

I get the same result with or without MSO credentials.

### PR DESCRIPTION
**Pull request by nevafuse**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Fix regex parser to retrieve information to build download link.  Also support new download link format.  Fixes #19213 and #20284.

### CODE REVIEW

**Comment by NGTmeaty** [comment]
There seems to be a few changes that happened on the Bravo side. They seemed to have removed ratings and "release_pid" from the drupal settings. https://www.bravotv.com/the-real-housewives-of-beverly-hills/season-9/ep-1-lucy-lucy-apple-juicy should work as test URL. The release_pid seems to only be contained here:

`<div id="pdk-player" data-width="448" data-height="252" data-url="https://player.theplatform.com/p/HNK2IC/aO3boJhesuo7/select/media/cCdxFF_SoYPn?playAll=true&amp;excludeSharing=true&amp;fwsitesection=bravo_tveverywhere_vod_hub"></div>`

This may require a bit of work to extract the release PID from here as it's the only place it seems to be mentioned at all. Everything else should work though!

**Comment by nevafuse** [comment]
I tried using that release pid, but it returned an error.  I noticed theplatform accepts a few url formats & the player_base_url link worked (which is in the Drupal settings).  Not 100% sure why my first merge didn't work but now I'm choosing the link at the last possible spot which seems to work for both url types.

**Comment by NGTmeaty** [comment]
In the above link, I didn't see a player base url.

**Comment by nevafuse** [comment]
I don't have a subscription to access this video (assumed it was the same as another I was looking at).  When I get a second, I'll try to find a subscription and play around with it.

**Comment by NGTmeaty** [comment]
Yup. It seems to be slightly different. Let me try to send you a copy of what I'm seeing here.

**Comment by roadzy** [comment]
Can you point me to instructions on how to test this?  I don't know how to a branch.  Do I need to compile something from scratch?  I'll be glad to test this if someone can give me some direction.

**Comment by NGTmeaty** [comment]
Hey sorry. Just got this. @roadzy this change isn't _totally_ done as it seems we missed a few changes that were very recently made. I'll see if I can get started on that today. @nevafuse may be able to help more as well.

**Comment by roadzy** [comment]
@NGTmeaty @nevafuse if you need an account to test this with, let me know I have one you can use.

**Comment by nevafuse** [comment]
@roadzy if you pm me an account & the video link that isn't work, I'll give it a try

**Comment by roadzy** [comment]
Dumb question how do I PM on here?

**Comment by nevafuse** [comment]
@roadzy ha, no clue.  You can just email me using my username at gmail.

**Comment by nevafuse** [comment]
@roadzy I got the test to work using your creds.  Let me know if it works for you.

**Comment by NGTmeaty** [comment]
I'll pull and check it out tonight.

**Comment by roadzy** [comment]
What am I doing wrong?

I did a git clone of the master and then did is a git checkout using the SHA value of the commit. Am I doing it wrong?  I also was reading about pull requests.  I have a feeling that is what I should be trying to use instead.  Thanks for answering all my questions.

**Comment by roadzy** [comment]
I was doing some more testing and found this error when trying the following URLs: https://www.bravotv.com/the-real-housewives-of-beverly-hills/season-9/ep-5-the-proof-hurts
https://www.bravotv.com/vanderpump-rules/season-7/ep-15-trouble-in-lala-land
https://www.bravotv.com/vanderpump-rules/season-7/ep-14-tom-vs-tom

I've tried now like 5-10 other ones and they work fine.  For some reason they decided to tweak the most recent ones that we were added for each show. 

Here is the verbose output from the first URL.

~/Desktop/youtube-dl/bin/youtube-dl --ap-mso auth_atlanticbb_net --ap-username xxxxxx@atlanticbb.net --ap-password xxxxxx --no-check-certificate https://www.bravotv.com/the-real-housewives-of-beverly-hills/season-9/ep-5-the-proof-hurts --verbose
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'auth_atlanticbb_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--no-check-certificate', 'https://www.bravotv.com/the-real-housewives-of-beverly-hills/season-9/ep-5-the-proof-hurts', '--verbose']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Git HEAD: 2232f5d1f
[debug] Python version 3.7.2 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BravoTV] ep-5-the-proof-hurts: Downloading webpage
ERROR: An extractor error has occurred. (caused by KeyError('ls_playlist')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 522, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/bravotv.py", line 60, in _real_extract
    ls_playlist = settings['ls_playlist']
KeyError: 'ls_playlist'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 522, in extract
    ie_result = self._real_extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/bravotv.py", line 60, in _real_extract
    ls_playlist = settings['ls_playlist']
KeyError: 'ls_playlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 794, in extract_info
    ie_result = ie.extract(url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 535, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('ls_playlist')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by nevafuse** [comment]
@roadzy the link that isn't working is just a preview link to a bunch of clips (for me at least).  If you click the preview link & use that page, it'll download the clip.  Can you confirm?  Maybe Bravo does that for episodes that haven't aired or aren't released online yet.

**Comment by roadzy** [comment]
> @roadzy the link that isn't working is just a preview link to a bunch of clips (for me at least). If you click the preview link & use that page, it'll download the clip. Can you confirm? Maybe Bravo does that for episodes that haven't aired or aren't released online yet.

Nope you are 100% right.  Weird that random episodes are previews and not full episodes?!?!  I noticed that episode 12 of one of the shows that has 16 episodes is a preview.  Overall I think this is working 100%

**Comment by roadzy** [comment]
Getting a 404 error now on one select video.  I know it works and is there because I played it in my browser.

youtube-dl --ap-mso auth_atlanticbb_net --ap-username  --ap-password --no-check-certificate  https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang -v
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'auth_atlanticbb_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--no-check-certificate', 'https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Git HEAD: 2232f5d1f
[debug] Python version 3.7.2 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BravoTV] ep-10-so-vain-in-solvang: Downloading webpage
[BravoTV] 6FpeqRgrsIZu: Retrieving Media Token
[ThePlatform] 6FpeqRgrsIZu: Downloading SMIL data
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 619, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by nevafuse** [comment]
@roadzy try now

**Comment by roadzy** [comment]
Ok do I have to do anything to get this new commit?  I have the branch check out.

**Comment by nevafuse** [comment]
@roadzy A git pull will probably tell you the branch has diverged since I force pushed.  You might have to reset it to get the new commit.  You can also try checking out the commit itself.

**Comment by roadzy** [comment]
I deleted everything and got it back.  Is there an easy way to tell that I'm using the newest version of yours?

**Comment by nevafuse** [comment]
Git log should have e6f966c at the top.  Otherwise just make sure the bravotv.py matches what's in this PR.

**Comment by roadzy** [comment]
> Git log should have [e6f966c](https://github.com/ytdl-org/youtube-dl/commit/e6f966c9619b353cb6d52651889adb0aac9cfd1a) at the top. Otherwise just make sure the bravotv.py matches what's in this PR.

Just to make sure, I copied the code from the bravotv.py script to my local box.

Here's the error:

[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--ap-mso', 'auth_atlanticbb_net', '--ap-username', 'PRIVATE', '--ap-password', 'PRIVATE', '--no-check-certificate', 'https://www.bravotv.com/vanderpump-rules/season-7/ep-10-so-vain-in-solvang', '-v']
[debug] Encodings: locale UTF-8, fs utf-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.03.09
[debug] Git HEAD: 2232f5d1f
[debug] Python version 3.7.2 (CPython) - Darwin-16.7.0-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.1.1, ffprobe 4.1.1, rtmpdump 2.4
[debug] Proxy map: {}
[BravoTV] ep-10-so-vain-in-solvang: Downloading webpage
[BravoTV] 6FpeqRgrsIZu: Retrieving Media Token
[ThePlatform] 6FpeqRgrsIZu: Downloading SMIL data
ERROR: Unable to download XML: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/extractor/common.py", line 619, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2225, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

**Comment by roadzy** [comment]
Everything seems good so this can get added to the next release.

**Comment by roadzy** [comment]
Just check and this isn't part of version 2019.04.01

**Comment by remitamine** [comment]
@nevafuse do not mix unrelated changes in a single PR.

**Comment by nevafuse** [comment]
@roadzy I don't have access to merge PRs.

@remitamine once separated, this will be merged?

**Comment by remitamine** [comment]
> once separated, this will be merged?

no, same as any PR, each one has to be reviewed and corrected before merging.

**Comment by roadzy** [comment]
@remitamine is there something I can do to help this move along?

**Comment by roadzy** [comment]
@remitamine @nevafuse anything I can do to help split this to get this resolved in the next build?

**Comment by remitamine** [comment]
extraction for BravoTV has been already fixed, and for the part related to `Atlantic Broadband` authentication, it's quite messy and not likely to be merged, a better solution needs to be done to support Adobe Pass authentication.

**Comment by roadzy** [comment]
@remitamine you mention a better solution... are you talking about a better piece of code or that Atlantic Broadband has to do something on their end?

**Comment by remitamine** [comment]
> @remitamine you mention a better solution... are you talking about a better piece of code or that Atlantic Broadband has to do something on their end?

a more generic solution that does not involve handling login flow for every TV provider separately.

**Pull request closed without merging**
