### PR TITLE
[myvideoge] New extractor

### PR DESCRIPTION
**Pull request by fonkap**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

New extractor for the site https://www.myvideo.ge/

### CODE REVIEW

**Comment by adrianheine** [comment]
Thanks for your PR! Please open separate pull requests for separate changes.

**Comment by fonkap** [comment]
> 
> 
> Thanks for your PR! Please open separate pull requests for separate changes.

I'm sorry, I didn't mean to do that. It should be fixed now.

**Comment by blackjack4494** [comment]
merged it into my fork youtube-dlc.
It's working :)

```
PS D:\gitkraken\youtube-dl> python3 -m youtube_dlc "https://www.myvideo.ge/v/3941048" -v -F
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['https://www.myvideo.ge/v/3941048', '-v', '-F']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dlc version 2020.09.06
[debug] Git HEAD: 55e106d1b
[debug] Python version 3.6.5 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg 4.2.1, ffprobe 4.2.1
[debug] Proxy map: {}
[MyVideoGe] 3941048: Downloading webpage
[info] Available formats for 3941048:
format code  extension  resolution note
0            mp4        unknown
1            mp4        unknown    (best)
```

**Review by dirkf — CHANGES_REQUESTED** [review]
This PR has been on the shelf for almost two years but its test is still just about working.

If you're still interested (after this time no reason you should be), I've added some review comments and proposed updates that amount to quite a re-work.

The manual format sorting that you had shouldn't have been necessary but we need a separate PR to use the labels from the `jwplayer_data` as format IDs (https://github.com/dirkf/youtube-dl/tree/df-kikuyan-jwplayer-patch).

If you aren't interested, I can push the changes myself in case it's useful to others.

**Comment by fonkap** [comment]
Hi dirkf , thanks for your work on this! Looks fine to me.
But I am not sure what I need to do :(

**Review by fonkap — COMMENTED** [review]
Looks fine to me!

**Comment by dirkf** [comment]
If you're happy to accept all the changes, then just let me progress it; if you happen to have time to test against some other site pages, that would be great. Or if you'd rather update it yourself, let me know.

Now there's PR#31000 that you should apply before testing.

**Comment by dirkf** [comment]
Moved to #31360 since the underlying repo is still subject to DMCA takedown.

**Pull request closed without merging**
