### PR TITLE
skip-http-head flag feature

### PR DESCRIPTION
**Pull request by Quitten**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Today I wanted to download mdp file. so i have a sepcific URL refer to this mdp file, this URL is one time URL, and its expires after 1 request.
youtube-dl is sending HEAD request before the GET one, cause that my URL is always expires and I wasn't able to download it.
By skipping the head request you can actually make it work and download the requested resource.

### CODE REVIEW

**Comment by dstftw** [comment]
I won't accept this until solid rationale is provided.

**Comment by Quitten** [comment]
@dstftw - You are right, I didn't explain the reason I needed it.
Today I wanted to download mdp file. so i have a sepcific URL refer to this mdp file, this URL is one time URL, and its expires after 1 request.
youtube-dl is sending HEAD request before the GET one, cause that my URL is always expires and I wasn't able to download it.
By skipping the head request you can actually make it work and download the requested resource.

**Comment by Quitten** [comment]
@dstftw  - WDYT???

**Comment by dstftw** [comment]
This is too specific and rare for general case and does not fit into Network Options category. Rather it's solely an option of the generic extractor thus:
1. Option should be prefixed with generic_.
2. It should start a new category Generic Extractor options.

**Comment by Quitten** [comment]
@dstftw - Files changed according your comments.

**Comment by keithah** [comment]
I have a url which said:
WARNING: Could not send HEAD request to http://(urlwithtoken): HTTP Error 405: Method Not Allowed

But once I applied this patch and used -skip-http-head, it worked fine. I've experienced this a few times where this patch has been useful, esp for CNBC/theplatform videos.

**Comment by davispuh** [comment]
Getting same warning, there are streaming servers that doesn't support `HEAD` so this PR would be useful to avoid that warning.

**Comment by devnoname120** [comment]
I also encountered this issue with a server that took forever to reply with `504: Gateway Time-out` to the `HEAD` request.

I was trying to record a live stream so it was extremely annoying. I missed the start due to the fact that I couldn't skip this `HEAD` request (which in my case is useless).

**Comment by pukkandan** [comment]
The head request is really just legacy code, and should be fully removed imo - no need of any option. See https://github.com/yt-dlp/yt-dlp/commit/61544381781d35276e1e7831456c653107ac8909

**Comment by devnoname120** [comment]
@pukkandan Awesome. I guess that this PR can be closed now as it's superseded by https://github.com/yt-dlp/yt-dlp/commit/61544381781d35276e1e7831456c653107ac8909

**Comment by pukkandan** [comment]
Not really - that commit is from yt-dlp, not this project. I just linked it for reference. It'll need to be ported and merged here

**Pull request closed without merging**
