### PR TITLE
[VVVVID] Support video/dash types, fixes #31030

### LINKED ISSUE #31030: ERROR: rtmpdump exited with code 1
## Checklist

- [ ] I'm reporting a broken site support issue
- [x ] I've verified that I'm running youtube-dl version **2021.12.17**
- [ ] I've checked that all provided URLs are alive and playable in a browser
- [x ] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x ] I've searched the bugtracker for similar bug reports including closed ones
- [ x] I've read bugs section in FAQ

## Verbose log

```
tech@Arcadia:~$ youtube-dl -F https://www.vvvvid.it/show/683/made-in-abyss/1542/693786/nanachi
[VVVVID] Downloading JSON metadata
[VVVVID] 693786: Downloading JSON metadata
[VVVVID] 693786: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[info] Available formats for 693786:
format code  extension  resolution note
rtsp-0       m3u8       unknown    
rtsp-1       m3u8       unknown    
rtmp-0       m3u8       unknown    
rtmp-1       m3u8       unknown    (best)
tech@Arcadia:~$ youtube-dl -f rtmp-1 https://www.vvvvid.it/show/683/made-in-abyss/1542/693786/nanachi
[VVVVID] Downloading JSON metadata
[VVVVID] 693786: Downloading JSON metadata
[VVVVID] 693786: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[download] Destination: Nanachi-693786.m3u8
ERROR: RTMP download detected but "rtmpdump" could not be run. Please install it.
tech@Arcadia:~$ sudo apt-get install rtmpdump 
[sudo] password for tech:                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-113 linux-headers-5.4.0-113-generic
  linux-image-5.4.0-113-generic linux-modules-5.4.0-113-generic
  linux-modules-extra-5.4.0-113-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed
  rtmpdump
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 44.4 kB of archives.
After this operation, 160 kB of additional disk space will be used.
Get:1 http://mirror.init7.net/ubuntu focal/universe amd64 rtmpdump amd64 2.4+20151223.gitfa8646d.1-2build1 [44.4 kB]
Fetched 44.4 kB in 0s (106 kB/s)  
Selecting previously unselected package rtmpdump.
(Reading database ... 507842 files and directories currently installed.)
Preparing to unpack .../rtmpdump_2.4+20151223.gitfa8646d.1-2build1_amd64.deb ...
Unpacking rtmpdump (2.4+20151223.gitfa8646d.1-2build1) ...
Setting up rtmpdump (2.4+20151223.gitfa8646d.1-2build1) ...
Processing triggers for man-db (2.9.1-1) ...
tech@Arcadia:~$ youtube-dl -f rtmp-1 https://www.vvvvid.it/show/683/made-in-abyss/1542/693786/nanachi
[VVVVID] Downloading JSON metadata
[VVVVID] 693786: Downloading JSON metadata
[VVVVID] 693786: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading m3u8 information
WARNING: Failed to download m3u8 information: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading f4m manifest
WARNING: Unable to download f4m manifest: HTTP Error 404: Not Found
[VVVVID] 693786: Downloading MPD manifest
WARNING: Failed to download MPD manifest: HTTP Error 404: Not Found
[download] Destination: Nanachi-693786.m3u8
[rtmpdump] Downloaded 0 bytes


ERROR: rtmpdump exited with code 1
tech@Arcadia:~$ youtube-dl -U
youtube-dl is up-to-date (2021.12.17)

```

## Description

I have a GNU/Linux Mint 20.3 MATE 64-bit with kernel 5.4.0-120-generic

On a certain website, it don't download me a video, but it detects the possibility

### PR DESCRIPTION
**Pull request by Kyraminol**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
The video_format of url in  #31030 is video/dash, as it's not present in the if ... if else ... if else ..., it goes to the last else that tries and fails to load the url. This fix should correctly handle video/dash as a m3u8 file.

### CODE REVIEW

**Comment by dirkf** [comment]
Thanks for your straightforward and uncontroversial PR!

As the site is strongly geo-blocked, please post a transcript of the new test passing, unlike this:
```
$ python test/test_download.py TestDownload.test_VVVVID_3
[VVVVID] Downloading JSON metadata
ERROR: None: Failed to parse JSON  (caused by ValueError('No JSON object could be decoded',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
...
$
```

**Comment by Kyraminol** [comment]
Sure, here is terminal output
```
python test/test_download.py TestDownload.test_VVVVID_3
[VVVVID] Downloading JSON metadata
[VVVVID] 693786: Downloading JSON metadata
[VVVVID] 693786: Downloading m3u8 information
[VVVVID] 693786: Downloading m3u8 information
[info] Writing video description metadata as JSON to: test_VVVVID_3_693786.info.json
.
----------------------------------------------------------------------
Ran 1 test in 2.185s

OK
```

And here the generated metadata info
```json
{
  "episode_number": 11,
  "season_number": 1,
  "formats": [
    {
      "format_id": "hls-default-audio-group-stream_0-0",
      "url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_fd-a.m3u8",
      "manifest_url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_fd.m3u8",
      "language": null,
      "ext": "mp4",
      "protocol": "m3u8",
      "preference": null,
      "vcodec": "none",
      "format": "hls-default-audio-group-stream_0-0 - audio only",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3562.1 Safari/537.36",
        "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5"
      }
    },
    {
      "format_id": "hls-default-audio-group-stream_0-1",
      "url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_sd-a.m3u8",
      "manifest_url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_sd.m3u8",
      "language": null,
      "ext": "mp4",
      "protocol": "m3u8",
      "preference": null,
      "vcodec": "none",
      "format": "hls-default-audio-group-stream_0-1 - audio only",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3562.1 Safari/537.36",
        "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5"
      }
    },
    {
      "format_id": "hls-492",
      "url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_sd-v.m3u8",
      "manifest_url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_sd.m3u8",
      "tbr": 492.219,
      "ext": "mp4",
      "fps": 23.976,
      "protocol": "m3u8",
      "preference": null,
      "width": 768,
      "height": 432,
      "vcodec": "avc1.4d4028",
      "acodec": "none",
      "format": "hls-492 - 768x432",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3562.1 Safari/537.36",
        "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5"
      }
    },
    {
      "format_id": "hls-2432",
      "url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_fd-v.m3u8",
      "manifest_url": "https://vvvvid.akamaized.net/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11_it_fd.m3u8",
      "tbr": 2432.461,
      "ext": "mp4",
      "fps": 23.976,
      "protocol": "m3u8",
      "preference": null,
      "width": 1920,
      "height": 1080,
      "vcodec": "avc1.640029",
      "acodec": "none",
      "format": "hls-2432 - 1920x1080",
      "http_headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3562.1 Safari/537.36",
        "Accept-Charset": "ISO-8859-1,utf-8;q=0.7,*;q=0.7",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Encoding": "gzip, deflate",
        "Accept-Language": "en-us,en;q=0.5"
      }
    }
  ],
  "thumbnail": "https://static.vvvvid.it/img/thumbs/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11-t.jpg",
  "episode_id": "11926",
  "id": "693786",
  "title": "Nanachi",
  "duration": 1420,
  "series": "Made in Abyss",
  "season_id": "1542",
  "episode": "Nanachi",
  "view_count": 6760,
  "like_count": 458,
  "repost_count": 8,
  "extractor": "VVVVID",
  "webpage_url": "https://www.vvvvid.it/show/683/made-in-abyss/1542/693786/nanachi",
  "webpage_url_basename": "nanachi",
  "extractor_key": "VVVVID",
  "playlist": null,
  "playlist_index": null,
  "thumbnails": [
    {
      "url": "https://static.vvvvid.it/img/thumbs/Dynit/MadeInAbyss/MadeInAbyss_S01Ep11-t.jpg",
      "id": "0"
    }
  ],
  "display_id": "693786",
  "season": "Season 1",
  "format": "hls-2432 - 1920x1080+hls-default-audio-group-stream_0-1 - audio only",
  "format_id": "hls-2432+hls-default-audio-group-stream_0-1",
  "width": 1920,
  "height": 1080,
  "resolution": null,
  "fps": 23.976,
  "vcodec": "avc1.640029",
  "vbr": null,
  "stretched_ratio": null,
  "acodec": null,
  "abr": null,
  "ext": "mp4",
  "fulltitle": "Nanachi",
  "_filename": "Nanachi-693786.mp4"
}
```
Let me know if anything else is needed :)

**Comment by pukkandan** [comment]
The site serves a HLS manifest with `video_type=video/dash`?!

**Comment by dirkf** [comment]
?! indeed!

**Comment by Kyraminol** [comment]
That site is weird, I've done some reverse engineering to it in the past for a side project of mine and it's full of weird stuff, like it does "encrypt" the video url not the video itself, and the decryption algorithm is in the js of the page

**Comment by pukkandan** [comment]
> like it does "encrypt" the video url not the video itself, and the decryption algorithm is in the js of the page

This is actually pretty common. Even youtube does this - but not even for the whole URL, but only for some query parameters

**Pull request merged**
