### PR TITLE
[niconico] Add heartbeat logic (closes #14582)

### LINKED ISSUE #14582: [niconico] Downloading long videos requires heartbeat signals
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2017.10.20*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running youtube-dl **2017.10.20**

### Before submitting an *issue* make sure you have:
- [x] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones

### What is the purpose of your *issue*?
- [x] Bug report (encountered problems with youtube-dl)

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
Python Console:
youtube_dl.YoutubeDL({'username': "username",'password': 'password','verbose':True}).extract_info(url="http://www.nicovideo.jp/watch/sm29409391")

[debug] Encodings: locale cp1252, fs utf-8, out UTF-8, pref cp1252
[debug] youtube-dl version 2017.10.20
[debug] Python version 3.6.2 - Windows-10-10.0.15063-SP0
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
...
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 795, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 849, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1619, in process_video_result
    self.process_info(new_info)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1892, in process_info
    success = dl(filename, info_dict)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 1831, in dl
    return fd.download(name, info)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\common.py", line 361, in download
    return self.real_download(filename, info_dict)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\http.py", line 297, in real_download
    self.report_error('giving up after %s retries' % retries)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\downloader\common.py", line 163, in report_error
    self.ydl.report_error(*args, **kargs)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 612, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\joshw\AppData\Local\Programs\Python\Python36-32\lib\site-packages\youtube_dl\YoutubeDL.py", line 582, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: giving up after 0 retries
```

### Description of your *issue*, suggested solution and other information

As of today, Nicovideo's seem to implemented a new session system. After every few minutes, the url of the video changes. This causes a 403 Forbidden error on the old url, Causing the Downloader to fail.
A screenshot of part of a video session:
chrome 2017-10-25 10 43 35 396

Resuming the download works just for a few minutes before the session is dropped.  
Note: I have only tested on a non-premium account. Im not sure if it applies to the permium accounts or not.

### PR DESCRIPTION
**Pull request by Gorfiend**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Based on PR #16495 to fix #14582. Adds heartbeat capability to FileDownloader and use it in the niconico extractor.

### CODE REVIEW

**Comment by ciffelia** [comment]
Any updates on this?

**Comment by Trevor-Guntren** [comment]
Works as expected on Linux. 

On Windows 10, with single executable binary built via `devscripts/wine-py2exe.sh` using 2.7.0 (CPython), I encounter the following error on all videos: 

```[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-vu', u'niconico@trevor.tguntren.com', u'-p', u'PRIVATE', u'https://www.nicovideo.jp/watch/sm33056722']
[debug] Encodings: locale cp932, fs mbcs, out cp932, pref cp932
[debug] youtube-dl version 2018.12.17
[debug] Python version 2.7.0 (CPython) - Windows-post2008Server-6.2.9200
[debug] exe versions: none
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm33056722: Downloading webpage
[niconico] sm33056722: Downloading JSON metadata for h264_2000kbps_720p-aac_128kbps
[niconico] sm33056722: Downloading JSON metadata for h264_1600kbps_540p-aac_128kbps
[niconico] sm33056722: Downloading JSON metadata for h264_600kbps_360p-aac_128kbps
[niconico] sm33056722: Downloading JSON metadata for h264_300kbps_360p-aac_128kbps
[niconico] sm33056722: Downloading JSON metadata for h264_2000kbps_720p-aac_64kbps
[niconico] sm33056722: Downloading JSON metadata for h264_1600kbps_540p-aac_64kbps
[niconico] sm33056722: Downloading JSON metadata for h264_600kbps_360p-aac_64kbps
[niconico] sm33056722: Downloading JSON metadata for h264_300kbps_360p-aac_64kbps
[debug] Default format spec: best/bestvideo+bestaudio
[debug] Invoking downloader on u'https://pa0531a22c8.dmc.nico/vod/ht2_nicovideo/nicovideo-sm33056722_85291b8127fd5bb0083511460567f0108282305b4bea4bcb5e3243f2ef60b256?ht2_nicovideo=30745746.82fnko_pl0j8j_243xbi2i51pzg'
[download] Heartbeat with 60 second interval...
ERROR: unable to download video data: <urlopen error [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyo", line 1909, in process_info
  File "youtube_dl\YoutubeDL.pyo", line 1848, in dl
  File "youtube_dl\downloader\common.pyo", line 393, in download
  File "youtube_dl\downloader\http.pyo", line 341, in real_download
  File "youtube_dl\downloader\http.pyo", line 109, in establish_connection
  File "youtube_dl\YoutubeDL.pyo", line 2212, in urlopen
  File "urllib2.pyo", line 391, in open
  File "urllib2.pyo", line 409, in _open
  File "urllib2.pyo", line 369, in _call_chain
  File "youtube_dl\utils.pyo", line 1140, in https_open
  File "urllib2.pyo", line 1148, in do_open
URLError: <urlopen error [Errno 1] _ssl.c:499: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>```

**Comment by panhartstuff** [comment]
So are we going to see this on the main build anytime soon?

**Comment by panhartstuff** [comment]
I'm occasionally getting the error `[download] Heartbeat failed`
What's the cause of this?

**Comment by Gorfiend** [comment]
> 
> 
> I'm occasionally getting the error `[download] Heartbeat failed`
> What's the cause of this?

That will be printed when a heartbeat request fails. Since it gets resent periodically, failures once in a while shouldn't be an issue, but does mean your network connection is not very reliable or something.

**Comment by CompulsiveConfig** [comment]
I've been using this code for months without issue. Unless I'm missing something, this should at least be ready for a review.

Are there any reasons particular to this request for the lack of a review at this point, or is it just a case of too many pull requests and not enough approved reviewers?

**Comment by Slider-Whistle** [comment]
Is this getting merged?

**Comment by MSauce** [comment]
Also interested in this. Any word on merging or do we need to maintain separate branch for this fix?

**Comment by animelover1984** [comment]
Since this likely isn't going to be merged any time soon, we have a fork of youtube-dl with this feature (and others for nico/bili) working here: https://github.com/animelover1984/youtube-dl

**Pull request closed without merging**
