### PR TITLE
[zoomus] Add new extractor

### PR DESCRIPTION
**Pull request by Romern**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

This is an extractor for Zoom.us recordings. Example link taken from here: https://github.com/ytdl-org/youtube-dl/issues/16597 .  
Other related Issues: https://github.com/ytdl-org/youtube-dl/issues/23573 , https://github.com/ytdl-org/youtube-dl/issues/24643 , https://github.com/ytdl-org/youtube-dl/issues/16597

I don't know how to get the tests working, somehow the md5 is None, even though the file is being downloaded when using ``--test`` manually.

### CODE REVIEW

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by Romern** [comment]
@d0u9 I have adjusted the regexes to ignore non important fields and some other code convention stuff.

**Comment by sheedy** [comment]
@Romern Does this PR avoid you having to open 2 separate tabs to dig out the request headers like I outlined [here](https://github.com/ytdl-org/youtube-dl/issues/23573#issuecomment-616936335) (#23573)?

**Comment by Romern** [comment]
@sheedy You simply drop the ``https://zoom.us/recording/play/*`` link into youtube-dl and add a password using if required.

**Comment by sjpickup** [comment]
Works well for me. Thanks @Romern

**Comment by o1dnik** [comment]
Hello @Romern,
cloning your repository and running with developer suggestion with `python -m youtube_dl` but it does not find the right extractor.
```
J-58_: Requesting header
WARNING: Falling back on generic information extractor.
```
am I doing something incorrectly? I can help to debug or in the extractor itself.

**Comment by Romern** [comment]
@o1dnik It seems like your link does not match the pattern, could you post it? If its sensitive, you can censor the id.

**Comment by o1dnik** [comment]
I'm not sure, but it should be publicly available. This is a TheEconomist magazine video recording 
https://economist.zoom.us/rec/play/7JV4Ibuqrjg3S9XEtgSDBvYoW9XsfKqs1HIfq_oEmRq0VnlSNVChZ7AVNOKcIcCsGRw-mFPuwGMJ-58_

**Comment by Romern** [comment]
@o1dnik it should now work for arbitrary long ids.

**Comment by o1dnik** [comment]
@Romern I confirm, works like charming! 👍

**Comment by karbassi** [comment]
@Romern Tested this with password and it works well.

@kcrkor thoughts on merging?

**Comment by kcrkor** [comment]
@karbassi Looks good to me.

**Comment by karbassi** [comment]
@dstftw thoughts on merging?

**Comment by Romern** [comment]
Continued here: https://github.com/ytdl-org/youtube-dl/pull/27002

**Pull request closed without merging**
