### PR TITLE
Sorting Video Formats

### PR DESCRIPTION
**Pull request by pukkandan**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [ ] New extractor
- [x] New feature

---

### Description of your *pull request* and other information

Added a new switch **--format-sort** which can be used to specify how the video formats will be sorted. It accepts a comma separated list of the fields that should be used for the sorting (e.g. "height,width,fps,filesize,tbr").

It accepts all the same options as the **field_preference** argument of **_sort_formats()** that can be used from the extractor (language_preference, quality, height, width, fps, filesize, filesize_approx, tbr, vbr, abr, format_id, proto_preference, ext_preference, audio_ext_preference, source_preference). The user-specified fields takes higher priority that those defined in the extractor which inturn takes higher priority that the default order.

### CODE REVIEW

**Comment by pukkandan** [comment]
When I checked the code with **flake8**, I see that many other parts of the file that I did not modify are also giving errors.

This is my first time ever contributing to a project. I followed all the guidelines given in **contributing.md**. I'd appreciate if someone can tell me what I need to do to fix the issue.

**Comment by pukkandan** [comment]
@dstftw Could you please tell me why this was labelled **do-not-merge**?

**Comment by dstftw** [comment]
There is already a [superior solution](#8125) which is still not flexible enough.

**Comment by pukkandan** [comment]
@dstftw As I understand that branch provides the extractor more control over the sorting. This pull request attempts to give more control to the **user** instead.

**Comment by dstftw** [comment]
Providing more control to user is just a matter of writing CLI wrapper passing data to core sorting mechanism.

**Comment by pukkandan** [comment]
Besides, #8125 was last updated 5yrs ago...

**Comment by pukkandan** [comment]
Sorry, I didn't mean to close this. I accidentally merged this branch with another. That is why this request shows a ton of irrelevant commits. Then I deleted the branch as I was trying to fix it. That caused the pull to be closed. I have force pushed [the branch](https://github.com/ytdl-org/youtube-dl/compare/master...pukkandan:format-sort) with only the correct commits. Sorry for the mess :(

**Pull request closed without merging**
