### PR TITLE
Acidcow

### PR DESCRIPTION
**Pull request by HussainMustafa**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information
Below is the link of the issue:

https://github.com/ytdl-org/youtube-dl/issues/24060

I have added one extractor file for site support. With this extractor people now can download video from acidcow.com. Before adding that video downloading was not possible. In the error it was returning two comma separated url's. I found out that there is no extractor file in the extractor folder. So that, I wrote one extractor for this website. I have tested with multiple links, Some are given below,
python3 -m youtube_dl -v https://acidcow.com/video/118488-trick_gone_wrong.html
python3 -m youtube_dl -v https://acidcow.com/video/118487-this_guy_knows_what_to_do.html

and below is the link which was stated with the issue,
python3 -m youtube_dl -v https://acidcow.com/video/116642-that_was_really_close.html

### CODE REVIEW

**Comment by HussainMustafa** [comment]
Hi, this is my first contribution to this open source project. Please provide me any suggestions or comment. It will be highly appreciable.

**Comment by dstftw** [comment]
Read coding conventions.

**Comment by HussainMustafa** [comment]
Before writing code and making pull request I checked with coding convention. Do I need to change something specifically that you noticed?

**Comment by dstftw** [comment]
I won't point all the same issues already described in coding conventions for every newcomer over and over again any longer. Bother to actually read it and see other PRs' reviews.

**Pull request closed without merging**
