### PR TITLE
[options] add an `add` flag for each `embed` flag

### PR DESCRIPTION
**Pull request by lucasew**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [ ] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

I sometimes download some songs with this program and, like with bash primitives, I forget which flag is `embed` and which is `add` for metadata and thumbnail. This PR just add an alias for `--embed-subs` and `--embed-thumbnail` replacing the `embed` word to `add` to solve this problem. Now if you want you can use all add instead of some add and some embed.

### CODE REVIEW

**Comment by dirkf** [comment]
If doing this, probably also make `--embed-metadata` an alias for `--add-metadata`. However I am not particularly enthusiastic about these changes in general. Maybe make them but don't advertise them, as with deprecated options?

**Comment by lucasew** [comment]
IDK for real, there is no conflict AFAIK to keep both.

Would even help because it could avoid confusion.

A deprecation may cause breakage and the cost of keeping both flags seems cheap.

**Comment by dirkf** [comment]
Basically the more options we have, the fewer people will make it through to the part of the manual they actually need. So my suggestion was to make these secret aliases that you can use if you know them, but not to advertise them in the documentation.

**Comment by lucasew** [comment]
Perfect

If someone got confused then the program will just magically accept it and carry on xD

**Comment by pukkandan** [comment]
The only `--add...` option that currently exists is `--add-metadata`. So why not just deprecate it in favor of `--embed-metadata`

**Comment by dirkf** [comment]
Which would also match yt-dlp!

Given that, I'm happy to align the options.

However the yt-dlp manual hasn't been consistently updated to use `--embed-metadata`.

**Pull request closed without merging**
