### PR TITLE
[extractor/ceskatelevize] fix POST request url to avoid redirection

### PR DESCRIPTION
**Pull request by kikuyan**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [ ] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [ ] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Resolves # 30151

Although not always happen, POST requests could be redirected, thus resulting in `ValueError: unknown url type: 'Error'`.
Adding `/` to the end of URL should prevent the redirection from occurring.

### CODE REVIEW

**Comment by kikuyan** [comment]
@pinochico
The dev members are absent for months, so no one knows when.
yt-dlp may solve the problem early. Search their repository.

**Comment by pinochico** [comment]
Ok,

the fix is merged now in master for app:
https://github.com/yt-dlp/yt-dlp

if you install this app, then new python3 and PyInstaller on the Mac (by homebrew), clone project to localhost (I use FORK), you can create new binary.
I maked and now I can load from ceskatelevize :)

**Comment by noahbroyles** [comment]
> The dev members are absent for months, so no one knows when
🙄

**Comment by kikuyan** [comment]
Closing. No longer useful now it seems.

**Pull request closed without merging**
