### PR TITLE
Add fix for #21469

### PR DESCRIPTION
**Pull request by SoneeJohn**
Add fix for #21469

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [ ] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [x] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

**Comment by Misterodd** [comment]
#21469 IS NOT FIXED
 After I "make" with the newest python file I still get the error:
`./youtube-dl/youtube-dl -x --embed-thumbnail  --mark-watched --add-metadata --console-title --audio-quality 0 --geo-bypass -i   --audio-format mp3 --verbose https://www.youtube.com/watch?v=DNZUKm0ApEM&list=PLiNVoBckLqLkuYqtb6YCaZXzCpt-X5Qht&index=2&t=0s
[1] 634
[2] 635
[3] 636
[2]   Done                    list=PLiNVoBckLqLkuYqtb6YCaZXzCpt-X5Qht
[3]+  Done                    index=2
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'-x', u'--embed-thumbnail', u'--mark-watched', u'--add-metadata', u'--console-title', u'--audio-quality', u'0', u'--geo-bypass', u'-i', u'--audio-format', u'mp3', u'--verbose', u'https://www.youtube.com/watch?v=DNZUKm0ApEM']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2019.06.08
[debug] Python version 2.7.15rc1 (CPython) - Linux-4.4.0-17763-Microsoft-x86_64-with-Ubuntu-18.04-bionic
[debug] exe versions: ffmpeg 3.4.4, ffprobe 3.4.4
[debug] Proxy map: {}
[youtube] DNZUKm0ApEM: Downloading webpage
[youtube] DNZUKm0ApEM: Downloading video info webpage
[youtube] {18} signature length 104, html5 player vfl49f_g4
[youtube] DNZUKm0ApEM: Downloading player https://www.youtube.com/yts/jsbin/player_ias-vfl49f_g4/en_US/base.js
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1256, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1320, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1256, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1320, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "./youtube-dl/youtube-dl/youtube_dl/YoutubeDL.py", line 796, in extract_info
    ie_result = ie.extract(url)
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1999, in _real_extract
    encrypted_sig, video_id, player_url, age_gate)
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1358, in _decrypt_signature
    'Signature extraction failed: ' + tb, cause=e)
ExtractorError: Signature extraction failed: Traceback (most recent call last):
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1348, in _decrypt_signature
    video_id, player_url, s
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1256, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/youtube.py", line 1320, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "./youtube-dl/youtube-dl/youtube_dl/extractor/common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError(u'Unable to extract \x1b[0;34mInitial JS player signature function name\x1b[0m; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
  ./youtube-dl/youtube-dl -x --embed-thumbnail --mark-watched --add-metadata --console-title --audio-quality 0 --geo-bypass -i --audio-format mp3 --verbose https://www.youtube.com/watch?v=DNZUKm0ApEM`

**Comment by SoneeJohn** [comment]
@Misterodd Thanks! I'll update the regex.

**Comment by Misterodd** [comment]
Thank you too. BTW Is the Issue tab gone?

**Comment by SoneeJohn** [comment]
@Misterodd Yes. It seems like an admin disabled Github issues (most likely a mistake)

**Comment by korangu** [comment]
Any admin please build and push the updated binary version as soon as possible.

**Comment by korangu** [comment]
@dstftw please bro

**Comment by Misterodd** [comment]
If you dont want to wait:
On Ubuntu you need the "make" and "pandoc" and "git" programm (via apt for example) installed:
after that:
git clone https://github.com/ytdl-org/youtube-dl.git
cd youtube-dl
make
now wait a moment, your HDD needs time.

**Comment by SoneeJohn** [comment]
> If you dont want to wait:
> On Ubuntu you need the "make" and "pandoc" and "git" programm (via apt for example) installed:
> after that:
> git clone https://github.com/ytdl-org/youtube-dl.git
> cd youtube-dl
> make
> now wait a moment, your HDD needs time.

Shouldn't you be cloning my patch repo (https://github.com/SoneeJohn/youtube-dl.git) switching to the `patch-1` branch? :-)

**Comment by Misterodd** [comment]
Oh Hatschuuuu. Lets try it again...Sorry,

**Comment by M10AC** [comment]
Sorry, it's impossible to download at this moment. There's a problem with js and Regex. Please help me, i'm busy with a university project.

[youtube] uk_wUT1CvWM: Downloading js player vfl49f_g4
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "\youtube.py", line 1348, in _decrypt_signature
    video_id, player_url, s
  File "\youtube_dl\extractor\youtube.py", line 1256, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "\youtube_dl\extractor\youtube.py", line 1320, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "\youtube_dl\extractor\youtube.py", line 1348, in _decrypt_signature
    video_id, player_url, s
  File "\youtube-dl-master\youtube_dl\extractor\youtube.py", line 1256, in _extract_signature_function
    res = self._parse_sig_js(code)
  File "\youtube-dl-master\youtube_dl\extractor\youtube.py", line 1320, in _parse_sig_js
    jscode, 'Initial JS player signature function name', group='sig')
  File "\youtube-dl-master\youtube_dl\extractor\common.py", line 1005, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug

**Comment by kaminsky9444** [comment]
https://github.com/SoneeJohn/youtube-dl/tree/patch-1 doesn't work for me ...

**Comment by SoneeJohn** [comment]
@kaminsky9444 I updated the regex can you try again?

**Comment by Misterodd** [comment]
code is 
 `git clone -b patch-1 https://github.com/SoneeJohn/youtube-dl.git`
now checked the youtube.py manually 
jup its the new file
`cd youtube-dl`
`make` <-- my stage
now I test it

**Comment by kaminsky9444** [comment]
> @kaminsky9444 I updated the regex can you try again?

Same problem.

**Comment by user001x** [comment]
Hi , I from Thailand , How to Fix Could you tell me…..?

**Comment by Misterodd** [comment]
@user001x 
Still working on, or better I just test it, for now.

**Comment by m33ts4k0z** [comment]
@pypy-vrc  binary for windows is working fine for me. If @SoneeJohn has an exe file, please let me know where to find it and I will try it.

**Comment by user001x** [comment]
> @ user001x
> ยังทำงานหรือดีกว่าฉันเพิ่งทดสอบตอนนี้

How to Fix ? , I still can't use

**Comment by SoneeJohn** [comment]
> > @kaminsky9444 I updated the regex can you try again?
> 
> Same problem.

Can you give me the video that is causing that issue?

**Pull request closed without merging**
