### PR TITLE
[Medialaan] Fix episode extractor

### LINKED ISSUE #16489: [Medialaan] Episode extractor broken, due to new api
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.05.18*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.05.18**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---

### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://vtm.be/video/volledige-afleveringen/id/vtm_20180504_VM067DA79_vtmwatch', u'--netrc', u'-v']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2018.05.18
[debug] Python version 2.7.13 (CPython) - Linux-4.13.0-41-generic-x86_64-with-debian-stretch-sid
[debug] exe versions: ffmpeg 2.8.14-0ubuntu0.16.04.1, ffprobe 2.8.14-0ubuntu0.16.04.1
[debug] Proxy map: {}
[Medialaan] vtm_20180504_VM067DA79_vtmwatch: Downloading webpage
[Medialaan] Logging in
[Medialaan] vtm_20180504_VM067DA79_vtmwatch: Downloading JSON metadata
ERROR: An extractor error has occurred. (caused by KeyError(u'response',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 503, in extract
    ie_result = self._real_extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/medialaan.py", line 207, in _real_extract
    data['response']['uri'], video_id, entry_protocol='m3u8_native',
KeyError: u'response'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 792, in extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 516, in extract
    raise ExtractorError('An extractor error has occurred.', cause=e)
ExtractorError: An extractor error has occurred. (caused by KeyError(u'response',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

```

---
### Description of your *issue*, suggested solution and other information

Medialaan is now using a new api for all their full episodes and therefore the videos can not be downloaded.  They are now using `https://vod.medialaan.io/vod/v2/videos/[VIDEO ID]/watch?access_token=[ENCODED ACCESS TOKEN]&apikey=[ENCODED API KEY]` to get the ```m3u8```  from. However we require an access token that is not currently in the data we get and it changes every call.

### PR DESCRIPTION
**Pull request by kenavera**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [X] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [X] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [X] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [X] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Medialaan changed their api, so that downloading did not work anymore for any authentication requiring video. Also videos that could be previously downloaded.

In this pull request, the api endpoint that is used is changed. As this required an access token we did not had previously this had to be fetched first (they also fetch this separate on the site itself). 
New json url is  ```https://vod.medialaan.io/vod/v2/videos/[VIDEO ID]/watch?access_token=[ENCODED ACCESS TOKEN]&apikey=[ENCODED API KEY]```

Fixes #16489

### CODE REVIEW

**Comment by xplorr** [comment]
This fix worked for a few days, but fails again since GDPR 25/5/2018.

**Comment by kenavera** [comment]
@xplorr Thanks for the comment, hadn't noticed it yet.
Will see if I can fix this.

**Comment by mrBliss** [comment]
To disable the GDPR warning, add the following line as the third line of `_real_extract` (after extracting the `site_id`):

```python
self._set_cookie('%s.be' % site_id, 'pws', 'functional|analytics')
```
Unfortunately, the next problem is that the url of the `hls-encrypted` entry is empty, at least for the recent videos I tried it with. So only DRM secured streams remain :(

**Comment by xplorr** [comment]
Thx @mrBliss , this is bad news.

**Comment by VuokkoVuorinnen** [comment]
The hls-encrypted stream is empty, but it now has a 'dash-cenc' stream, and a 'hls-fairplay' stream. Can we do anything with those?

**Comment by kenavera** [comment]
I tried, but failed.
As the data is all encrypted, I believe that this has not been done here codewise and is not doable.
I'm not the most experienced here working on these things.

**Pull request closed without merging**
