### PR TITLE
Split Thumbzilla out into it's own extractor.

### PR DESCRIPTION
**Pull request by twaddington**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

Split Thumbzilla out into it's own extractor.

This simplifies the pornhub extractor and makes it easier to maintain in
the future.

### CODE REVIEW

**Comment by dstftw** [comment]
No, as this is the same extractor thus must have the same id for download archives.

**Comment by twaddington** [comment]
> No, as this is the same extractor thus must have the same id for download archives. &mdash; @dstftw 

Can you elaborate on this? Wouldn't it have the same id since it delegates the download to the pornhub extractor via a url_result?

**Comment by dstftw** [comment]
There is no point in extractor that only redirects and introduces unnecessary code duplication.

**Comment by twaddington** [comment]
@dstftw code duplication isn't a bad thing if it makes the code more maintainable. Thumbzilla used to host videos from other tube sites that aren't Pornhub so this could would allow us to delegate out to different extractors depending on the source site.

**Comment by twaddington** [comment]
Plus, if Thumbzilla ever goes away entirely, it makes it easier to delete the relevant code since it's not intermingled with the pornhub logic.

**Comment by dstftw** [comment]
No, code duplication does not make code more maintainable, never.
>host videos from other tube sites that aren't Pornhub

Provide concrete URLs and add implement support for them.

**Comment by twaddington** [comment]
lol, okay. Thanks for the warm welcome @dstftw.

**Comment by Hrxn** [comment]
> No, as this is the same extractor thus must have the same id for download archives.

Do they really have the same video IDs? Why would that even make any sense?

**Pull request closed without merging**
