### PR TITLE
[twitter] Add support for public Nitter instances

### PR DESCRIPTION
**Pull request by B0pol**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

[Nitter](https://github.com/zedeus/nitter) is a privacy-friendly twitter web-client. The url are the same, except the domain, it depends on the [Nitter instances](https://github.com/zedeus/nitter/wiki/Instances) you use. So I added the possibility to download from nitter link, it just consists of accepting Nitter url, the rest of the extractor is untouched.

I tested tweets with videos, it works, and also images, which link is kinda different: ``https://nitter.net/pic/https%3A%2F%2Fabs.twimg.com%2Fsticky%2Fdefault_profile_images%2Fdefault_profile.png``, it works.

Url to test:
+ https://nitter.net/realmemeskids/status/1238408755215138816
+ https://nitter.net/pic/https%3A%2F%2Fabs.twimg.com%2Fsticky%2Fdefault_profile_images%2Fdefault_profile.png
+ … (change any twitter link, from https://twitter.com/whatever to https://nitterinstanceyouwant/whatever)

### CODE REVIEW

**Comment by dstftw** [comment]
1. Add tests.
2. flake8.

**Comment by B0pol** [comment]
@dstftw done

**Comment by zedeus** [comment]
Personally I would prefer a new simple extractor that just reads the m3u8 url instead of going the Twitter route. This protects the user's privacy since it doesn't connect to Twitter directly, instead proxying the video through the Nitter server.

**Comment by mjsir911** [comment]
It looks like this is similar to the `_INVIDIOUS_SITES`  & bar the previously aforementioned privacy concerns, there is not an invidious extractor so mirroring that I do not believe there should be a separate nitter extractor.

**Pull request closed without merging**
