### PR TITLE
[extractor/xvideos] Fixes 404 Issue Currently Present On XVIDEOS.COM (Issue #30271)

### PR DESCRIPTION
**Pull request by scramblr**
This simple addition of '0' fixes the 404 issues many are having with downloading videos from xvideos.com. Tested on linux, windows, and macOS.

## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [x] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [ ] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

A small change in the way the web server is handling URLs caused the parser to interpret valid URLs as 404. Adding zero to the end of URL parser string to allow the porn to continue flowing freely! This enables the new format on xvideos.com website to work as intended with youtube-dl. 

Tested with Linux, Windows, macOS. Specifically for baseline testing, [debug] Python version 3.9.9 (CPython) - macOS-12.0.1-x86_64-i386-64bit

Thanks

### CODE REVIEW

**Comment by scramblr** [comment]
Added testing output:
```
➜  Downloads youtube-dl --verbose "https://www.xvideos.com/video14517807/married_neighbors_fucking_hidden_"
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', 'https://www.xvideos.com/video14517807/married_neighbors_fucking_hidden_']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.06.06
[debug] Python version 3.9.9 (CPython) - macOS-12.0.1-x86_64-i386-64bit
[debug] exe versions: ffmpeg 4.4.1, ffprobe 4.4.1, rtmpdump 2.4
[debug] Proxy map: {}
[XVideos] 14517807: Downloading webpage
[XVideos] 14517807: Downloading m3u8 information
[debug] Default format spec: bestvideo+bestaudio/best
[debug] Invoking downloader on 'https://cdn77-vid.xvideos-cdn.com/PV6cuP1mU0jGft9Hh4wgZA==,1639718019/videos/hls/bb/87/52/bb87520db05eddbaf3b3c87a29c4fb9d/hls-360p.m3u8'
[hlsnative] Downloading m3u8 manifest
[hlsnative] Total fragments: 39
[download] Destination: MARRIED NEIGHBORS FUCKING HIDDEN!-14517807.mp4
[download] 100% of 24.42MiB in 00:25
[debug] ffmpeg command line: ffprobe -show_streams 'file:MARRIED NEIGHBORS FUCKING HIDDEN!-14517807.mp4'
[ffmpeg] Fixing malformed AAC bitstream in "MARRIED NEIGHBORS FUCKING HIDDEN!-14517807.mp4"
[debug] ffmpeg command line: ffmpeg -y -loglevel repeat+info -i 'file:MARRIED NEIGHBORS FUCKING HIDDEN!-14517807.mp4' -c copy -f mp4 -bsf:a aac_adtstoasc 'file:MARRIED NEIGHBORS FUCKING HIDDEN!-14517807.temp.mp4'
```

**Comment by kikuyan** [comment]
Duplicate of #30271.

**Comment by scramblr** [comment]
Hi there,

I'm happy to withdraw my merge, but it just seemed like the previous fix had issues. I did indeed notice the other PR, but I made sure to test across win/*nix/macOS and verify no issues, while the other PR seemed to have some problems (at least when I took a quick glance at the thread originally) 

That said, both fixes are indeed basically the same, it just seemed like submitting a more clean approach with multi-platform testing confirmed was possibly a cleaner approach.

Again, I can withdraw if you'd rather I do that, just trying to help! 
Cheers

> Duplicate of #30278.

**Comment by mo-han** [comment]
thanks
works
cheers

**Comment by kikuyan** [comment]
It's just confusing to have the same fix.

**Comment by emmanuelgboyega** [comment]
- [ ] Yah!

**Comment by emmanuelgboyega** [comment]
Ok

**Comment by linuxstv** [comment]
Thank you, it works. This should be merged.

**Pull request closed without merging**
