### PR TITLE
[novamov] fix for all included provider (WholeCloud, NowVideo, BitVid, CloudTime, AuroraVid)

### PR DESCRIPTION
**Pull request by FDMX2**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

---

### Before submitting a *pull request* make sure you have:
- [x] At least skimmed through [adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections
- [x] [Searched](https://github.com/rg3/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [ ] Improvement
- [x] New extractor
- [ ] New feature

---

### Description of your *pull request* and other information

NovaMov changed their way of providing video files. Now a form must be posted to get the direct link to the video file. 

This impacts following hoster:
- WholeCloud
- NowVideo
- BitVid (former known as VideoWeed)
- CloudTime
- AuroraVid

### CODE REVIEW

**Comment by dstftw** [comment]
Read
>[adding new extractor tutorial](https://github.com/rg3/youtube-dl#adding-support-for-a-new-site) and [youtube-dl coding conventions](https://github.com/rg3/youtube-dl#youtube-dl-coding-conventions) sections

and fix all issues.

**Comment by FDMX2** [comment]
The only test failing right now on the build server is for CloudTime (HTTP Error 400: Bad Request), when it tries to download the webpage. But it does pass locally. 
Can anyone give me a hint how make the test pass or at least bypass it on the build server? 
(If nothing helps I will just remove it...)

**Comment by mwalcott3** [comment]
Rather than make 2 separate web requests its probably faster to grab the weird toker id thing from this script tag `<script type="text/javascript" src="/api/toker.php?f=mmdbb1b48eddbb4e43b8e98c3112499ad1.mp4"></script>` which is found on the "Continue to video" page  by using the following regex `r'toker\.php\?f=([^"]+)'` and then construct a download url directly with something like this `video_url = 'http://%s/download.php?file=%s' % (self._HOST, the_toker_id_thing_grabbed_from_beforehand)` . This ends up with something like the following "http://www.nowvideo.sx/download.php?file=mmdbb1b48eddbb4e43b8e98c3112499ad1.mp4"

Besides being a bit faster by avoiding a second url request this also avoids a problem I was having with some links were it would give you a mpd file instead of a mp3 or flv

**Comment by FDMX2** [comment]
ok, thanks for the info i will look into it and see what can be done

**Comment by FDMX2** [comment]
I added the proposed method, but I have not found a single example where an mpd file is provided.
Is youtube-dl capable to handle mpd files without any further work?

**Pull request closed without merging**
