### PR TITLE
[Turner] Raise proper error in case of geoblocking

### PR DESCRIPTION
**Pull request by adrianheine**
### Before submitting a *pull request* make sure you have:
- [x] [Searched](https://github.com/ytdl-org/youtube-dl/search?q=is%3Apr&type=Issues) the bugtracker for similar pull requests
- [x] Read [adding new extractor tutorial](https://github.com/ytdl-org/youtube-dl#adding-support-for-a-new-site)
- [x] Read [youtube-dl coding conventions](https://github.com/ytdl-org/youtube-dl#youtube-dl-coding-conventions) and adjusted the code to meet them
- [ ] Covered the code with tests (note that PRs without tests will be REJECTED)
- [x] Checked the code with [flake8](https://pypi.python.org/pypi/flake8)

### In order to be accepted and merged into youtube-dl each piece of code must be in public domain or released under [Unlicense](http://unlicense.org/). Check one of the following options:
- [x] I am the original author of this code and I am willing to release it under [Unlicense](http://unlicense.org/)
- [ ] I am not the original author of this code but it is in public domain or released under [Unlicense](http://unlicense.org/) (provide reliable evidence)

### What is the purpose of your *pull request*?
- [ ] Bug fix
- [x] Improvement
- [ ] New extractor
- [ ] New feature

---

Raise a georestricted error instead of a generic one.

### CODE REVIEW

**Comment by dstftw** [comment]
Add a test.

**Comment by adrianheine** [comment]
How can I add a test for this?

**Comment by dstftw** [comment]
In `_TESTS` of some affected extractor obviously.

**Comment by adrianheine** [comment]
Sorry, but that doesn't help me much. How can a test in `_TESTS` specify that it expects geoblocking? I haven't found an example of this.

**Comment by dstftw** [comment]
By adding a comment.

**Comment by adrianheine** [comment]
So you want me to add a regular test that will fail when I'm outside of the restricted countries (but obviously passes otherwise) with a comment about it being georestricted?

**Comment by dstftw** [comment]
The test must be only matching. Full geo restricted tests are useless since non-deterministic.

**Comment by adrianheine** [comment]
I cannot reproduce what this was intended for. #28066 fixes the issue for AdultSwim.

**Pull request closed without merging**
